Repository kiali/kiali, pull requests merged in 2018-08, with the labels that each got.

#393 KIALI-1211 Add a new label validation at WorkloadList endpoint level, check labels and istioSidecar
  handlers/workloads.go
  handlers/workloads_test.go
  kubernetes/client.go
  kubernetes/kubernetes_service.go
  kubernetes/kubetest/mock.go
  services/business/services.go
  services/business/workloads.go
  services/business/workloads_test.go
  services/models/pod.go
  services/models/service.go
  services/models/workload.go
  swagger.json
Labels: do not merge, master-only

#431 Improve Makefile help for devs
  Makefile
Labels: enhancement

#418 KIALI-1304 Service details update - workloads added, deployments/pods removed
  doc.go
  routing/routes.go
  services/business/services.go
  services/business/workloads.go
  services/models/pod.go
  services/models/service.go
  services/models/service_test.go
  services/models/workload.go
  services/models/workload_test.go
  swagger.json
Labels: enhancement, master-only

#433 KIALI-1347 Add type in workloadEndpoint Details and validations by Workload
  README.adoc
  config/config.go
  doc.go
  handlers/workloads.go
  routing/routes.go
  services/business/checkers/pod_checker.go
  services/business/checkers/pod_checker_test.go
  services/business/checkers/pods/label_presence_checker.go
  services/business/istio_validations.go
  services/models/workload.go
  swagger.json
Labels: do not merge

#429 KIALI-1336 Repurpose service metrics endpoint to a strict definition …
  handlers/apps.go
  handlers/services.go
  handlers/services_test.go
  prometheus/metrics.go
  prometheus/metrics_definitions.go
  prometheus/prometheustest/client_test.go
  services/business/services.go
Labels: do not merge, master-only

#445 KIALI-1379 Fix service metric support
  handlers/apps_test.go
  handlers/graph.go
  handlers/namespaces_test.go
  handlers/services_test.go
  handlers/testdata/test_namespace_graph.expected
  handlers/workloads_test.go
  prometheus/metrics.go
  prometheus/prometheustest/client_test.go
Labels: UI changes required

#460 KIALI-1423 Move Jaeger iFrame to external links
  Makefile
  README.adoc
  config.yaml
  config/config.go
  deploy/kubernetes/kiali-configmap.yaml
  deploy/kubernetes/kiali.yaml
  deploy/openshift/kiali-configmap.yaml
  deploy/openshift/kiali.yaml
  handlers/grafana.go
  handlers/grafana_test.go
  handlers/jaeger.go
  handlers/utils.go
  server/server.go
Labels: do not merge
