Repository kiali/kiali, pull requests merged in 2018-06, with the labels that each got.

#258 KIALI-913 Fix auth PopUp when access to url different to /api
  server/server.go
  server/server_test.go
Labels: bug

#270 KIALI-923 Allow authentication by route
  config/authentication.go
  routing/router.go
  routing/router_test.go
  routing/routes.go
  server/server.go
  server/server_test.go
Labels: enhancement

#252 KIALI-817 Change shape of nodes on different namespaces
  graph/cytoscape/cytoscape.go
  handlers/graph.go
  handlers/testdata/test_multi_namespace_graph.expected
  handlers/testdata/test_namespace_graph.expected
  handlers/testdata/test_service_graph.expected
Labels: do not merge
