Repository kiali/kiali, pull requests merged in 2019-09, with the labels that each got.

#1643 Add some special handling of PassthroughCluster service
  business/services.go
  graph/meta.go
  graph/protocol.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/dead_node.go
  graph/telemetry/istio/appender/istio_details.go
  graph/telemetry/istio/appender/istio_details_test.go
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/unused_node.go
  graph/telemetry/istio/appender/unused_node_test.go
  graph/telemetry/istio/istio.go
  graph/types.go
  models/service.go
Labels: team/saturn

#1353 Adding Maistra Molecule Testing with Maistra UBI8 1.0.0
  operator/deploy/operator_without_ao.yaml
  operator/molecule/README.md
  operator/molecule/asserts/multi-tenancy/label_selector_asserts.yml
  operator/molecule/asserts/multi-tenancy/role_asserts.yml
  operator/molecule/docker/Dockerfile
  operator/molecule/maistra-e2e/assets/elasticsearch-operator.yaml
  operator/molecule/maistra-e2e/assets/jaeger-operator.yaml
  operator/molecule/maistra-e2e/assets/maistra-cr.yaml
  operator/molecule/maistra-e2e/assets/maistra-operator.yaml
  operator/molecule/maistra-e2e/create.yml
  operator/molecule/maistra-e2e/destroy.yml
  operator/molecule/maistra-e2e/molecule.yml
  operator/molecule/maistra-e2e/playbook.yml
  operator/molecule/maistra-e2e/prepare.yml
  operator/molecule/multi-tenancy/molecule.yml
  operator/molecule/multi-tenancy/playbook.yml
  operator/molecule/requirements.txt
  tests/e2e/config/env.yaml
Labels: qe, team/saturn

#1678 Allow customized links to Grafana
  config/config.go
  handlers/grafana.go
  handlers/grafana_test.go
  models/grafana_info.go
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  swagger.json
Labels: frontend changes required

#1688 Renaming Maistra Molecule Test Folder
  operator/molecule/maistra-e2e-test/assets/bookinfo/bookinfo-crd.yaml
  operator/molecule/maistra-e2e-test/assets/bookinfo/complex_mesh-crd.yaml
  operator/molecule/maistra-e2e-test/assets/bookinfo/operator.yaml
  operator/molecule/maistra-e2e-test/assets/bookinfo/redhat_tutorial-crd.yaml
  operator/molecule/maistra-e2e-test/assets/bookinfo/role_binding.yaml
  operator/molecule/maistra-e2e-test/assets/bookinfo/service_account.yaml
  operator/molecule/maistra-e2e-test/assets/elasticsearch-operator.yaml
  operator/molecule/maistra-e2e-test/assets/jaeger-operator.yaml
  operator/molecule/maistra-e2e-test/assets/maistra-cr.yaml
  operator/molecule/maistra-e2e-test/assets/maistra-operator.yaml
  operator/molecule/maistra-e2e-test/assets/secret.yaml
  operator/molecule/maistra-e2e-test/create.yml
  operator/molecule/maistra-e2e-test/destroy.yml
  operator/molecule/maistra-e2e-test/molecule.yml
  operator/molecule/maistra-e2e-test/playbook.yml
  operator/molecule/maistra-e2e-test/prepare.yml
  operator/molecule/maistra-e2e-test/tests/tasks.yml
Labels: qe, team/saturn

#1684 OLM Molecule Test
  operator/molecule/olm-test/assets/bookinfo/bookinfo-crd.yaml
  operator/molecule/olm-test/assets/bookinfo/complex_mesh-crd.yaml
  operator/molecule/olm-test/assets/bookinfo/operator.yaml
  operator/molecule/olm-test/assets/bookinfo/redhat_tutorial-crd.yaml
  operator/molecule/olm-test/assets/bookinfo/role_binding.yaml
  operator/molecule/olm-test/assets/bookinfo/service_account.yaml
  operator/molecule/olm-test/assets/catalog-sources.yaml
  operator/molecule/olm-test/assets/elasticsearch-subscription.yaml
  operator/molecule/olm-test/assets/jaeger-subscription.yaml
  operator/molecule/olm-test/assets/kiali-subscription.yaml
  operator/molecule/olm-test/assets/maistra-cr.yaml
  operator/molecule/olm-test/assets/servicemesh-subscription.yaml
  operator/molecule/olm-test/create.yml
  operator/molecule/olm-test/destroy.yml
  operator/molecule/olm-test/molecule.yml
  operator/molecule/olm-test/playbook.yml
  operator/molecule/olm-test/prepare.yml
  operator/molecule/olm-test/tests/tasks.yml
Labels: qe, team/saturn

#1630 KIALI#1605 Update route to redirect http to https
  operator/roles/kiali-deploy/templates/openshift/route.yaml
Labels: team/saturn

#1672 Add missing dependency, vendor others that we forgot.
  glide.lock
  glide.yaml
  server/server.go
  vendor/github.com/NYTimes/gziphandler/.gitignore
  vendor/github.com/NYTimes/gziphandler/.travis.yml
  vendor/github.com/NYTimes/gziphandler/CODE_OF_CONDUCT.md
  vendor/github.com/NYTimes/gziphandler/CONTRIBUTING.md
  vendor/github.com/NYTimes/gziphandler/LICENSE
  vendor/github.com/NYTimes/gziphandler/README.md
  vendor/github.com/NYTimes/gziphandler/go.mod
  vendor/github.com/NYTimes/gziphandler/go.sum
  vendor/github.com/NYTimes/gziphandler/gzip.go
  vendor/github.com/NYTimes/gziphandler/gzip_go18.go
  vendor/github.com/NYTimes/gziphandler/gzip_go18_test.go
  vendor/github.com/NYTimes/gziphandler/gzip_test.go
  vendor/github.com/NYTimes/gziphandler/testdata/benchmark.json
Labels: bug, team/saturn

#1711 Support request_duration_milliseconds for latency reporting in mixer-less telemetry
  business/dashboards.go
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/appender/response_time_test.go
  prometheus/metrics_definitions.go
  prometheus/prometheustest/client_test.go
Labels: frontend changes required, team/saturn

#1726 Fix potential nil value in workloads
  models/workload.go
  models/workload_test.go
Labels: backport/v1.0

#1736 Fix wrong k-charted version in glide.yaml
  glide.lock
  glide.yaml
Labels: bug
