Repository kiali/kiali, pull requests merged in 2019-11, with the labels that each got.

#1763 Adding E2E VirtualService Create/Delete Test
  tests/e2e/tests/test_api_methods.py
Labels: qe, team/saturn

#1870 Fix wizards for Istio 1.4
  business/istio_config.go
  models/destination_rule.go
  models/virtual_service.go
Labels: team/saturn

#1853 [hack] install istio using istioctl. this is how istio 1.4 is installed now
  hack/istio/install-bookinfo-demo.sh
  hack/istio/install-istio-via-istioctl.sh
Labels: team/saturn

#1881 Remove legacy adapters/templates
  kubernetes/types.go
Labels: team/jupiter

#1888 Remove null values from JSON on Create operations
  business/istio_config.go
  models/destination_rule.go
  models/virtual_service.go
  util/maps.go
  util/maps_test.go
Labels: team/jupiter

#1919 issue 1917 - add v1.9.1 operator manifests for community and upstream
  operator/manifests/kiali-community/1.9.1/kiali.crd.yaml
  operator/manifests/kiali-community/1.9.1/kiali.monitoringdashboards.crd.yaml
  operator/manifests/kiali-community/1.9.1/kiali.v1.9.1.clusterserviceversion.yaml
  operator/manifests/kiali-community/kiali.package.yaml
  operator/manifests/kiali-upstream/1.9.1/kiali.crd.yaml
  operator/manifests/kiali-upstream/1.9.1/kiali.monitoringdashboards.crd.yaml
  operator/manifests/kiali-upstream/1.9.1/kiali.v1.9.1.clusterserviceversion.yaml
  operator/manifests/kiali-upstream/kiali.package.yaml
Labels: team/saturn

#1872 Add annotations for display config
  business/services.go
  config/config.go
  models/additional_item.go
  models/service.go
  models/workload.go
  models/workload_test.go
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  operator/roles/kiali-deploy/vars/main.yml
  swagger.json
Labels: frontend changes required

#1912 Prevent empty reference on validations
  business/checkers/destinationrules/multi_match_checker.go
Labels: bug

#1916 Return 403 instead 500 for accessible_namespaces filtered queries
  business/namespaces.go
  handlers/apps.go
  handlers/errors.go
  handlers/health.go
  handlers/istio_config.go
  handlers/services.go
  handlers/threescale.go
  handlers/workloads.go
Labels: team/jupiter

#1925 Filter OS projects with accessible_namespaces for consistency
  business/namespaces.go
Labels: team/jupiter

#1927 Refresh Kiali caches after Create/Update/Delete
  business/istio_config.go
  kubernetes/cache/cache.go
  kubernetes/cache/istio.go
  kubernetes/cache/kubernetes.go
Labels: team/jupiter

#1801 Add Jaeger configuration for namespaceSelector
  business/jaeger_helper.go
  config/config.go
  handlers/jaeger.go
  models/jaeger_info.go
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  swagger.json
Labels: enhancement, team/jupiter

#1940 issue 1934 - fix the name in deploy script - it is now tracing, not jaeger
  operator/deploy/deploy-kiali-operator.sh
Labels: team/saturn

#1856 [hack] this is to support installing upstream istio 1.4.
  hack/istio/install-istio-kiali-via-helm.sh
Labels: team/saturn

#1948 Removing deadlock in IstioConfigList
  business/istio_config.go
Labels: backlog

#1958 [operator] be able to configure the replica count. this is going to b…
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
  operator/roles/kiali-deploy/templates/openshift/deployment.yaml
Labels: enhancement, team/saturn

#1959 [operator] customize priority class name and pod annotations
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
  operator/roles/kiali-deploy/templates/openshift/deployment.yaml
Labels: enhancement, team/saturn

#1932 Adding NamespaceValidations endpoint with summary of validations
  doc.go
  handlers/namespaces.go
  models/istio_validation.go
  models/istio_validation_test.go
  routing/routes.go
  swagger.json
Labels: frontend changes required

#1967 issue 1561 the operator SDK exposes metrics; tell prometheus to scrape it
  operator/deploy/operator.yaml
  operator/manifests/kiali-community/1.10.0/kiali.crd.yaml
  operator/manifests/kiali-community/1.10.0/kiali.monitoringdashboards.crd.yaml
  operator/manifests/kiali-community/1.10.0/kiali.v1.10.0.clusterserviceversion.yaml
  operator/manifests/kiali-community/kiali.package.yaml
  operator/manifests/kiali-ossm/X.X.X/kiali.crd.yaml
  operator/manifests/kiali-ossm/X.X.X/kiali.monitoringdashboards.crd.yaml
  operator/manifests/kiali-ossm/X.X.X/kiali.vX.X.X.clusterserviceversion.yaml
  operator/manifests/kiali-ossm/kiali-ossm.package.yaml
  operator/manifests/kiali-upstream/1.10.0/kiali.crd.yaml
  operator/manifests/kiali-upstream/1.10.0/kiali.monitoringdashboards.crd.yaml
  operator/manifests/kiali-upstream/1.10.0/kiali.v1.10.0.clusterserviceversion.yaml
  operator/manifests/kiali-upstream/kiali.package.yaml
Labels: team/saturn

#1982 [operator] update role permissions for all istio types
  operator/deploy/role.yaml
  operator/manifests/kiali-community/1.10.0/kiali.v1.10.0.clusterserviceversion.yaml
  operator/manifests/kiali-ossm/X.X.X/kiali.vX.X.X.clusterserviceversion.yaml
  operator/manifests/kiali-upstream/1.10.0/kiali.v1.10.0.clusterserviceversion.yaml
  operator/roles/kiali-deploy/templates/kubernetes/role-viewer.yaml
  operator/roles/kiali-deploy/templates/kubernetes/role.yaml
  operator/roles/kiali-deploy/templates/openshift/role-viewer.yaml
  operator/roles/kiali-deploy/templates/openshift/role.yaml
Labels: team/saturn

#1980 Create Jaeger Endpoints for Traces
  appstate/jaeger_state.go
  business/apps_test.go
  business/health_test.go
  business/istio_config_test.go
  business/istio_validations_test.go
  business/jaeger.go
  business/jaeger_helper.go
  business/layer.go
  business/services.go
  business/services_test.go
  business/tls_test.go
  business/workloads_test.go
  config/config.go
  doc.go
  graph/telemetry/istio/appender/dead_node_test.go
  graph/telemetry/istio/appender/istio_details_test.go
  graph/telemetry/istio/appender/service_entry_test.go
  graph/telemetry/istio/appender/sidecars_check_test.go
  handlers/jaeger.go
  handlers/services.go
  jaeger/client.go
  jaeger/jaegertest/mock.go
  jaeger/services.go
  jaeger/traces.go
  jaeger/util.go
  kiali.go
  operator/deploy/kiali/kiali_cr.yaml
  operator/deploy/kiali/kiali_cr_dev_servicemesh.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  operator/roles/kiali-deploy/tasks/main.yml
  routing/routes.go
  status/discover.go
  status/versions.go
  swagger.json
  vendor/github.com/prometheus/procfs/meminfo.go
Labels: enhancement
