Repository kiali/kiali, pull requests merged in 2019-06, with the labels that each got.

#1111 KIALI-2963 Use configured istio namespace for grafana/jaeger/prometheus
  config/config.go
  handlers/grafana.go
  models/grafana_info.go
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  operator/roles/kiali-deploy/tasks/main.yml
  status/discover.go
  swagger.json
Labels: UI changes required :art:

#1146 KIALI-3025 Wrong Jaeger base query when defined
  config/config.go
  operator/deploy/kiali/kiali_cr.yaml
  status/discover.go
Labels: bug :bug:

#1167 KIALI-3031 Add missing fields in VS/SE
  models/service_entry.go
  models/virtual_service.go
  swagger.json
Labels: UI changes required :art:, backport_v1.0

#1179 KIALI-3054 need auto-detection to work for jaeger under all situations
  status/discover.go
Labels: backport_v1.0

#1177 KIALI-3049 delete oauth client by name
  operator/deploy/deploy-kiali-operator.sh
Labels: backport_v1.0

#1155 Fix Jaeger in kubernetes, improve discovery, clean
  business/services.go
  status/discover.go
Labels: backport_v1.0, bug :bug:, enhancement :rocket:

#1135 KIALI-2976 Support hiding Jaeger and Grafana based on authorization
  handlers/grafana.go
  handlers/jaeger.go
Labels: UI changes required :art:, backport_v1.0

#1182 Prepare for major release workflow
  RELEASING.adoc
  deploy/jenkins-ci/Dockerfile
  deploy/jenkins-ci/Makefile
  operator/Makefile
Labels: backport_v1.0

#1172 KIALI-3034 ServiceEntry nodes should represent an actual ServiceEntry
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/protocol.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/istio_details.go
  graph/telemetry/istio/appender/istio_details_test.go
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/service_entry_test.go
  graph/telemetry/istio/istio.go
  graph/types.go
Labels: UI changes required :art:

#1187 KIALI-3057 Fixing MeshPolicy error when user hasn't access to any namespace
  business/tls.go
  business/tls_test.go
Labels: UI changes required :art:, backport_v1.0

#1197 Wrong override of prometheus auth config
  config/config.go
Labels: backport_v1.0

#1198 KIALI-3072 MTLS validations fixed when user doesn't have access to istio ns
  business/istio_validations.go
Labels: backport_v1.0
