Repository kiali/kiali, pull requests merged in 2019-05, with the labels that each got.

#1030 KIALI-2676 Don't panic when there are no endpoints for a given service
  business/services.go
  models/service.go
  swagger.json
Labels: UI changes required :art:

#1022 KIALI-2446 AutoDiscover Jaeger and Grafana from backend
  business/jaeger_helper.go
  config/config.go
  handlers/grafana.go
  handlers/jaeger.go
  kubernetes/client.go
  kubernetes/kubernetes_service.go
  kubernetes/kubetest/mock.go
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  operator/roles/kiali-deploy/tasks/openshift/os-grafana.yml
  operator/roles/kiali-deploy/tasks/openshift/os-jaeger.yml
  operator/roles/kiali-deploy/tasks/openshift/os-main.yml
  status/discover.go
  status/versions.go
Labels: enhancement :rocket:

#1065 KIALI-2848 Cannot specify the Tracing URL anymore
  status/discover.go
Labels: bug :bug:

#1050 KIALI-2639 Support 3scale adapter Istio config
  business/istio_config.go
  business/istio_config_test.go
  business/layer.go
  business/threescale.go
  business/threescale_test.go
  config/config.go
  doc.go
  handlers/threescale.go
  kubernetes/client.go
  kubernetes/istio_rules_service.go
  kubernetes/kubetest/mock.go
  models/threescale.go
  routing/routes.go
  swagger.json
Labels: UI changes required :art:

#1082 KIALI-2892 Jaeger traces not work when the user use Istio upstream with a QUERY_BASE_PATH
  business/jaeger_helper.go
  config/config.go
  kiali.go
  status/discover.go
Labels: bug :bug:

#1089 KIALI-2893 Show the traces tab if jaeger is configured but application is not available and show warning
  business/jaeger_helper.go
Labels: bug :bug:

#1097 KIALI-2902 Missing tracing tab
  business/jaeger_helper.go
  kiali.go
Labels: bug :bug:

#1102 KIALI-2795 Move mesh-wide tls status to tls endpoint
  business/tls.go
  business/tls_test.go
  doc.go
  handlers/root.go
  handlers/tls.go
  routing/routes.go
  status/mtls_status.go
  status/status.go
  swagger.json
Labels: UI changes required :art:

#1100 KIALI-2570 Adding Selector labels to ServiceDetails endpoint
  models/service.go
  swagger.json
Labels: UI changes required :art:
