Repository kiali/kiali, pull requests merged in 2019-08, with the labels that each got.

#1309 KIALI-3181 Support OSSM in version checks
  config/config.go
  status/versions.go
  status/versions_test.go
Labels: backport_v1.0

#1319 KIALI-2938 Better support detailed error messages
  handlers/base.go
  handlers/graph.go
Labels: UI changes required :art:

#1326 KIALI-3193 Add support for ServiceMeshPolicy,ServiceMeshRbacConfig
  business/checkers/destinationrules/disabled_namespacewide_mtls_checker.go
  business/checkers/destinationrules/meshwide_mtls_checker.go
  business/checkers/destinationrules/namespacewide_mtls_checker.go
  business/checkers/mesh_policies_checker.go
  business/checkers/meshpolicies/mesh_mtls_checker.go
  business/checkers/service_mesh_policies_checker.go
  business/istio_config.go
  business/istio_validations.go
  business/istio_validations_test.go
  business/tls.go
  business/tls_test.go
  handlers/istio_config.go
  kubernetes/client.go
  kubernetes/istio_details_service.go
  kubernetes/kubernetes_service.go
  kubernetes/kubetest/mock.go
  kubernetes/types.go
  models/cluster_rbac_config.go
  models/istio_config.go
  models/istio_validation.go
  models/mesh_policy.go
  operator/deploy/role.yaml
  operator/roles/kiali-deploy/templates/openshift/role-viewer.yaml
  operator/roles/kiali-deploy/templates/openshift/role.yaml
  swagger.json
Labels: UI changes required :art:, backport_v1.0, do not merge :stop_sign:

#1321 KIALI-3195 Support Istio component namespaces
  business/dashboards.go
  business/istio_config.go
  business/istio_validations.go
  business/threescale.go
  business/tls.go
  config/config.go
  doc.go
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/options.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/istio_details_test.go
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/appender/response_time_test.go
  graph/telemetry/istio/appender/security_policy.go
  graph/telemetry/istio/appender/security_policy_test.go
  graph/telemetry/istio/appender/service_entry_test.go
  graph/telemetry/istio/appender/sidecars_check.go
  graph/telemetry/istio/appender/util.go
  graph/telemetry/istio/istio.go
  graph/types.go
  handlers/config.go
  handlers/graph.go
  handlers/graph_test.go
  handlers/threescale.go
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  operator/roles/kiali-deploy/tasks/main.yml
  operator/roles/kiali-deploy/vars/main.yml
  swagger.json
Labels: UI changes required :art:
