Repository kiali/kiali, pull requests merged in 2019-02, with the labels that each got.

#803 KIALI-2148 Adding mTLS status into status endpoint
  business/istio_config.go
  business/istio_config_test.go
  business/namespaces.go
  deploy/kubernetes/clusterrole.yaml
  deploy/openshift/clusterrole.yaml
  kubernetes/client.go
  kubernetes/istio_details_service.go
  kubernetes/kubetest/mock.go
  kubernetes/types.go
  status/mtls_status.go
  status/status.go
  tests/data/mesh_policy_data.go
Labels: UI changes required :art:

#831 KIALI-2311 Show MeshPolicies into IstioConfig section
  business/istio_config.go
  handlers/istio_config.go
  handlers/istio_config_test.go
  kubernetes/client.go
  kubernetes/istio_details_service.go
  kubernetes/kubetest/mock.go
  models/istio_config.go
  models/mesh_policy.go
  swagger.json
Labels: UI changes required :art:

#839 Fix json camelCase on istio labels
  config/config.go
Labels: UI changes required :art:

#748 KIALI-1906 Make changes in the Kiali-UI to integrate Jaeger Components
  README.adoc
  business/jaeger_helper.go
  business/services.go
  config/config.go
  kiali.go
  models/service.go
  swagger.json
Labels: UI changes required :art:, do not merge :stop_sign:, enhancement :rocket:

#842 KIALI-2381 Adding support to RbacConfig, ServiceRole and ServiceRoleBindings to IstioConfig
  business/istio_config.go
  business/istio_validations.go
  deploy/kubernetes/clusterrole.yaml
  deploy/openshift/clusterrole.yaml
  handlers/istio_config.go
  kubernetes/client.go
  kubernetes/istio_details_service.go
  kubernetes/kubetest/mock.go
  kubernetes/types.go
  models/cluster_rbac_config.go
  models/istio_config.go
  models/service_role.go
  models/service_role_binding.go
  swagger.json
Labels: UI changes required :art:

#871 KIALI-2448 Handle destination workloads in different namespace than requested service
  graph/appender/dead_node_test.go
  graph/appender/istio_details.go
  graph/appender/istio_details_test.go
  graph/appender/response_time.go
  graph/appender/response_time_test.go
  graph/appender/security_policy.go
  graph/appender/security_policy_test.go
  graph/appender/service_entry_test.go
  graph/appender/sidecars_check_test.go
  graph/appender/unused_node.go
  graph/appender/unused_node_test.go
  graph/cytoscape/cytoscape.go
  graph/graph.go
  handlers/graph.go
  handlers/graph_test.go
  handlers/testdata/test_app_graph.expected
  handlers/testdata/test_app_node_graph.expected
  handlers/testdata/test_complex_graph.expected
  handlers/testdata/test_service_graph.expected
  handlers/testdata/test_service_node_graph.expected
  handlers/testdata/test_versioned_app_graph.expected
  handlers/testdata/test_versioned_app_node_graph.expected
  handlers/testdata/test_workload_graph.expected
  handlers/testdata/test_workload_node_graph.expected
  swagger.json
Labels: UI changes required :art:

#876 KIALI-2093 - Verify rules for both sending+receiving are enabled
  business/checkers/mesh_policies_checker.go
  business/checkers/meshpolicies/mtls_checker.go
  business/checkers/meshpolicies/mtls_checker_test.go
  business/istio_config.go
  business/istio_validations.go
  business/istio_validations_test.go
  kubernetes/istio_details_service.go
  models/istio_validation.go
  tests/data/mesh_policy_data.go
Labels: kiali.io changes required :memo:
