Repository kiali/kiali, pull requests merged in 2019-10, with the labels that each got.

#1751 Allow to specify the full path of the executable
  hack/istio/install-istio-kiali-via-helm.sh
Labels: maintenance, team/saturn

#1687 Capture and report request.host information when it is configured
  graph/api/api_test.go
  graph/api/testdata/test_app_graph.expected
  graph/api/testdata/test_app_node_graph.expected
  graph/api/testdata/test_complex_graph.expected
  graph/api/testdata/test_service_graph.expected
  graph/api/testdata/test_service_node_graph.expected
  graph/api/testdata/test_versioned_app_graph.expected
  graph/api/testdata/test_versioned_app_node_graph.expected
  graph/api/testdata/test_workload_graph.expected
  graph/api/testdata/test_workload_node_graph.expected
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/protocol.go
  graph/telemetry/common.go
  graph/telemetry/istio/appender/dead_node.go
  graph/telemetry/istio/appender/istio_details.go
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/istio.go
  graph/types.go
  swagger.json
Labels: frontend changes required, team/saturn

#1756 Implementing edge aggregation for nodes "talking" to a ServiceEntry
  graph/api/api.go
  graph/protocol.go
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/service_entry_test.go
Labels: team/saturn

#1782 Fixing Paths on Maistra E2E Test
  operator/molecule/maistra-e2e-test/molecule.yml
  operator/molecule/olm-test/create.yml
Labels: qe, team/saturn

#1769 Return 404, not 500, when service is not found in apidoc call
  business/services.go
Labels: team/saturn

#1774 OSSM-102 CVE-2019-11253
  glide.lock
  glide.yaml
  hack/istio/bookinfo-mlts-mongodb.yaml
  hack/istio/fortio-client.yaml
  vendor/github.com/gorilla/mux/.circleci/config.yml
  vendor/github.com/gorilla/mux/.github/stale.yml
  vendor/github.com/gorilla/mux/.travis.yml
  vendor/github.com/gorilla/mux/ISSUE_TEMPLATE.md
  vendor/github.com/gorilla/mux/README.md
  vendor/github.com/gorilla/mux/doc.go
  vendor/github.com/gorilla/mux/example_cors_method_middleware_test.go
  vendor/github.com/gorilla/mux/middleware.go
  vendor/github.com/gorilla/mux/middleware_test.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/mux_test.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/NOTICE
  vendor/gopkg.in/yaml.v2/README.md
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/benchmark_test.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
  vendor/gopkg.in/yaml.v2/example_embedded_test.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/parserc.go
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
Labels: backlog

#1795 Update base images when building Kiali containers
  Makefile
  operator/Makefile
Labels: team/saturn

#1817 Documentation of Kiosk mode
  README.adoc
Labels: team/saturn

#1830 [operator] fix molecule tests so they use the route and LoadBalancer
  operator/molecule/common/tasks.yml
  operator/molecule/ldap-test/ldap-service.yaml
  operator/molecule/ldap-test/prepare-ldap.yml
Labels: team/saturn

#1840 rip out the obsolete env var and default settings
  config/config.go
  config/config_test.go
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
Labels: team/saturn
