Repository kiali/kiali, pull requests merged in 2020-10, with the labels that each got.

#3292 molecule tests - allow dump logs on error to be turned off
  make/Makefile.molecule.mk
Labels: team/saturn

#3302 [v1.24] Custom dashboards: implement "enabled" config flag
  business/dashboards.go
  config/config.go
  handlers/apps.go
Labels: operator changes required

#3282 Support parsed log messages for the workload logs
  business/test_util.go
  business/workloads.go
  business/workloads_test.go
Labels: team/saturn

#3126 Add proxy status in the health
  business/health.go
  business/health_test.go
  business/layer.go
  business/proxy_status.go
  business/workloads.go
  kubernetes/cache/cache.go
  kubernetes/cache/proxy_status.go
  kubernetes/client.go
  kubernetes/istio.go
  kubernetes/kubetest/mock_istio.go
  models/health.go
  models/pod.go
  models/pod_test.go
  swagger.json
Labels: frontend changes required, operator changes required

#3319 Add 'tls' Spec to virtual service matching.
  models/virtual_service.go
Labels: team/saturn

#3326 Fix the path of the cookie for OpenShift authentication strategy
  handlers/authentication.go
Labels: team/saturn

#3329 Fix the path of the cookie for OpenShift authentication strategy
  handlers/authentication.go
Labels: team/saturn

#3316 Short term expiration cache for Health Prom queries
  config/config.go
  prometheus/cache.go
  prometheus/client.go
Labels: operator changes required

#3331 Implement duration filtering for logs
  business/test_util.go
  business/workloads.go
  business/workloads_test.go
  doc.go
  handlers/workloads.go
  swagger.json
Labels: team/saturn

#3339 Remove mixer/telemetry-v1 use of request_duration_seconds
  business/dashboards.go
  business/dashboards_test.go
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/appender/response_time_test.go
  prometheus/metrics_definitions.go
  prometheus/prometheustest/client_test.go
  tests/e2e/tests/test_kiali_application_endpoint.py
  tests/e2e/tests/test_kiali_service_endpoint.py
  tests/e2e/tests/test_kiali_workload_endpoint.py
Labels: team/saturn

#3344 Remove Mixer + RBAC + 3Scale deps
  business/checkers/authorization/service_binding_checker.go
  business/checkers/authorization/service_binding_checker_test.go
  business/checkers/authorization/service_checker.go
  business/checkers/authorization/service_checker_test.go
  business/checkers/no_service_checker.go
  business/checkers/service_role_bind_checker.go
  business/istio_config.go
  business/istio_config_test.go
  business/istio_validations.go
  config/config.go
  handlers/config.go
  kubernetes/client.go
  kubernetes/istio.go
  kubernetes/kubernetes.go
  kubernetes/types.go
  models/attribute_manifest.go
  models/cluster_rbac_config.go
  models/http_api_spec.go
  models/http_api_spec_binding.go
  models/istio_config.go
  models/istio_rule.go
  models/istio_rule_test.go
  models/mesh_policy.go
  models/quota_spec.go
  models/quota_spec_binding.go
  models/rbac_config.go
  models/service_role.go
  models/service_role_binding.go
  status/versions.go
  swagger.json
  tests/data/service_role_data.go
Labels: frontend changes required, operator changes required

#3352 workload logs: remove support for logs blob
  business/workloads.go
  business/workloads_test.go
Labels: team/saturn

#3360 make sure the dev has the latest code by git pulling the helm chart
  make/Makefile.helm.mk
Labels: maintenance

#3310 [OpenId] Support for clusters without OIDC integration (no RBAC will be possible)
  business/openid_auth.go
  config/config.go
  go.mod
  go.sum
  handlers/authentication.go
Labels: docs, operator changes required, team/saturn
