Repository kiali/kiali, pull requests merged in 2020-08, with the labels that each got.

#3068 [hack] install addons since istioctl doesn't do it anymore
  hack/istio/install-istio-via-istioctl.sh
Labels: maintenance

#3070 make client id prefix configurable
  business/openshift_oauth.go
  config/config.go
Labels: operator changes required, team/saturn

#3073 Update request_operation support to Istio 1.7 and Travel 2.0
  hack/istio/install-travel-agency-demo.sh
Labels: backlog

#3076 Remove Jenkins generation of the all-in-one yaml
  deploy/jenkins-ci/Makefile.operator.jenkins
Labels: operator changes required, team/saturn

#3090 The helm charts moved to a separate repo - change the makefiles to accomodate this change
  Makefile
  deploy/jenkins-ci/Makefile.operator.jenkins
  hack/run-molecule-tests.sh
  make/Makefile.helm.mk
  make/Makefile.molecule.mk
  make/Makefile.operator.mk
Labels: maintenance, team/saturn

#3085 Add namespace update endpoint
  business/namespaces.go
  config/config.go
  doc.go
  handlers/config.go
  handlers/namespaces.go
  kubernetes/cache/namespaces.go
  kubernetes/client.go
  kubernetes/kubernetes.go
  kubernetes/kubetest/mock_kubernetes.go
  kubernetes/kubetest/mock_openshift.go
  routing/routes.go
  swagger.json
Labels: frontend changes required, operator changes required

#3098 expect the helm-charts as a peer to the operator directory always
  .gitignore
  README.adoc
  hack/run-molecule-tests.sh
  make/Makefile.helm.mk
Labels: maintenance, team/saturn

#3106 V1.22 master merge
  .gitignore
  Makefile
  README.adoc
  business/checkers/authorization/mtls_enabled_checker.go
  business/checkers/authorization/no_host_checker.go
  business/checkers/authorization/no_host_checker_test.go
  business/checkers/authorization_policies_checker.go
  business/checkers/common/multi_match_selector_checker.go
  business/checkers/common/multi_match_selector_checker_test.go
  business/checkers/common/workload_selector_checker.go
  business/checkers/common/workload_selector_checker_test.go
  business/checkers/request_authentication_checker.go
  business/dashboards.go
  business/istio_status.go
  business/istio_status_test.go
  business/istio_validations.go
  business/istio_validations_test.go
  business/iter8.go
  business/jaeger.go
  business/namespaces.go
  business/openshift_oauth.go
  config/config.go
  deploy/jenkins-ci/Makefile.operator.jenkins
  doc.go
  go.mod
  go.sum
  hack/istio/install-istio-via-istioctl.sh
  hack/istio/install-travel-agency-demo.sh
  hack/run-molecule-tests.sh
  handlers/config.go
  handlers/jaeger.go
  handlers/metrics.go
  handlers/namespaces.go
  jaeger/client.go
  jaeger/spans.go
  jaeger/traces.go
  jaeger/util.go
  kubernetes/cache/istio.go
  kubernetes/cache/namespaces.go
  kubernetes/client.go
  kubernetes/host.go
  kubernetes/host_test.go
  kubernetes/iter8.go
  kubernetes/kubernetes.go
  kubernetes/kubetest/mock_kubernetes.go
  kubernetes/kubetest/mock_openshift.go
  kubernetes/types.go
  make/Makefile.helm.mk
  make/Makefile.molecule.mk
  make/Makefile.operator.mk
  models/istio_validation.go
  models/iter8.go
  routing/routes.go
  status/versions.go
  swagger.json
Labels: team/saturn

#3109 when deleting istio, remove the addons too
  hack/istio/install-istio-via-istioctl.sh
Labels: backlog, maintenance, team/saturn

#3107 jenkins build for helm charts
  deploy/jenkins-ci/Jenkinsfile
  deploy/jenkins-ci/Makefile.helm.jenkins
  deploy/jenkins-ci/README.md
  deploy/jenkins-ci/jenkins_ref/jobs/kiali-release/config.xml
Labels: maintenance, team/saturn

#3121 Block Helm charts builds on snapshots
  deploy/jenkins-ci/Jenkinsfile
Labels: team/saturn

#3128 Bump go to version 1.14.7
  .travis.yml
  Makefile
  deploy/jenkins-ci/Dockerfile
Labels: maintenance, team/saturn

#3089 Use remote cluster's api server
  README.adoc
  go.sum
  kubernetes/client.go
  kubernetes/secret.go
  kubernetes/token.go
Labels: team/saturn

#3144 Fix WebRoot redirects for OIDC
  routing/router.go
  routing/router_test.go
Labels: team/saturn

#3149 Update Cache with potential perf scenarios
  business/apps.go
  business/health.go
  business/istio_config.go
  business/istio_status.go
  business/istio_validations.go
  business/istio_validations_test.go
  business/iter8.go
  business/layer.go
  business/services.go
  business/tls.go
  business/workloads.go
  config/config.go
  kubernetes/cache/cache.go
  kubernetes/cache/istio.go
  kubernetes/cache/kubernetes.go
  kubernetes/client.go
  kubernetes/istio.go
  kubernetes/kubetest/mock_istio.go
  kubernetes/types.go
Labels: operator changes required

#3142 Add support for cluster API proxies on OpenId strategy
  business/layer.go
  config/config.go
  kubernetes/client.go
  kubernetes/client_factory.go
  kubernetes/secret.go
  models/workload.go
Labels: team/saturn
