Repository kiali/kiali, pull requests merged in 2020-12, with the labels that each got.

#3490 Be able to enable operator profiler from make
  Makefile
  hack/run-molecule-tests.sh
  make/Makefile.molecule.mk
  make/Makefile.operator.mk
Labels: enhancement, maintenance, operator changes required, team/saturn

#3498 get the run-operator-playbook target to run all the way through and with profiler
  make/Makefile.operator.mk
Labels: maintenance, team/saturn

#3501 Provide better flexibility when building helm charts.
  Makefile
  make/Makefile.helm.mk
Labels: maintenance, team/saturn

#3400 Add ConfigDump endpoint at pod level
  business/proxy_status.go
  business/services.go
  config/config.go
  doc.go
  go.mod
  go.sum
  handlers/proxy_status.go
  kubernetes/client.go
  kubernetes/envoy.go
  kubernetes/istio.go
  kubernetes/kubetest/mock_istio.go
  models/config_dump.go
  routing/routes.go
  swagger.json
  util/config_dump/port_forwarder.go
Labels: area/management, frontend changes required, operator changes required

#3509 need to use the GO env var in makefiles
  Makefile
  make/Makefile.build.mk
Labels: maintenance, team/saturn

#3510 [hack] Allow user to dictate what protocol (git or https) to use when git cloning repos.
  hack/ci-openshift-molecule-tests.sh
Labels: maintenance, team/saturn

#3473 publish multi-arch backend and operator images to quay.io
  deploy/jenkins-ci/Jenkinsfile
  deploy/jenkins-ci/Makefile
  deploy/jenkins-ci/Makefile.operator.jenkins
  make/Makefile.container.mk
Labels: team/saturn

#3520 hack script can now be told what version of Istio to download
  hack/ci-openshift-molecule-tests.sh
Labels: maintenance, team/saturn

#3521 [hack] when installing istio, do not pull images from docker.io anymore
  hack/istio/install-istio-via-istioctl.sh
Labels: maintenance, team/saturn

#3495 Add proxy to OpenId metadata http requests
  business/openid_auth.go
  config/config.go
Labels: team/saturn

#3524 when rebuilding molecule image, don't use the cache so force rebuild will pull in everything anew
  make/Makefile.molecule.mk
Labels: team/saturn

#3525 create the helm charts so people don't have to remember to do it when running tests
  make/Makefile.molecule.mk
Labels: team/saturn

#3522 Support new 'includeIdleEdges` option. False by default.
  doc.go
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/options.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/idle_node.go
  graph/telemetry/istio/appender/idle_node_test.go
  graph/telemetry/istio/istio.go
  swagger.json
  tests/e2e/tests/test_kiali_external_host_node.py
Labels: frontend changes required, team/saturn

#3530 get the "run-operator-playbook" make target to behave more like a deployed operator
  make/Makefile.operator.mk
Labels: maintenance, operator changes required

#3531 Add Github Actions CI to Kiali repo
  .github/workflows/kiali-ci.yml
Labels: backlog, maintenance, team/saturn
