Repository kiali/kiali, pull requests merged in 2020-01, with the labels that each got.

#2063 [operator] strip all values in the dicts that are of type NoneType
  operator/deploy/kiali/kiali_cr.yaml
  operator/molecule/null-cr-values-test/kiali-cr.yaml
  operator/molecule/null-cr-values-test/molecule.yml
  operator/molecule/null-cr-values-test/playbook.yml
  operator/roles/kiali-deploy/filter_plugins/stripnone.py
  operator/roles/kiali-deploy/vars/main.yml
Labels: team/saturn

#2071 [operator] OSSM-127 update manifests for kiali ossm 1.1
  operator/manifests/kiali-ossm/1.1.0/kiali.crd.yaml
  operator/manifests/kiali-ossm/1.1.0/kiali.monitoringdashboards.crd.yaml
  operator/manifests/kiali-ossm/1.1.0/kiali.v1.1.0.clusterserviceversion.yaml
  operator/manifests/kiali-ossm/kiali-ossm.package.yaml
Labels: team/saturn

#2067 [operator] create proper annotations on k8s ingress when https is disabled on the backend
  operator/roles/kiali-deploy/templates/kubernetes/ingress.yaml
Labels: team/saturn

#2079 [operator] update base ansible image
  operator/build/Dockerfile
  operator/deploy/kiali/kiali_cr.yaml
  operator/deploy/kiali/kiali_cr_dev.yaml
  operator/deploy/kiali/kiali_cr_dev_servicemesh.yaml
Labels: enhancement, team/saturn

#2114 Add a new make target 'cluster-status'
  make/Makefile.cluster.mk
Labels: enhancement

#2017 Move jaegerInfo and return if there is an integration and errorMessage
  business/jaeger.go
  business/services.go
  doc.go
  handlers/jaeger.go
  jaeger/client.go
  jaeger/info.go
  jaeger/services.go
  jaeger/spans.go
  jaeger/traces.go
  jaeger/types.go
  models/jaeger_info.go
  swagger.json
Labels: backport/v1.12, team/jupiter

#2118 Traces tab should be visible just with InClusterURL configured
  jaeger/info.go
Labels: backport/v1.12

#2121 Improve log messages for 3scale and traces
  business/services.go
  handlers/threescale.go
  jaeger/spans.go
Labels: backport/v1.12, team/jupiter

#2110 MeshPolicies#details show now validations
  business/checkers/mesh_policies_checker.go
Labels: backport/v1.12, bug

#2116 [operator] allow user to override ingress spec and annotation sections to be able to customize it
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  operator/roles/kiali-deploy/tasks/main.yml
  operator/roles/kiali-deploy/templates/kubernetes/ingress.yaml
  operator/roles/kiali-deploy/templates/openshift/route.yaml
Labels: enhancement, team/saturn

#2108 VirtualService#Route validation: one route under 100 weight warning
  business/checkers/virtual_service_checker_test.go
  business/checkers/virtual_services/route_checker.go
  business/checkers/virtual_services/route_checker_test.go
  models/istio_validation.go
Labels: backport/v1.12, docs

#2156 Service Details load Error when Jaeger is configured wrongly
  config/config.go
  jaeger/client.go
  jaeger/info.go
  jaeger/traces.go
Labels: backport/v1.12

#2161 fix the grafana and jaeger default urls created by the makefile
  make/Makefile.operator.mk
Labels: team/saturn

#2171 [operator] don't look for version if not on openshift.
  operator/roles/kiali-deploy/tasks/main.yml
Labels: backport/v1.12, team/saturn

#2172 [backport] [operator] don't look for version if not on openshift.
  operator/roles/kiali-deploy/tasks/main.yml
Labels: team/saturn

#2163 [operator] needs new permissions
  operator/deploy/role.yaml
  operator/manifests/kiali-community/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
  operator/manifests/kiali-ossm/1.12.0/kiali.v1.12.0.clusterserviceversion.yaml
  operator/manifests/kiali-upstream/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
Labels: backport/v1.12, bug, team/saturn

#2164 [backport] [operator] needs new permissions
  operator/deploy/role.yaml
  operator/manifests/kiali-community/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
  operator/manifests/kiali-ossm/1.12.0/kiali.v1.12.0.clusterserviceversion.yaml
  operator/manifests/kiali-upstream/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
Labels: bug, team/saturn

#2175 don't spit out errors if route or oauthclient types don't exist
  operator/deploy/deploy-kiali-operator.sh
Labels: team/saturn

#2176 Set url jaeger default to empty
  config/config.go
Labels: backport/v1.12

#2178 Fix error integration in Jaeger
  jaeger/info.go
  jaeger/types.go
Labels: backport/v1.12

#2184 [operator] get k8s version and simplify task getting OS version
  operator/roles/kiali-deploy/tasks/main.yml
Labels: team/saturn

#2185 [backport] [operator] get k8s version and simplify task getting OS version
  operator/roles/kiali-deploy/tasks/main.yml
Labels: team/saturn
