Repository kiali/kiali, pull requests merged in 2020-04, with the labels that each got.

#2587 [operator] move to 0.16 of the operator base image/operator-sdk
  make/Makefile.container.mk
  operator/build/Dockerfile
Labels: team/saturn

#2621 Stop publishing Kiali to DockerHub
  Makefile
  RELEASING.adoc
  deploy/jenkins-ci/Jenkinsfile
  deploy/jenkins-ci/Makefile
  deploy/jenkins-ci/README.md
  deploy/jenkins-ci/jenkins_ref/jobs/kiali-release/config.xml
  make/Makefile.cluster.mk
  make/Makefile.container.mk
Labels: team/saturn

#2638 [v1.15] Relax filtering of bad telemetry (#2571)
  graph/api/api_test.go
  graph/api/testdata/test_complex_graph.expected
  graph/telemetry/istio/util/util.go
Labels: backport/v1.15, team/saturn

#2642 [v1.15] Protect against bad source telemetry (#2636)
  graph/api/api_test.go
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/istio.go
  graph/telemetry/istio/util/util.go
  graph/types.go
Labels: backport/v1.15, team/saturn

#2632 Disable LoginToken.SigningKey validation with Anonymous auth strategy
  config/token.go
  kiali.go
Labels: team/saturn

#2639 [operator] additional changes needed to support disconnected use-case
  operator/manifests/kiali-ossm/1.12.8/kiali.crd.yaml
  operator/manifests/kiali-ossm/1.12.8/kiali.monitoringdashboards.crd.yaml
  operator/manifests/kiali-ossm/1.12.8/kiali.v1.12.8.clusterserviceversion.yaml
  operator/manifests/kiali-ossm/kiali-ossm.package.yaml
Labels: area/install, backport/v1.12, team/saturn

#2640 [operator] [v1.12] additional changes needed to support disconnected use-case
  operator/manifests/kiali-ossm/1.12.8/kiali.crd.yaml
  operator/manifests/kiali-ossm/1.12.8/kiali.monitoringdashboards.crd.yaml
  operator/manifests/kiali-ossm/1.12.8/kiali.v1.12.8.clusterserviceversion.yaml
  operator/manifests/kiali-ossm/kiali-ossm.package.yaml
Labels: area/install, team/saturn

#2644 [operator] ao-logs are going away
  operator/deploy/kiali/kiali_cr.yaml
  operator/deploy/kiali/kiali_cr_dev.yaml
  operator/deploy/kiali/kiali_cr_dev_servicemesh.yaml
  operator/deploy/operator.yaml
  operator/deploy/operator_without_ao.yaml
  operator/manifests/kiali-community/1.16.0/kiali.v1.16.0.clusterserviceversion.yaml
  operator/manifests/kiali-upstream/1.16.0/kiali.v1.16.0.clusterserviceversion.yaml
  operator/molecule/maistra-e2e-test/create.yml
  operator/molecule/maistra-e2e-test/destroy.yml
Labels: area/install, team/saturn

#2675 Allow minikube hack script to set different minikube profile
  hack/k8s-minikube.sh
Labels: area/install, enhancement

#2680 Update AuthorizationPolicy model
  business/istio_config.go
  kubernetes/istio_details_service.go
  kubernetes/types.go
  models/authorization_policy.go
  swagger.json
Labels: frontend changes required

#2687 Allow pre-set query params in Grafana URL
  handlers/grafana.go
  handlers/grafana_test.go
Labels: frontend changes required

#2598 Add Istio Components Status
  business/istio_status.go
  business/istio_status_test.go
  business/layer.go
  config/config.go
  doc.go
  handlers/config.go
  handlers/istio_status.go
  kubernetes/client.go
  kubernetes/kubernetes_service.go
  kubernetes/kubetest/mock.go
  routing/routes.go
  status/versions.go
  swagger.json
Labels: area/management, frontend changes required, operator changes required

#2581 Enable kiali travis build on arm64
  .travis.yml
  README.adoc
  make/Makefile.build.mk
Labels: area/install

#2714 Fixes Iter8 literal in config to please ansible operator
  config/config.go
Labels: operator changes required

#2643 Allow multiple metrics per chart (model update)
  business/dashboards.go
  business/dashboards_test.go
  glide.lock
  glide.yaml
  models/dashboards.go
  prometheus/metrics.go
  prometheus/types.go
  swagger.json
  vendor/github.com/kiali/k-charted/.travis.yml
  vendor/github.com/kiali/k-charted/business/dashboards.go
  vendor/github.com/kiali/k-charted/business/dashboards_test.go
  vendor/github.com/kiali/k-charted/kubernetes/mock/mock.go
  vendor/github.com/kiali/k-charted/kubernetes/v1alpha1/spec.go
  vendor/github.com/kiali/k-charted/model/dashboards.go
  vendor/github.com/kiali/k-charted/model/dashboards_test.go
  vendor/github.com/kiali/k-charted/prometheus/client.go
  vendor/github.com/kiali/k-charted/prometheus/mock/mock.go
  vendor/github.com/kiali/k-charted/web/common/types/Dashboards.ts
  vendor/github.com/kiali/k-charted/web/common/types/Labels.ts
  vendor/github.com/kiali/k-charted/web/common/types/Metrics.ts
  vendor/github.com/kiali/k-charted/web/common/utils/timeSeriesUtils.ts
  vendor/github.com/kiali/k-charted/web/pf4/package.json
  vendor/github.com/kiali/k-charted/web/pf4/src/types/__mocks__/Charts.mock.ts
  vendor/github.com/kiali/k-charted/web/pf4/src/types/__mocks__/Dashboards.mock.ts
  vendor/github.com/kiali/k-charted/web/pf4/src/utils/__tests__/victoryChartsUtils.test.ts
  vendor/github.com/kiali/k-charted/web/pf4/src/utils/victoryChartsUtils.ts
  vendor/github.com/kiali/k-charted/web/pf4/yarn.lock
  vendor/github.com/prometheus/procfs/.circleci/config.yml
  vendor/github.com/prometheus/procfs/fixtures.ttar
  vendor/github.com/prometheus/procfs/fscache.go
  vendor/github.com/prometheus/procfs/fscache_test.go
  vendor/github.com/prometheus/procfs/mountinfo.go
  vendor/github.com/prometheus/procfs/mountstats.go
  vendor/github.com/prometheus/procfs/mountstats_test.go
  vendor/github.com/prometheus/procfs/net_conntrackstat.go
  vendor/github.com/prometheus/procfs/proc_maps.go
  vendor/google.golang.org/appengine/.travis.yml
  vendor/google.golang.org/appengine/aetest/user.go
  vendor/google.golang.org/appengine/internal/api_test.go
Labels: frontend changes required
