Repository kiali/kiali, pull requests merged in 2020-02, with the labels that each got.

#2193 Return ObjectCount and validations only of current ns
  handlers/namespaces.go
  models/istio_validation.go
  models/istio_validation_test.go
  swagger.json
Labels: frontend changes required

#2207 [operator] add the 1.0.10 metadata
  operator/manifests/kiali-ossm/1.0.10/kiali.crd.yaml
  operator/manifests/kiali-ossm/1.0.10/kiali.monitoringdashboards.crd.yaml
  operator/manifests/kiali-ossm/1.0.10/kiali.v1.0.10.clusterserviceversion.yaml
Labels: backport/v1.12, team/saturn

#2208 [backport] [operator] add the 1.0.10 metadata
  operator/manifests/kiali-ossm/1.0.10/kiali.crd.yaml
  operator/manifests/kiali-ossm/1.0.10/kiali.monitoringdashboards.crd.yaml
  operator/manifests/kiali-ossm/1.0.10/kiali.v1.0.10.clusterserviceversion.yaml
Labels: team/saturn

#2192 Reworked some jaeger error handling and enabling workflow
  business/jaeger.go
  business/services.go
  doc.go
  handlers/jaeger.go
  jaeger/client.go
  jaeger/info.go
  jaeger/services.go
  jaeger/spans.go
  jaeger/traces.go
  models/service.go
  models/tracing.go
  operator/deploy/kiali/kiali_cr.yaml
  routing/routes.go
  swagger.json
Labels: frontend changes required

#2214 trivial cleanup of some readmes
  operator/manifests/README.adoc
  operator/roles/kiali-deploy/README.adoc
Labels: team/saturn

#2211 Support GRPC status codes
  graph/api/api_test.go
  graph/api/testdata/test_complex_graph.expected
  graph/protocol.go
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/appender/response_time_test.go
  graph/telemetry/istio/istio.go
  graph/telemetry/istio/util/util.go
  models/health.go
  prometheus/client.go
  prometheus/metrics.go
  prometheus/metrics_definitions.go
  prometheus/prometheustest/client_test.go
Labels: backport/v1.12, team/saturn

#2159 Reorganize config for extensions
  business/threescale.go
  config/config.go
  handlers/config.go
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  operator/roles/kiali-deploy/vars/main.yml
Labels: frontend changes required

#2206 Adding new validation: same subset in different route destination
  business/checkers/virtual_services/route_checker.go
  business/checkers/virtual_services/route_checker_test.go
  models/istio_validation.go
Labels: area/management, docs

#2225 Provide a istio-system services whitelist for jaeger tracing integration
  config/config.go
  handlers/jaeger.go
  models/tracing.go
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  swagger.json
Labels: backport/v1.12, bug

#2229 Add a whitelist for services in istio-system
  config/config.go
  jaeger/client.go
  jaeger/info.go
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/kiali-deploy/defaults/main.yml
  swagger.json
Labels: bug

#2224 AuthorizationPolicies validations: namespace present and valid methods
  business/checkers/authorization/namespace_method_checker.go
  business/checkers/authorization/namespace_method_checker_test.go
  business/checkers/authorization_policies_checker.go
  business/istio_validations.go
  kubernetes/istio_details_service.go
  kubernetes/types.go
  models/istio_validation.go
  models/namespace.go
  tests/data/authorization_policy_data.go
  tests/data/service_entry_data.go
  util/httputil/http_util.go
Labels: docs

#2249 Adding workload checker for AuthPolicy
  business/checkers/authorization/namespace_method_checker_test.go
  business/checkers/authorization/workload_selector_checker.go
  business/checkers/authorization/workload_selector_checker_test.go
  business/checkers/authorization_policies_checker.go
  business/istio_validations.go
  models/istio_validation.go
  tests/data/authorization_policy_data.go
Labels: area/management, docs

#2248 [operator] do not convert pod annotations to snake case
  operator/molecule/affinity-tolerations-resources-test/playbook.yml
  operator/molecule/affinity-tolerations-resources-test/set-affinity-tolerations-resources.yml
  operator/roles/kiali-deploy/tasks/main.yml
Labels: team/saturn

#2257 [operator] clean up some things
  operator/playbooks/kiali-deploy.yml
  operator/roles/v1.0/kiali-deploy/README.adoc
Labels: backport/v1.12, team/saturn

#2258 Fix issue when pulling "request_error_count" metrics
  prometheus/metrics.go
  prometheus/prometheustest/client_test.go
Labels: backport/v1.12, team/saturn

#2268 [hack] support installing istio 1.5
  hack/istio/install-istio-via-istioctl.sh
Labels: team/saturn

#2262 Merge "api doc" and "additional details" features
  business/services.go
  config.yaml
  config/config.go
  deploy/get-console.sh
  doc.go
  handlers/apidocumentation.go
  models/additional_details_test.go
  models/additional_item.go
  models/service.go
  models/workload.go
  operator/deploy/kiali/kiali_cr.yaml
  operator/roles/default/kiali-deploy/defaults/main.yml
  operator/roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
  operator/roles/default/kiali-deploy/templates/kubernetes/service.yaml
  operator/roles/default/kiali-deploy/templates/openshift/deployment.yaml
  operator/roles/default/kiali-deploy/templates/openshift/service.yaml
  operator/roles/default/kiali-deploy/vars/main.yml
  routing/routes.go
  swagger.json
Labels: do not merge, frontend changes required

#2261 Add AuthPolicy validation: host not found for operation rule
  business/checkers/authorization/namespace_method_checker_test.go
  business/checkers/authorization/no_host_checker.go
  business/checkers/authorization/no_host_checker_test.go
  business/checkers/authorization/workload_selector_checker_test.go
  business/checkers/authorization_policies_checker.go
  business/checkers/destinationrules/no_dest_checker.go
  business/istio_validations.go
  kubernetes/host.go
  kubernetes/types.go
  models/istio_validation.go
  models/workload.go
  tests/data/authorization_policy_data.go
Labels: docs
