Repository kiali/kiali, pull requests merged in 2020-05, with the labels that each got.

#2724 [operator] be able to specify what images to test via env vars.
  make/Makefile.molecule.mk
Labels: area/install, operator changes required

#2730 jenkins generation of all-in-one operator deployment yaml
  deploy/jenkins-ci/Dockerfile
  deploy/jenkins-ci/Makefile.operator.jenkins
Labels: area/install

#2739 Adding PeerAuthentication to IstioConfig section
  business/istio_config.go
  business/istio_validations.go
  handlers/istio_config.go
  kubernetes/client.go
  kubernetes/istio_details_service.go
  kubernetes/kubetest/mock.go
  kubernetes/types.go
  models/istio_config.go
  models/peer_authentication.go
  swagger.json
Labels: frontend changes required

#2746 Add WorkloadEntry and RequestAuthentication for Istio 1.6
  business/istio_config.go
  business/istio_validations.go
  handlers/istio_config.go
  kubernetes/client.go
  kubernetes/istio_details_service.go
  kubernetes/kubetest/mock.go
  kubernetes/types.go
  models/authorization_policy.go
  models/istio_config.go
  models/peer_authentication.go
  models/request_authentication.go
  models/workload_entry.go
  swagger.json
Labels: frontend changes required

#2758 Update Istio 1.6 types
  config/config.go
  kubernetes/istio_details_service.go
  models/destination_rule.go
  models/service_entry.go
  models/sidecars.go
  models/virtual_service.go
  swagger.json
Labels: frontend changes required

#2764 Handle istio alpha/beta release versions
  status/versions.go
  status/versions_test.go
Labels: team/saturn

#2743 Remove RBAC limitation from the token authentication
  business/namespaces.go
  handlers/authentication.go
Labels: team/saturn

#2782 server should not allow TLS 1.1 or lower
  server/server.go
  server/server_test.go
Labels: enhancement

#2774 Fix overview services health showing inexisting services
  business/health.go
Labels: do not merge

#2780 require go 1.14.1 minimum
  .travis.yml
  Makefile
Labels: backport/v1.15

#2769 Run Kiali as non-root user
  deploy/docker/Dockerfile-ubi7-minimal
  deploy/docker/Dockerfile-ubi8-minimal
Labels: team/saturn

#2788 Add another RC version-string variety
  status/versions.go
  status/versions_test.go
Labels: backlog, team/saturn

#2802 Add support for minikube profiles in Makefiles
  Makefile
  make/Makefile.cluster.mk
Labels: team/saturn

#2813 Allow Policies and MeshPolicies still be displayed into Istio 1.5
  business/istio_validations.go
Labels: backport/v1.18

#2814 Disabled Namespace validation: Expects PeerAuthn not to be STRICT
  business/checkers/destinationrules/disabled_namespacewide_mtls_checker.go
  business/checkers/destinationrules/disabled_namespacewide_mtls_checker_test.go
Labels: backlog, backport/v1.18, bug

#2794 Virtual Service: support to partially QDN in gateways
  business/checkers/virtual_services/no_gateway_checker.go
  business/checkers/virtual_services/no_gateway_checker_test.go
  business/checkers/virtual_services/subset_presence_checker.go
  business/checkers/virtual_services/subset_presence_checker_test.go
  kubernetes/host.go
  kubernetes/host_test.go
  models/istio_validation.go
Labels: docs, team/jupiter

#2810 Updates IstioConfig with {Peer,Request}Authentication
  business/istio_config.go
Labels: backport/v1.18, frontend changes required, team/jupiter

#2821 Strict and permissive modes can enable/disable TLS status at ns-level
  business/tls.go
  business/tls_test.go
Labels: backport/v1.18

#2822 Endpoint [...]/traces/{traceID} returns single trace
  business/jaeger.go
  handlers/jaeger.go
  jaeger/client.go
  jaeger/traces.go
  jaeger/types.go
Labels: frontend changes required

#2833 makefile - when purging, remove the consolelinks, too.
  make/Makefile.operator.mk
Labels: maintenance

#2836 Change hack script to match Istio 1.6, default auto-mtls to true
  hack/istio/install-istio-via-istioctl.sh
Labels: team/saturn

#2837 expose the image registry if it has not yet been done in the cluster
  make/Makefile.cluster.mk
Labels: maintenance

#2839 [hack] fix up some things for minikube that are broken
  hack/k8s-minikube.sh
  make/Makefile.cluster.mk
  make/Makefile.operator.mk
Labels: maintenance

#2830 Fix dead node corner case
  graph/telemetry/istio/appender/dead_node.go
  graph/telemetry/istio/appender/dead_node_test.go
Labels: team/saturn

#2808 Adding MultiMatch and NoWorkloadFound validations to PeerAuthentication
  business/checkers/authorization/workload_selector_checker.go
  business/checkers/authorization_policies_checker.go
  business/checkers/common/multi_match_selector_checker.go
  business/checkers/common/multi_match_selector_checker_test.go
  business/checkers/common/workload_selector_checker.go
  business/checkers/common/workload_selector_checker_test.go
  business/checkers/peer_authentication_checker.go
  business/checkers/sidecars/multi_match_checker.go
  business/checkers/sidecars/workload_selector_checker.go
  business/checkers/sidecars/workload_selector_checker_test.go
  business/checkers/sidecars_checker.go
  business/istio_validations.go
  models/istio_validation.go
Labels: docs
