Repository kiali/kiali, pull requests merged in 2020-11, with the labels that each got.

#3358 Workload Logs: Avoid business package name shadowing by using criterias
  business/workloads.go
  handlers/workloads.go
Labels: team/saturn

#3385 new hack script for ci when testing with openshift
  hack/ci-openshift-molecule-tests.sh
Labels: maintenance

#3390 see if this fixes travis permission errors
  make/Makefile.build.mk
Labels: maintenance

#3377 Capture more info about the Pod phase/status
  models/pod.go
  swagger.json
Labels: team/saturn

#3392 remove unused/obsolete hack files/scripts
  hack/README.adoc
  hack/cluster-openshift.sh
  hack/istio/install-istio-kiali-via-helm.sh
  hack/istio/install-rh-tutorial.sh
  hack/istio/install-sm10.sh
  hack/istio/playbooks/README.adoc
  hack/istio/playbooks/files/bookinfo-gateway.yaml
  hack/istio/playbooks/files/bookinfo-mongodb.yaml
  hack/istio/playbooks/files/bookinfo-mysql.yaml
  hack/istio/playbooks/files/bookinfo-ratings-v2-mongodb.yaml
  hack/istio/playbooks/files/bookinfo-ratings-v2-mysql.yaml
  hack/istio/playbooks/files/bookinfo.yaml
  hack/istio/playbooks/install_bookinfo.yml
  hack/knative/config-domain.yaml
  hack/knative/service.yaml
  hack/maistra_v1_servicemeshcontrolplane_cr_basic.yaml
  hack/os-minishift.sh
Labels: maintenance

#3393 [hack] get the install istio script to work with 1.8.
  hack/istio/install-istio-via-istioctl.sh
Labels: maintenance

#3401 make it easier to run molecule test by doing a build automatically when required
  make/Makefile.molecule.mk
Labels: maintenance, team/saturn

#3397 Add timeout and client close
  business/openshift_oauth.go
Labels: backport/v1.12, backport/v1.24, frontend changes required, team/saturn

#3396 [hack] install SM 2.0
  hack/istio/install-sm2.sh
Labels: maintenance

#3403 [1.24] Add timeout to http client used with OAuth API
  business/openshift_oauth.go
Labels: team/saturn

#3402 [1.12] Add timeout to http client used with OAuth API
  business/openshift_oauth.go
Labels: team/saturn

#3382 Implement zerolog as logger, support proper json log format and human…
  Makefile
  go.mod
  go.sum
  graph/telemetry/istio/istio.go
  kiali.go
  log/log.go
  log/log_test.go
  make/Makefile.operator.mk
Labels: area/install, enhancement, operator changes required

#3421 use LOG_LEVEL in make run target since -v is invalid now
  make/Makefile.build.mk
Labels: team/saturn

#3412 update makefile and hack scripts to use the new k8s labels
  Makefile
  hack/k8s-minikube.sh
  hack/purge-kiali-from-cluster.sh
  make/Makefile.operator.mk
Labels: backport/v1.24, maintenance, operator changes required, team/saturn

#3416 [v1.24] update makefile and hack scripts
  Makefile
  hack/k8s-minikube.sh
  hack/purge-kiali-from-cluster.sh
  make/Makefile.operator.mk
Labels: team/saturn

#3414 [v1.26] [openid] Fix token validation when RBAC is off
  handlers/authentication.go
Labels: team/saturn

#3415 [openid] Fix token validation when RBAC is off
  handlers/authentication.go
Labels: team/saturn

#3425 [hack] clean up some more things hanging around after uninstalling SM 2.x.
  hack/istio/install-sm2.sh
Labels: maintenance, team/saturn

#3428 [hack] Some changes to dev tools (make and hack script)
  hack/istio/install-istio-via-istioctl.sh
  make/Makefile.cluster.mk
Labels: maintenance, team/saturn

#3383 Add support to setting up the web port in the configuration
  config/config.go
  util/httputil/http_util.go
  util/httputil/http_util_test.go
Labels: team/saturn

#3423 Prom, Jaeger, Grafana component status computed using their service url
  business/istio_status.go
  business/istio_status_test.go
  config/config.go
  kubernetes/kubetest/mock.go
  log/log_test.go
Labels: area/management, frontend changes required, operator changes required

#3427 Incorporate k-charted backend into kiali backend
  business/dashboards.go
  business/dashboards_test.go
  business/grafana.go
  business/metrics.go
  business/metrics_test.go
  business/workloads.go
  doc.go
  go.mod
  go.sum
  handlers/apps.go
  handlers/dashboards.go
  handlers/dashboards_test.go
  handlers/grafana.go
  handlers/metrics.go
  handlers/services.go
  handlers/workloads.go
  kubernetes/monitoringdashboards/client.go
  kubernetes/monitoringdashboards/mock/mock.go
  kubernetes/monitoringdashboards/v1alpha1/spec.go
  models/app.go
  models/dashboards.go
  models/dashboards_test.go
  models/grafana_info.go
  models/metrics.go
  models/pod.go
  models/workload.go
  prometheus/client.go
  prometheus/metrics.go
  prometheus/prometheustest/mock.go
  prometheus/types.go
  swagger.json
Labels: frontend changes required

#3432 need to create NetworkPolicy when deploying dev builds inside a Maistra environment
  make/Makefile.operator.mk
Labels: maintenance, team/saturn

#3413 [multi-cluster] Resolve clusters available to the adjacent istio control plane
  business/layer.go
  business/mesh.go
  business/mesh_test.go
  doc.go
  handlers/mesh.go
  kubernetes/client.go
  kubernetes/kubetest/mock_kubernetes.go
  kubernetes/secret.go
  routing/routes.go
  swagger.json
Labels: frontend changes required, team/saturn
