Repository kiali/kiali, pull requests merged in 2020-07, with the labels that each got.

#2953 [hack] fix some things that are broke when running cron jobs
  hack/ci-minikube-molecule-tests.sh
  hack/k8s-minikube.sh
  make/Makefile.molecule.mk
Labels: maintenance

#2959 pass in -t so we get color text output from ansible which makes the logs easier to read
  make/Makefile.molecule.mk
Labels: maintenance

#2963 Add `state` parameter when requesting autorization to OpenId IdP
  handlers/authentication.go
Labels: team/saturn

#2972 [hack] reset the minikube clock properly (with seconds). CI hack should reset clock before running tests
  hack/ci-minikube-molecule-tests.sh
  hack/k8s-minikube.sh
Labels: maintenance

#2971 Remove namespace/service path params for single trace
  doc.go
  routing/routes.go
  swagger.json
Labels: frontend changes required

#2968 Enabling travis build for ppc64le
  .travis.yml
  Makefile
  make/Makefile.build.mk
Labels: enhancement, maintenance, operator changes required

#2944 Introduce operation aggregate nodes
  doc.go
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/options.go
  graph/protocol.go
  graph/telemetry/istio/appender/aggregate_node.go
  graph/telemetry/istio/appender/aggregate_node_test.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/dead_node.go
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/istio.go
  graph/types.go
  hack/istio/install-travel-agency-demo.sh
  handlers/metrics.go
  handlers/metrics_test.go
  prometheus/metrics.go
  prometheus/types.go
  routing/routes.go
  swagger.json
Labels: frontend changes required, team/saturn

#2986 oauthclient is a cluster scoped resource - no need to pass -n when deleting
  make/Makefile.operator.mk
Labels: maintenance

#2990 be able to specify the pull policy - this might help speed up tests if using dev or released images
  make/Makefile.molecule.mk
Labels: maintenance, operator changes required, team/saturn

#2985 Fix Snyk
  .travis.yml
Labels: team/saturn

#3007 Add all changes when releasing documentation
  deploy/jenkins-ci/Makefile.site.jenkins
Labels: bug, team/saturn

#2976 operator should watch all namespaces by default
  Makefile
  make/Makefile.operator.mk
Labels: area/install, operator changes required, team/saturn

#2938 New Validation - Some AuthorizationPolicy fields needs mTLS to be enabled
  business/checkers/authorization/mtls_enabled_checker.go
  business/checkers/authorization/mtls_enabled_checker_test.go
  business/checkers/authorization_policies_checker.go
  business/checkers/destinationrules/disabled_meshwide_mtls_checker_test.go
  business/checkers/peerauthentications/disabled_meshwide_checker_test.go
  business/checkers/peerauthentications/disabled_namespacewide_checker_test.go
  business/checkers/virtual_services/subset_presence_checker_test.go
  business/istio_validations.go
  business/tls.go
  business/tls_test.go
  kubernetes/kubetest/mock_istio.go
  models/istio_validation.go
  tests/data/fiture_loader.go
  tests/data/validations/authorization/authz_policy_requires_mtls.yaml
  tests/data/validations/authorization/mtls_enabled_checker_1.yaml
  tests/data/validations/authorization/mtls_enabled_checker_10.yaml
  tests/data/validations/authorization/mtls_enabled_checker_101.yaml
  tests/data/validations/authorization/mtls_enabled_checker_11.yaml
  tests/data/validations/authorization/mtls_enabled_checker_12.yaml
  tests/data/validations/authorization/mtls_enabled_checker_13.yaml
  tests/data/validations/authorization/mtls_enabled_checker_14.yaml
  tests/data/validations/authorization/mtls_enabled_checker_15.yaml
  tests/data/validations/authorization/mtls_enabled_checker_16.yaml
  tests/data/validations/authorization/mtls_enabled_checker_17.yaml
  tests/data/validations/authorization/mtls_enabled_checker_2.yaml
  tests/data/validations/authorization/mtls_enabled_checker_3.yaml
  tests/data/validations/authorization/mtls_enabled_checker_4.yaml
  tests/data/validations/authorization/mtls_enabled_checker_5.yaml
  tests/data/validations/authorization/mtls_enabled_checker_6.yaml
  tests/data/validations/authorization/mtls_enabled_checker_7.yaml
  tests/data/validations/authorization/mtls_enabled_checker_71.yaml
  tests/data/validations/authorization/mtls_enabled_checker_8.yaml
  tests/data/validations/authorization/mtls_enabled_checker_9.yaml
  tests/data/validations/test_asserter.go
  util/mtls/status.go
Labels: team/jupiter

#2936 Backend refactoring triggered by 3scale changes
  business/health.go
  business/health_test.go
  business/istio_config.go
  business/istio_config_test.go
  business/istio_validations.go
  business/layer.go
  business/services.go
  business/threescale.go
  business/threescale_test.go
  business/tls.go
  business/workloads.go
  business/workloads_test.go
  config/config.go
  doc.go
  handlers/config.go
  handlers/health.go
  handlers/istio_config.go
  handlers/threescale.go
  handlers/workloads.go
  kubernetes/cache/istio.go
  kubernetes/client.go
  kubernetes/filters.go
  kubernetes/kubernetes.go
  kubernetes/kubetest/mock_kubernetes.go
  models/threescale.go
  routing/routes.go
  swagger.json
Labels: frontend changes required, operator changes required

#3012 CVE-2020-14040
  go.mod
  go.sum
Labels: backport/v1.12, maintenance, team/saturn

#3029 Use config instead of hardcoded default for token expiration
  handlers/authentication.go
Labels: enhancement

#3038 [v1.18 backport] Better handle egress destination telemetry (#3004)
  graph/api/api_test.go
  graph/api/testdata/test_complex_graph.expected
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/istio.go
  graph/telemetry/istio/util/util.go
Labels: backport/v1.18, frontend changes required, team/saturn

#3039 Fix version matching for alpha release
  status/versions.go
  status/versions_test.go
Labels: team/saturn

#3043 Ensure removal of leaf service nodes with no incoming traffic
  graph/telemetry/istio/appender/dead_node.go
  graph/telemetry/istio/appender/dead_node_test.go
Labels: team/saturn

#3034 PoC: changes to go with the introduction of helm
  README.adoc
  deploy/jenkins-ci/Makefile.operator.jenkins
  hack/run-molecule-tests.sh
  make/Makefile.cluster.mk
  make/Makefile.operator.mk
Labels: area/install, operator changes required, team/saturn

#3058 Update install-istio-via-istiocl hack script for istio 1.7
  hack/istio/install-istio-via-istioctl.sh
Labels: team/saturn

#3059 [1.7] can not expose prom because it is no longer installed by istioctl
  hack/istio/install-istio-via-istioctl.sh
Labels: team/saturn

#3046 Bump k-charted 0.6.1-rc2
  business/dashboards.go
  go.mod
  go.sum
  handlers/metrics.go
  swagger.json
Labels: frontend changes required
