Repository kiali/kiali, pull requests merged in 2021-05, with the labels that each got.

#3961 Create service entry nodes in homecluster
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/service_entry_test.go
Labels: team/saturn

#3967 Use RW for cache lock
  kubernetes/cache/cache.go
Labels: team/jupiter

#3979 [hack] some tweaks to k8s-minikube.sh
  hack/ci-minikube-molecule-tests.sh
  hack/k8s-minikube.sh
Labels: maintenance, team/saturn

#3970 Reduce number of API calls to discover remote Kialis
  business/layer.go
  business/mesh.go
  business/mesh_test.go
  jaeger/http_client.go
  kubernetes/filters.go
  kubernetes/kubernetes.go
  kubernetes/kubetest/mock_kubernetes.go
Labels: team/saturn

#3980 Add the ServiceEntry definition namespace to the SEInfo returned to client
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/service_entry_test.go
  graph/types.go
  kiali_api.md
  swagger.json
Labels: team/saturn

#4006 Reduce number of API calls to discover remote Kialis (#3970)
  business/layer.go
  business/mesh.go
  business/mesh_test.go
  jaeger/http_client.go
  kubernetes/filters.go
  kubernetes/kubernetes.go
  kubernetes/kubetest/mock_kubernetes.go
Labels: team/saturn

#4007 Set typemeta for istio cache objects
  kubernetes/cache/istio.go
  kubernetes/cache/istio_test.go
Labels: team/saturn

#3981 Make sure Istio gateways are captured as proxies
  config/config.go
  kiali_api.md
  models/pod.go
  swagger.json
Labels: frontend changes required, team/saturn

#4022 Allow read-only file system in Kiali's pod
  kiali.go
  routing/router.go
  routing/router_test.go
  server/server_test.go
Labels: team/saturn

#3986 Deprecate publishing to NPM (back-end)
  Makefile
  README.adoc
  RELEASING.adoc
  deploy/get-console.sh
  deploy/jenkins-ci/Jenkinsfile
  deploy/jenkins-ci/README.md
  deploy/jenkins-ci/bin/determine-release-type.sh
  deploy/jenkins-ci/jenkins_ref/jobs/kiali-release/config.xml
  hack/run-kiali.sh
  make/Makefile.container.mk
Labels: team/saturn

#4033 [hack] fix purge script so it purges correctly on minikube
  hack/purge-kiali-from-cluster.sh
Labels: maintenance

#4021 [hack] be able to set web_fqdn and web_schema for the 2 kiali instances
  hack/istio/multicluster/deploy-kiali.sh
  hack/istio/multicluster/env.sh
Labels: maintenance, team/saturn

#4044 kvm2 doesn't work - need virtualbox
  hack/istio/multicluster/env.sh
Labels: maintenance, team/saturn

#4020 Introduce Graph Find/Hide presets
  config/config.go
Labels: frontend changes required, team/saturn

#4026 Assume a connectivity issue on Prometheus API failures
  business/health.go
  graph/telemetry/istio/appender/util.go
  graph/telemetry/istio/istio.go
  graph/util.go
  handlers/dashboards.go
  handlers/errors.go
  handlers/mesh.go
  handlers/metrics.go
  handlers/namespaces.go
  prometheus/client.go
  prometheus/metrics.go
Labels: team/saturn
