Repository kiali/kiali, pull requests merged in 2021-08, with the labels that each got.

#4232 [v1.36] Fix graph with spurious cluster boxes and a crash
  business/mesh.go
  graph/telemetry/istio/appender/aggregate_node_test.go
  graph/telemetry/istio/appender/dead_node.go
  graph/telemetry/istio/appender/dead_node_test.go
  graph/telemetry/istio/appender/idle_node.go
  graph/telemetry/istio/appender/idle_node_test.go
  graph/telemetry/istio/appender/istio_details_test.go
  graph/telemetry/istio/appender/response_time_test.go
  graph/telemetry/istio/appender/security_policy_test.go
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/sidecars_check_test.go
  graph/telemetry/istio/appender/throughput_test.go
Labels: team/saturn

#4248 add metric to track processing time for each individual checker
  business/istio_validations.go
  prometheus/internalmetrics/internal_metrics.go
Labels: backport/v1.36, team/saturn

#4250 [v1.36] add metric to track processing time for each individual checker (#4248)
  business/istio_validations.go
  prometheus/internalmetrics/internal_metrics.go
Labels: team/saturn

#4249 Using gRPC or HTTP methods to check health of the jaeger component
  business/istio_status.go
  business/istio_status_test.go
  business/jaeger.go
  config/config.go
  jaeger/client.go
  jaeger/http_client.go
  jaeger/jaegertest/mock.go
Labels: area/istio operations, operator changes required

#4247 [v1.38] Fix router issue and cluster discovery
  business/mesh.go
  graph/telemetry/istio/appender/aggregate_node_test.go
  graph/telemetry/istio/appender/dead_node.go
  graph/telemetry/istio/appender/dead_node_test.go
  graph/telemetry/istio/appender/idle_node.go
  graph/telemetry/istio/appender/idle_node_test.go
  graph/telemetry/istio/appender/istio_details_test.go
  graph/telemetry/istio/appender/response_time_test.go
  graph/telemetry/istio/appender/security_policy_test.go
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/sidecars_check_test.go
  graph/telemetry/istio/appender/throughput_test.go
  routing/router.go
Labels: team/saturn

#4257 [v1.38] Using gRPC or HTTP methods to check health of the jaeger component
  business/istio_status.go
  business/istio_status_test.go
  business/jaeger.go
  config/config.go
  jaeger/client.go
  jaeger/http_client.go
  jaeger/jaegertest/mock.go
Labels: team/saturn

#4254 [hack] support istio 1.11 and the openshift profile
  hack/istio/install-istio-via-istioctl.sh
Labels: maintenance, team/saturn

#4262 Adding default grafana in_cluster_url
  business/grafana_test.go
  config/config.go
Labels: area/installation

#4274 Hack script for running podman pods as Workload Entries
  hack/istio/install-bookinfo-workload-entry.sh
  hack/istio/workloadentry/bookinfo-service-entry.yaml
  hack/istio/workloadentry/istiod-ingress.yaml
  hack/istio/workloadentry/workloadgroup_template.yaml
Labels: team/saturn

#4269 Reduce logging related to clustering discovery
  business/mesh.go
Labels: team/saturn

#4285 [hack] some enhancements and cleanup
  hack/aws-openshift-istio.sh
  hack/configure-operator.sh
  hack/k8s-minikube.sh
Labels: maintenance, team/saturn

#4286 [hack] a couple of new, general purpose scripts
  hack/istio/create-mesh-namespace.sh
  hack/istio/enable_maistra_deployment_injection.sh
Labels: team/saturn

#4283 Added support of exported DestinationRules for SubsetPresenceChecker of VirtualSevices. Added tests.
  business/checkers/virtual_service_checker.go
  business/checkers/virtualservices/subset_presence_checker.go
  business/checkers/virtualservices/subset_presence_checker_test.go
  tests/data/validations/virtualservices/subset-presence-export-subset.yaml
  tests/data/validations/virtualservices/subset-presence-no-matching-export-subset.yaml
Labels: area/istio operations

#4291 [hack] ci tests will now report the number of failed tests
  hack/ci-kind-molecule-tests.sh
  hack/ci-minikube-molecule-tests.sh
  hack/ci-openshift-molecule-tests.sh
Labels: maintenance, team/saturn

#4256 Make DRs subset validation error to info when no VS created for this subsets. Tests added.
  business/checkers/destinationrules/no_dest_checker.go
  business/checkers/destinationrules/no_dest_checker_test.go
  business/checkers/no_service_checker.go
  tests/data/validations/virtualservices/subset-presence-matching-not-referenced.yaml
  tests/data/validations/virtualservices/subset-presence-not-referenced.yaml
  tests/data/validations/virtualservices/subset-presence-referenced.yaml
  tests/data/validations/virtualservices/subset-presence-wrongly-referenced.yaml
Labels: docs, area/istio operations, operator changes required

#4297 [hack] update CRC script so it can run the latest
  hack/crc-openshift.sh
Labels: maintenance

#4273 Add viewOnlyMode property into config object
  business/istio_config.go
  config/config.go
  handlers/config.go
Labels: enhancement
