Repository kiali/kiali, pull requests merged in 2021-11, with the labels that each got.

#4465 New function to check if namespace is the root namespace
  config/config.go
Labels: requires operator PR

#4463 Hostnames for egress gateways nodes
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/telemetry/istio/appender/istio_details.go
  kiali_api.md
  swagger.json
Labels: requires UI PR

#4499 While validating port name in Services, consider also appProtocol parameter's value.
  business/checkers/services/port_mapping_checker.go
  business/checkers/services/port_mapping_checker_test.go
  kubernetes/istio.go
  kubernetes/istio_test.go
  models/istio_validation.go
  models/port.go
  swagger.json
Labels: requires UI PR, docs
