Repository kiali/kiali, pull requests merged in 2021-07, with the labels that each got.

#4136 Show Istio configuration linked with Services and Workloads (and Applications) on list pages
  business/apps.go
  business/apps_test.go
  business/istio_validations.go
  business/services.go
  business/services_test.go
  business/workloads.go
  business/workloads_test.go
  graph/telemetry/istio/appender/appender.go
  handlers/apps.go
  handlers/apps_test.go
  handlers/iter8.go
  handlers/services.go
  handlers/workloads.go
  handlers/workloads_test.go
  kiali_api.md
  models/app.go
  models/service.go
  models/workload.go
  swagger.json
Labels: frontend changes required

#4146 Fix regression in personalized CustomDashboards at namespace level
  business/apps.go
  business/apps_test.go
  business/dashboards.go
  business/dashboards_test.go
  business/workloads.go
  business/workloads_test.go
  config/dashboards/dashboards_config.go
  handlers/dashboards.go
  kiali_api.md
  models/dashboards.go
  models/namespace.go
  models/workload.go
  swagger.json
Labels: backport/v1.36, frontend changes required

#4171 Support multiple rows in metrics dashboards
  business/dashboards.go
  config/dashboards/dashboards_config.go
  kiali_api.md
  models/dashboards.go
  swagger.json
Labels: backport/v1.36

#4108 Replace PodProxy calls by plain HTTP GET calls
  business/istio_status.go
  business/istio_status_test.go
  kubernetes/istio.go
  kubernetes/kubernetes.go
  kubernetes/kubetest/mock_kubernetes.go
  util/httputil/port_forwarder.go
  util/httputil/port_pool.go
  util/httputil/port_pool_test.go
Labels: helm charts changes required, operator changes required

#4189 Run molecule tests with KinD
  hack/ci-kind-molecule-tests.sh
  hack/run-molecule-tests.sh
  make/Makefile.molecule.mk
Labels: team/saturn

#4183 Add kiali scenarios to graph node from VS spec
  graph/telemetry/istio/appender/istio_details.go
  graph/telemetry/istio/appender/istio_details_test.go
  graph/types.go
  models/virtual_service.go
  models/virtual_service_test.go
Labels: team/saturn

#4200 be able to upload logs to different branches for ci-minikube and ci-openshift scripts
  hack/ci-minikube-molecule-tests.sh
  hack/ci-openshift-molecule-tests.sh
Labels: maintenance, team/saturn

#4188 Allow service entries with multiple edges
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/service_entry_test.go
Labels: team/saturn

#4204 VirtualService's exportTo field's value is restricted to “.” or “*”.
  business/checkers/common/export_to_namespace_checker.go
  business/checkers/common/export_to_namespace_checker_test.go
  tests/data/validations/exportto/dr_exportto_all_valid.yaml
  tests/data/validations/exportto/se_exportto_all_valid.yaml
  tests/data/validations/exportto/vs_exportto_all_valid.yaml
Labels: team/jupiter

#4205 Be able to ignore one or more validation checks
  business/checkers/authorization/namespace_method_checker_test.go
  business/checkers/authorization/no_host_checker_test.go
  business/checkers/common/export_to_namespace_checker.go
  business/checkers/common/export_to_namespace_checker_test.go
  business/checkers/common/multi_match_selector_checker_test.go
  business/checkers/common/workload_selector_checker_test.go
  business/checkers/destinationrules/disabled_namespacewide_mtls_checker_test.go
  business/checkers/destinationrules/meshwide_mtls_checker_test.go
  business/checkers/destinationrules/multi_match_checker_test.go
  business/checkers/destinationrules/namespacewide_mtls_checker_test.go
  business/checkers/destinationrules/no_dest_checker_test.go
  business/checkers/destinationrules/traffic_policy_checker_test.go
  business/checkers/gateways/port_checker_test.go
  business/checkers/gateways/selector_checker_test.go
  business/checkers/no_service_checker_test.go
  business/checkers/peerauthentications/mesh_mtls_checker_test.go
  business/checkers/peerauthentications/namespace_mtls_checker_test.go
  business/checkers/serviceentries/port_checker_test.go
  business/checkers/services/port_mapping_checker_test.go
  business/checkers/sidecars/egress_listener_checker_test.go
  business/checkers/sidecars/global_checker_test.go
  business/checkers/virtual_services/no_gateway_checker_test.go
  business/checkers/virtual_services/no_host_checker_test.go
  business/checkers/virtual_services/route_checker_test.go
  business/checkers/virtual_services/single_host_checker_test.go
  business/istio_validations.go
  config/config.go
  kiali.go
  kiali_api.md
  models/istio_validation.go
  models/istio_validation_test.go
  swagger.json
  tests/data/validations/test_asserter.go
  tests/testutils/check_confirmer.go
  tests/testutils/check_confirmer_test.go
Labels: frontend changes required, operator changes required, team/saturn

#4233 [v1.36] Run molecule tests with KinD (#4189)
  hack/ci-kind-molecule-tests.sh
  hack/run-molecule-tests.sh
  make/Makefile.molecule.mk
Labels: maintenance, team/saturn

#4236 Fix missing Grafana Workload and Service links
  config/dashboards/dashboards_config.go
  swagger.json
Labels: bug

#4237 [v1.36] Fix missing Grafana Workload and Service links
  config/dashboards/dashboards_config.go
  swagger.json
Labels: backport/v1.36

#4234 [hack] fix the comments in run-kiali.sh - had some wrong information
  hack/run-kiali.sh
Labels: team/saturn

#4138 Add new gateway_hostnames graph appender
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/istio_details.go
  graph/telemetry/istio/appender/istio_details_test.go
  kiali_api.md
  models/gateway.go
  models/virtual_service.go
  swagger.json
  tests/data/virtual_service_data.go
Labels: frontend changes required, team/saturn

#4231 Fix graph with spurious cluster boxes and a crash
  business/mesh.go
  graph/telemetry/istio/appender/aggregate_node_test.go
  graph/telemetry/istio/appender/dead_node.go
  graph/telemetry/istio/appender/dead_node_test.go
  graph/telemetry/istio/appender/idle_node.go
  graph/telemetry/istio/appender/idle_node_test.go
  graph/telemetry/istio/appender/istio_details_test.go
  graph/telemetry/istio/appender/response_time_test.go
  graph/telemetry/istio/appender/security_policy_test.go
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/sidecars_check_test.go
  graph/telemetry/istio/appender/throughput_test.go
Labels: team/saturn

#4235 Fix root URL not loading with URL parameters
  routing/router.go
Labels: team/saturn
