Repository kiali/kiali, pull requests merged in 2021-12, with the labels that each got.

#4520 While validating VS subsets repeatings, consider hosts and subset combinations
  business/checkers/virtual_service_checker.go
  business/checkers/virtualservices/route_checker.go
  business/checkers/virtualservices/route_checker_test.go
  models/istio_validation.go
Labels: docs

#4522 Add configuration for IstioD pod monitoring port
  config/config.go
  kubernetes/istio.go
Labels: requires operator PR

#4548 Remove unnecessary graph boxes
  graph/config/cytoscape/cytoscape.go
Labels: requires UI PR
