Repository kiali/kiali, pull requests merged in 2021-03, with the labels that each got.

#3735 Discovery of Kiali instances in remote clusters
  business/mesh.go
  business/mesh_test.go
  graph/telemetry/istio/appender/idle_node.go
  handlers/config.go
  handlers/mesh.go
  kubernetes/client.go
  kubernetes/kubernetes.go
  kubernetes/kubetest/mock_kubernetes.go
  swagger.json
Labels: team/saturn

#3750 Add missing token validation for implicit flow
  handlers/authentication.go
Labels: team/saturn

#3680 Update graph query approach to use complementary source and dest reporting
  graph/api/api_test.go
  graph/api/testdata/test_app_node_graph.expected
  graph/api/testdata/test_complex_graph.expected
  graph/api/testdata/test_mc_source_graph.expected
  graph/api/testdata/test_service_graph.expected
  graph/api/testdata/test_service_node_graph.expected
  graph/api/testdata/test_versioned_app_graph.expected
  graph/api/testdata/test_versioned_app_node_graph.expected
  graph/api/testdata/test_workload_graph.expected
  graph/api/testdata/test_workload_node_graph.expected
  graph/appender.go
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/protocol.go
  graph/telemetry/istio/appender/aggregate_node.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/dead_node.go
  graph/telemetry/istio/appender/dead_node_test.go
  graph/telemetry/istio/appender/health_config.go
  graph/telemetry/istio/appender/idle_node.go
  graph/telemetry/istio/appender/istio_details.go
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/appender/response_time_test.go
  graph/telemetry/istio/appender/sidecars_check.go
  graph/telemetry/istio/appender/sidecars_check_test.go
  graph/telemetry/istio/istio.go
  graph/telemetry/istio/util/util.go
  graph/types.go
  graph/util.go
  swagger.json
Labels: team/saturn

#3367 Changes necessary to move to Ansible Operator SDK 1.x
  hack/run-prometheus.sh
  make/Makefile.cluster.mk
  make/Makefile.container.mk
Labels: team/saturn

#3774 no need for these extra permissions anymore due to the use of CNI on OpenShift
  hack/istio/install-bookinfo-demo.sh
  hack/istio/install-error-rates-demo.sh
  hack/istio/install-istio-via-istioctl.sh
  hack/istio/install-travel-agency-demo-1.6.sh
  hack/istio/install-travel-agency-demo.sh
Labels: maintenance, team/saturn

#3779 [hack] this is still needed - this perm is required in the control plane ns
  hack/istio/install-istio-via-istioctl.sh
Labels: team/saturn

#3780 Bump golang version to 1.16.2
  .github/workflows/kiali-ci.yml
  Makefile
  README.adoc
  deploy/jenkins-ci/Dockerfile
Labels: team/saturn

#3783 Simplify pipeline parameters and update README
  deploy/jenkins-ci/Dockerfile
  deploy/jenkins-ci/Jenkinsfile
  deploy/jenkins-ci/README.md
  deploy/jenkins-ci/jenkins_ref/init.groovy.d/setup-jenkins.groovy
  deploy/jenkins-ci/jenkins_ref/jobs/kiali-helm-release/config.xml
  deploy/jenkins-ci/jenkins_ref/jobs/kiali-operator-release/config.xml
  deploy/jenkins-ci/jenkins_ref/jobs/kiali-release/config.xml
  deploy/jenkins-ci/jenkins_ref/jobs/kiali-website-release/config.xml
Labels: team/saturn

#3768 Extract external-url annotation when discovering Kialis
  business/mesh.go
Labels: team/saturn

#3796 Add the IstiodDeploymentName to config and use it in the mesh business
  business/mesh.go
  config/config.go
Labels: operator changes required

#3784 script that you can use to run kiali on the local machine
  README.adoc
  hack/run-kiali-config-template.yaml
  hack/run-kiali.sh
Labels: maintenance

#3802 [hack] needs update to install sm2 on os 4.7
  hack/istio/install-sm2.sh
Labels: maintenance, team/saturn

#3801 Cache home cluster to avoid resolving it multiple times
  business/mesh.go
  business/mesh_test.go
Labels: team/saturn

#3803 [hack] check for a route called "jaeger" - ossm creates this
  hack/run-kiali.sh
Labels: maintenance, team/saturn

#3806 [hack] clean up the istio-cni pods from kube-system, too
  hack/istio/install-sm2.sh
Labels: maintenance, team/saturn

#3797 Fix redirection from root-path without slash to root-path with slash
  business/mesh_test.go
  routing/router.go
  util/httputil/http_util.go
Labels: team/saturn

#3804 molecule tests to be able to skip operator install
  hack/ci-openshift-molecule-tests.sh
  hack/run-molecule-tests.sh
  make/Makefile.molecule.mk
Labels: operator changes required, team/saturn

#3832 Pass dorp to run-molecule-tests.sh
  hack/ci-openshift-molecule-tests.sh
  hack/run-molecule-tests.sh
Labels: maintenance, team/saturn
