Repository kiali/kiali, pull requests merged in 2021-06, with the labels that each got.

#4043 Add additional kiali scenarios to node metadata
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/telemetry/istio/appender/istio_details.go
  graph/telemetry/istio/appender/istio_details_test.go
  graph/types.go
  kiali_api.md
  swagger.json
Labels: frontend changes required, team/saturn

#4065 Support 'queryTime' query parameter for Health requests.
  handlers/health.go
Labels: frontend changes required, team/saturn

#4085 [hack] pass minikube profile name to bookinfo hack script
  hack/k8s-minikube.sh
Labels: maintenance

#4086 [hack] we want mtls mode explicitly set whether using "oc" or "kubectl"
  hack/istio/install-istio-via-istioctl.sh
Labels: maintenance, team/saturn

#4059 consolidate dashboards
  business/dashboards.go
  business/dashboards_test.go
  business/grafana.go
  config/config.go
  config/dashboards/dashboards.go
  config/dashboards/dashboards_config.go
  config/dashboards/dashboards_config_test.go
  kiali_api.md
  kubernetes/monitoringdashboards/client.go
  kubernetes/monitoringdashboards/mock/mock.go
  kubernetes/monitoringdashboards/v1alpha1/spec.go
  models/dashboards.go
  swagger.json
Labels: area/installation+configuration, helm charts changes required, operator changes required, team/saturn

#4088 clean up some bookinfo hack yaml
  hack/istio/bookinfo-details-abort.yaml
  hack/istio/bookinfo-mlts-details.yaml
  hack/istio/bookinfo-ratings-delay.yaml
  hack/istio/bookinfo-reviews-all-cb.yaml
  hack/istio/bookinfo-reviews-faults.yaml
  hack/istio/bookinfo-reviews-mirroring.yaml
  hack/istio/bookinfo-reviews-v1-cb.yaml
  hack/istio/bookinfo-traffic/bookinfo-details-abort-multicode.yaml
  hack/istio/bookinfo-traffic/bookinfo-ratings-delay.yaml
  hack/istio/bookinfo-traffic/bookinfo-reviews-mirroring.yaml
  hack/istio/bookinfo-traffic/bookinfo-service-entry.yaml
  hack/istio/install-travel-agency-demo.sh
  hack/istio/istio-mtls-meshwide.yaml
Labels: maintenance, team/saturn

#4075 Added IsReady status on ContainerInfo taking from ContainerStatus
  models/pod.go
  swagger.json
Labels: frontend changes required

#4103 [hack] Support non-openshift clusters and add --print-images option
  hack/docker-io-auth.sh
Labels: maintenance

#4105 ci script now sends results to libera chat room.
  hack/ci-openshift-molecule-tests.sh
Labels: maintenance, team/saturn

#4093 Display throughput on the graph edges
  doc.go
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/appender/response_time_test.go
  graph/telemetry/istio/appender/security_policy.go
  graph/telemetry/istio/appender/throughput.go
  graph/telemetry/istio/appender/throughput_test.go
  graph/telemetry/istio/istio.go
  kiali_api.md
  swagger.json
Labels: frontend changes required, team/saturn

#4107 Reusing Filter method for Service Registry loopup
  business/checkers/authorization/no_host_checker.go
  business/checkers/destinationrules/no_dest_checker.go
  business/checkers/virtual_services/no_host_checker.go
  kubernetes/host.go
Labels: maintenance

#4110 remove istio_component_namespaces config
  business/iter8.go
  config/config.go
  graph/api/api_test.go
  handlers/config.go
  kubernetes/types.go
Labels: area/installation+configuration, frontend changes required, operator changes required, team/saturn

#4112 Support for custom CA certificate for OpenID auth
  business/openid_auth.go
Labels: docs, helm charts changes required, operator changes required, team/saturn

#4053 [hack] be able to enable OLM in minikube
  hack/ci-minikube-molecule-tests.sh
  hack/k8s-minikube.sh
Labels: maintenance, team/saturn

#4126 provide some make targets to allow you to set operator feature settings easily
  make/Makefile.operator.mk
Labels: maintenance, team/saturn

#4127 the makefile target was broken when trying to set the config when installed via OLM
  make/Makefile.operator.mk
Labels: maintenance, team/saturn

#4128 [v1.36] backport some fixes to the makefile to support testing with OLM
  make/Makefile.operator.mk
Labels: maintenance, team/saturn
