Repository kiali/kiali, pull requests merged in 2021-02, with the labels that each got.

#3626 Adding host information to clusters and routes
  business/layer.go
  business/proxy_status.go
  kubernetes/host.go
  models/config_dump.go
Labels: frontend changes required

#3651 Metrics: fix peer namespace segregation
  business/dashboards_test.go
  models/dashboards.go
  models/dashboards_test.go
Labels: frontend changes required, team/jupiter

#3655 fix logout
  business/openshift_oauth.go
Labels: backport/v1.12, backport/v1.24, operator changes required, team/saturn

#3661 [v1.24] fix logout
  business/openshift_oauth.go
Labels: team/saturn

#3662 [v1.12] fix logout
  business/openshift_oauth.go
Labels: team/saturn

#3654 Proxy status: fetching status only from running istiod pods + always returning status if present
  kubernetes/istio.go
Labels: backport/v1.29

#3663 use UBI8 for all builds
  Makefile
  deploy/docker/Dockerfile-multi-arch
  deploy/docker/Dockerfile-ubi7-minimal
Labels: team/saturn

#3669 [1.29] Cherry-picking kiali-3664 kiali-3654 kiali-3653
  business/dashboards_test.go
  business/health.go
  business/health_test.go
  kubernetes/istio.go
  models/health.go
  prometheus/client.go
  prometheus/metrics.go
  prometheus/prometheustest/mock.go
Labels: team/jupiter

#3668 Performance / custom dashboards: new configs
  business/dashboards.go
  config/config.go
Labels: backport/v1.29

#3666 whenever the server detects the client is unauthorized, delete the token cookies
  handlers/authentication.go
Labels: team/saturn

#3672 [v1.24] whenever the server detects the client is unauthorized, delete the token cookies
  handlers/authentication.go
Labels: team/saturn

#3671 [v1.29] whenever the server detects the client is unauthorized, delete the token cookies
  handlers/authentication.go
Labels: team/saturn

#3674 update operation node support to istio 1.9
  hack/istio/install-travel-agency-demo.sh
Labels: team/saturn

#3688 Server config support UI Defaults
  config/config.go
Labels: frontend changes required, operator changes required, team/saturn

#3362 Allow custom health configuration to be deployed as annotations
  business/health.go
  business/health_test.go
  business/services.go
  config/config.go
  doc.go
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/health_config.go
  graph/telemetry/istio/appender/health_config_test.go
  handlers/health_test.go
  handlers/services.go
  kubernetes/client.go
  kubernetes/kubernetes.go
  kubernetes/kubetest/mock_kubernetes.go
  models/health.go
  models/health_config.go
  models/service.go
  models/workload.go
  routing/routes.go
  swagger.json
Labels: team/jupiter

#3700 Homogenate GH-Actions CI with old Travis CI
  .github/workflows/kiali-ci.yml
  .github/workflows/snyk.yml
  .travis.yml
  handlers/authentication.go
  kubernetes/client_factory.go
  make/Makefile.build.mk
  swagger.json
  util/httputil/http_util.go
Labels: team/saturn

#3710 Allow releasing helm charts on patch releases
  deploy/jenkins-ci/Jenkinsfile
Labels: team/saturn

#3705 Fix Snyk GitHub action
  .github/workflows/snyk.yml
Labels: team/saturn
