Repository kiali/kiali, pull requests merged in 2021-09, with the labels that each got.

#4284 Add workload entry appender to label WE nodes
  graph/config/cytoscape/cytoscape.go
  graph/config/cytoscape/cytoscape_test.go
  graph/meta.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/workload_entry.go
  graph/telemetry/istio/appender/workload_entry_test.go
  kiali_api.md
  swagger.json
Labels: requires UI PR

#4227 Add a new section to get internal certificates information
  business/istio_certs.go
  business/istio_certs_test.go
  business/layer.go
  config/config.go
  doc.go
  handlers/istio_certs.go
  kiali_api.md
  kubernetes/kubernetes.go
  kubernetes/kubetest/mock_kubernetes.go
  kubernetes/secret.go
  models/cert_info.go
  routing/routes.go
  swagger.json
Labels: requires UI PR, requires operator PR, requires helm chart PR

#4309 when checking for sidecar injection, check the label as well as the annotation
  kiali_api.md
  models/workload.go
  status/status.go
  status/versions.go
  swagger.json
Labels: requires UI PR, requires operator PR

#4350 send custom headers in prometheus requests
  business/grafana.go
  business/istio_status.go
  config/config.go
  jaeger/client.go
  kubernetes/kubernetes.go
  prometheus/client.go
  status/versions.go
  util/httputil/http_util.go
Labels: requires operator PR

#4375 Pass empty custom headers
  util/httputil/http_util.go
Labels: bug
