Repository kiali/kiali, pull requests merged in 2021-04, with the labels that each got.

#3846 support kind
  Makefile
  README.adoc
  hack/istio/install-bookinfo-demo.sh
  make/Makefile.cluster.mk
  make/Makefile.molecule.mk
Labels: maintenance, team/saturn

#3848 [hack] be able to easily access kiali deployed in k8s via port-forward and get image names correct with podman
  hack/kiali-port-forward.sh
  make/Makefile.cluster.mk
Labels: maintenance, team/saturn

#3713 [hack] multi-cluster setup scripts
  hack/istio/install-istio-via-istioctl.sh
  hack/istio/multicluster/README.adoc
  hack/istio/multicluster/config-mesh-networks.sh
  hack/istio/multicluster/deploy-kiali.sh
  hack/istio/multicluster/env.sh
  hack/istio/multicluster/install-everything.sh
  hack/istio/multicluster/setup-ca.sh
  hack/istio/multicluster/split-bookinfo.sh
  hack/istio/multicluster/start-kind.sh
  hack/istio/multicluster/start-minikube.sh
  hack/istio/multicluster/uninstall-everything.sh
  hack/k8s-minikube.sh
Labels: maintenance, team/saturn

#3850 the way our make targets work, we need to allow ad-hoc kiali namespaces
  Makefile
  make/Makefile.operator.mk
Labels: area/installation+configuration, enhancement, operator changes required, team/saturn

#3851 be able to specify CR spec.version to test
  hack/ci-openshift-molecule-tests.sh
  hack/run-molecule-tests.sh
  make/Makefile.molecule.mk
Labels: maintenance, operator changes required, team/saturn

#3855 [molecule] set image version when testing non-default spec.version
  make/Makefile.molecule.mk
Labels: maintenance, team/saturn

#3785 Enhanced logs view with access log detail
  business/test_util.go
  business/workloads.go
  business/workloads_test.go
  go.mod
  go.sum
  handlers/workloads.go
Labels: frontend changes required, team/saturn

#3875 be able to port forward multiple kiali servers
  hack/kiali-port-forward.sh
Labels: maintenance

#3876 the way our make targets work, we need to allow ad-hoc kiali images
  Makefile
  make/Makefile.operator.mk
Labels: maintenance

#3880 Removing HPA references
  kubernetes/types.go
  models/autoscalers.go
Labels: operator changes required

#3838 OpenID Azure AKS+AAD support
  business/openid_auth.go
  config/config.go
  handlers/authentication.go
Labels: team/saturn

#3853 Add full list of discovered clusters to config endpoint
  handlers/config.go
Labels: team/saturn

#3849 Allow users to override add-on urls to check health for istio component status
  business/istio_status.go
  business/istio_status_test.go
  config/config.go
Labels: docs, operator changes required, team/jupiter

#3764 Istio ingress may be installed as a daemonset
  business/istio_status.go
  business/istio_status_test.go
  business/layer.go
Labels: operator changes required, team/jupiter

#3897 sidecar graph appender, fix problem when verifying node's namespace is accessible
  graph/telemetry/istio/appender/sidecars_check.go
  graph/telemetry/istio/appender/sidecars_check_test.go
Labels: team/saturn

#3898 Fix login failure with long OpenId tokens
  business/openid_auth.go
  handlers/authentication.go
Labels: team/saturn

#3902 need to allow ad hoc namespace and images when running the playbook target
  make/Makefile.operator.mk
Labels: maintenance

#3903 Cleanup - remove reference to an ServiceMesh CRD
  models/istio_validation.go
Labels: team/jupiter

#3926 better support for machines with podman
  hack/ci-minikube-molecule-tests.sh
  hack/istio/multicluster/env.sh
  hack/k8s-minikube.sh
  hack/run-molecule-tests.sh
  hack/run-prometheus.sh
Labels: maintenance

#3929 [hack] fix up ci scripts
  hack/ci-minikube-molecule-tests.sh
  hack/k8s-minikube.sh
  hack/run-molecule-tests.sh
Labels: maintenance, team/saturn

#3925 Adds configuration for the istio-sidecar-injector configmap name
  business/mesh.go
  business/mesh_test.go
  config/config.go
Labels: team/saturn

#3932 Fix hashbang in hack/k8s-minikube script
  hack/k8s-minikube.sh
Labels: team/saturn

#3940 [hack] forgot to use the env var rather than hardcoding kubectl
  hack/ci-minikube-molecule-tests.sh
Labels: maintenance

#3954 Adds a check to the makefile to see if OC is ready
  Makefile
Labels: team/saturn

#3935 Ensure idle nodes are created in the homecluster
  graph/telemetry/istio/appender/dead_node.go
  graph/telemetry/istio/appender/idle_node.go
  graph/telemetry/istio/appender/idle_node_test.go
Labels: team/saturn

#3937 Terminate gracefully on errors in OpenID's authorization code flow
  handlers/authentication.go
Labels: team/saturn

#3950 Fix missing units in jaeger query
  jaeger/http_client.go
Labels: team/jupiter
