Repository kiali/kiali, pull requests merged in 2022-09, with the labels that each got.

#5397 Update testing demos to be compatible with OpenShift 4.11
  hack/istio/install-bookinfo-demo.sh
  hack/istio/install-error-rates-demo.sh
  hack/istio/install-testing-demos.sh
  hack/istio/install-travel-agency-demo.sh
Labels: bug

#5439 add 2.3 compat information.
  config/version-compatibility-matrix.yaml
Labels: backlog

#5345 Added support of K8s Gateway API objects
  business/apps_test.go
  business/authentication/openid_auth_controller_test.go
  business/authentication/token_auth_controller_test.go
  business/health_test.go
  business/istio_certs_test.go
  business/istio_config.go
  business/istio_config_test.go
  business/istio_status_test.go
  business/istio_validations.go
  business/istio_validations_test.go
  business/mesh_test.go
  business/registry_status.go
  business/services_test.go
  business/tls_perf_test.go
  business/tls_test.go
  business/workloads_test.go
  config/config.go
  frontend/src/components/Pf/PfBadges.tsx
  frontend/src/components/VirtualList/Config.ts
  frontend/src/pages/IstioConfigList/FiltersAndSorts.ts
  frontend/src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  frontend/src/types/IstioConfigDetails.ts
  frontend/src/types/IstioConfigList.ts
  frontend/src/types/IstioObjects.ts
  frontend/src/utils/IstioConfigUtils.ts
  go.mod
  go.sum
  graph/api/api_test.go
  handlers/apps_test.go
  handlers/namespaces_test.go
  handlers/proxy_logging_test.go
  handlers/utils_test.go
  kubernetes/cache/cache.go
  kubernetes/cache/cache_test.go
  kubernetes/cache/istio.go
  kubernetes/cache/istio_test.go
  kubernetes/cache/kubernetes_test.go
  kubernetes/client.go
  kubernetes/istio.go
  kubernetes/kubernetes.go
  kubernetes/kubetest/mock.go
  kubernetes/kubetest/mock_istio.go
  kubernetes/types.go
  models/istio_config.go
  tests/integration/tests/istio_config_test.go
  tests/integration/utils/kiali_client.go
Labels: requires operator PR, requires helm chart PR

#5491 For Argo rollout, use the controller's replica sets as workloads
  business/test_util.go
  business/workloads.go
  business/workloads_test.go
  kubernetes/cache/kubernetes.go
  kubernetes/kubernetes.go
Labels: backport/v1.57

#5438 Skip Login Page for OpenId strategy
  business/authentication/openid_auth_controller.go
  frontend/src/pages/Login/LoginPage.tsx
Labels: enhancement

#5503 Adding more space between the chart name and the y axis value
  frontend/src/pages/Overview/OverviewCardControlPlaneNamespace.tsx
Labels: backport/v1.57

#5496 Added Gateway API support in Graph
  frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts
  frontend/src/pages/Graph/SummaryPanelNode.tsx
  frontend/src/types/Graph.ts
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/telemetry/istio/appender/istio_details.go
  kiali_api.md
Labels: backport/v1.57
