Repository kiali/kiali, pull requests merged in 2022-11, with the labels that each got.

#5592 secrets now injected into pod file system, not as env vars
  config/config.go
  config/config_test.go
Labels: requires operator PR, backport/v1.57

#5600 Prevent flooding backend with concurrent calls as the user drags across trace chart
  frontend/src/actions/MetricsStatsThunkActions.ts
  frontend/src/components/Charts/ChartWithLegend.tsx
  frontend/src/components/JaegerIntegration/JaegerScatter.tsx
  frontend/src/components/JaegerIntegration/TraceTooltip.tsx
Labels: backport/v1.57

#5608 New test in Overview for Min TLS
  frontend/cypress/integration/common/overview.ts
  frontend/cypress/integration/featureFiles/overview.feature
  frontend/src/components/Overview/TLSInfo.tsx
Labels: enhancement, cypress

#5605 Improvements in CP card for min TLS
  frontend/src/components/Overview/TLSInfo.tsx
  frontend/src/pages/Overview/OverviewPage.tsx
Labels: enhancement

#5624 Add key atribute to remove react warning
  frontend/src/components/Overview/TLSInfo.tsx
Labels: bug

#5604 [v1.57] secrets now injected into pod file system, not as env vars
  config/config.go
  config/config_test.go
Labels: requires operator PR

#5652 Be able to customize some timeouts for openshift auth
  business/openshift_oauth.go
  config/config.go
Labels: requires operator PR, requires helm chart PR, backport/v1.57
