Repository kiali/kiali, pull requests merged in 2022-06, with the labels that each got.

#5137 toolbar alignment issues
  frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx
  frontend/src/pages/Graph/GraphToolbar/GraphFindOptions.tsx
Labels: backlog

#5124 Update confirmation button placement and styling
  frontend/src/app/InitializingScreen.tsx
  frontend/src/components/About/AboutUIModal.tsx
  frontend/src/components/CytoscapeGraph/CytoscapeToolbar.tsx
  frontend/src/components/CytoscapeGraph/EmptyGraphLayout.tsx
  frontend/src/components/IstioActions/IstioActionsDropdown.tsx
  frontend/src/components/IstioConfigPreview/IstioConfigPreview.tsx
  frontend/src/components/IstioWizards/RequestRouting/MatchBuilder.tsx
  frontend/src/components/IstioWizards/RequestRouting/RuleBuilder.tsx
  frontend/src/components/IstioWizards/ServiceWizard.tsx
  frontend/src/components/IstioWizards/ServiceWizardDropdown.tsx
  frontend/src/components/IstioWizards/Slider/Slider.tsx
  frontend/src/components/IstioWizards/TrafficShifting.tsx
  frontend/src/components/IstioWizards/WorkloadWizard.tsx
  frontend/src/components/JaegerIntegration/JaegerResults/SpanTags.tsx
  frontend/src/components/Label/Labels.tsx
  frontend/src/components/MessageCenter/AlertDrawer.tsx
  frontend/src/components/MessageCenter/AlertDrawerGroup.tsx
  frontend/src/components/Nav/Navigation.tsx
  frontend/src/components/Refresh/RefreshButton.tsx
  frontend/src/components/SessionTimeout/SessionTimeout.tsx
  frontend/src/components/Time/TimeDurationComponent.tsx
  frontend/src/components/Tour/TourStop.tsx
  frontend/src/pages/Graph/GraphLegend.tsx
  frontend/src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  frontend/src/pages/Graph/SummaryPanelNodeTraces.tsx
  frontend/src/pages/Graph/SummaryPanelTraceDetails.tsx
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/From/SourceBuilder.tsx
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleBuilder.tsx
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/To/OperationBuilder.tsx
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/When/ConditionBuilder.tsx
  frontend/src/pages/IstioConfigNew/GatewayForm/ServerBuilder.tsx
  frontend/src/pages/IstioConfigNew/IstioConfigNewPage.tsx
  frontend/src/pages/IstioConfigNew/PeerAuthenticationForm.tsx
  frontend/src/pages/IstioConfigNew/RequestAuthorizationForm/JwtRuleBuilder.tsx
  frontend/src/pages/IstioConfigNew/ServiceEntryForm.tsx
  frontend/src/pages/IstioConfigNew/SidecarForm.tsx
  frontend/src/pages/Login/LoginPage.tsx
  frontend/src/pages/Overview/OverviewToolbar.tsx
  frontend/src/pages/Overview/OverviewTrafficPolicies.tsx
Labels: epic subtask

#5139 Add tooltips to graph side-panel traffic tabs
  frontend/src/pages/Graph/SummaryPanelClusterBox.tsx
  frontend/src/pages/Graph/SummaryPanelGraph.tsx
  frontend/src/pages/Graph/SummaryPanelNamespaceBox.tsx
Labels: backlog

#5157 Optimized workload validations load.
  business/istio_validations.go
Labels: scalability
