Repository kiali/kiali, pull requests merged in 2022-03, with the labels that each got.

#4778 Align namespace label in custom dashboards
  business/dashboards.go
  business/dashboards_test.go
  config/config.go
Labels: backport/v1.47

#4768 For Istio Config validations result JSON, make the key 'name.namespace' instead of 'name' only to support multiple namepaces
  models/istio_validation.go
  models/istio_validation_test.go
Labels: requires UI PR

#4739 Add QueryScope to narrow promethues queries against unified metrics
  business/dashboards.go
  business/dashboards_test.go
  business/metrics.go
  business/metrics_labels_builder.go
  business/metrics_labels_builder_test.go
  config/config.go
  graph/api/api_test.go
  graph/telemetry/istio/appender/security_policy_test.go
  graph/telemetry/istio/appender/util.go
  graph/telemetry/istio/appender/util_test.go
  graph/telemetry/istio/istio.go
  graph/telemetry/istio/util/util.go
  graph/telemetry/istio/util/util_test.go
Labels: requires operator PR

#4755 Add labeler appender for find/hide support
  business/services.go
  graph/appender.go
  graph/config/cytoscape/cytoscape.go
  graph/finalizer.go
  graph/meta.go
  graph/options.go
  graph/telemetry/istio/appender/aggregate_node.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/dead_node.go
  graph/telemetry/istio/appender/health_config.go
  graph/telemetry/istio/appender/idle_node.go
  graph/telemetry/istio/appender/istio_details.go
  graph/telemetry/istio/appender/labeler.go
  graph/telemetry/istio/appender/labeler_test.go
  graph/telemetry/istio/appender/outsider.go
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/appender/security_policy.go
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/sidecars_check.go
  graph/telemetry/istio/appender/throughput.go
  graph/telemetry/istio/appender/traffic_generator.go
  graph/telemetry/istio/appender/workload_entry.go
  graph/telemetry/istio/finalizer/finalizer.go
  graph/telemetry/istio/finalizer/traffic_generator.go
  graph/telemetry/istio/istio.go
  kiali_api.md
  swagger.json
Labels: requires UI PR

#4846 [v1.48] fix: add RW lock to put status (#4843)
  status/status.go
  status/status_test.go
Labels: bug

#4856 fix: add read lock when getting status
  status/status.go
  status/status_test.go
  status/versions.go
Labels: backlog, backport/v1.48
