Repository kiali/kiali, pull requests merged in 2022-10, with the labels that each got.

#5521 support more include/exclude features in namespaces api
  business/namespaces.go
  config/config.go
Labels: requires operator PR

#5549 Don't assume the prom config when testing for durations.
  frontend/cypress/integration/common/graph_toolbar.ts
Labels: backport/v1.57

#5563 [Cypress] Fix sidecar injection cypress tests that assumed only label
  frontend/cypress/integration/common/sidecar_injection.ts
Labels: backlog, backport/v1.57

#5566 Hide memory or CPU charts if there is no values to show
  frontend/src/pages/Overview/OverviewCardControlPlaneNamespace.tsx
Labels: backport/v1.57

#5579 Preview shows old state in Istio Config Wizard Preview
  frontend/src/components/IstioConfigPreview/IstioConfigPreview.tsx
Labels: bug

#5583 Add min TLS Version in CP Card
  business/istio_certs.go
  business/tls.go
  business/tls_test.go
  frontend/src/components/Overview/TLSInfo.tsx
  frontend/src/pages/Overview/OverviewPage.tsx
  frontend/src/pages/Overview/__tests__/OverviewPage.test.tsx
  frontend/src/reducers/MeshTlsState.ts
  frontend/src/store/Selectors.ts
  frontend/src/types/TLSStatus.ts
  models/mtls_status.go
  status/status.go
Labels: enhancement, backlog
