Repository kiali/kiali, pull requests merged in 2022-02, with the labels that each got.

#4409 adding a checker that warns about workloads which are not covered by …
  business/checkers/workloads/uncovered_workload_checker.go
  business/checkers/workloads/uncovered_workload_checker_test.go
  business/checkers/workloads_checker.go
  business/istio_validations.go
  business/istio_validations_test.go
  business/workloads.go
  handlers/istio_config.go
  handlers/namespaces.go
  handlers/services.go
  handlers/workloads.go
  kiali_api.md
  models/istio_validation.go
  models/workload.go
  swagger.json
  tests/data/authorization_policy_data.go
Labels: requires UI PR, docs, requires operator PR, requires helm chart PR

#4719 [v1.36] Protobuf version upgraded to v1.3.2
  go.mod
  go.sum
Labels: backport/v1.36

#4760 change observability name GetApp
  business/apps.go
Labels: bug
