Repository kiali/kiali, pull requests merged in 2022-08, with the labels that each got.

#5333 Overlay trace onclick event doesn't work
  frontend/src/pages/ServiceDetails/ServiceDetailsPage.tsx
Labels: bug

#5359 Remove js error in missing title in Modal component
  frontend/src/components/IstioWizards/ServiceWizard.tsx
Labels: bug

#5395 For Tracing queries, add QueryScope support (analogous to Prometheus)
  config/config.go
  handlers/jaeger.go
  jaeger/client.go
Labels: requires operator PR

#5400 Support Telemetry and WasmPlugin Istio objects
  business/checkers/telemetries_checker.go
  business/checkers/wasm_plugin_checker.go
  business/istio_config.go
  business/istio_validations.go
  business/registry_status.go
  frontend/src/components/Pf/PfBadges.tsx
  frontend/src/components/VirtualList/Config.ts
  frontend/src/pages/IstioConfigList/FiltersAndSorts.ts
  frontend/src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  frontend/src/types/IstioConfigDetails.ts
  frontend/src/types/IstioConfigList.ts
  frontend/src/types/IstioObjects.ts
  frontend/src/utils/IstioConfigUtils.ts
  kubernetes/cache/istio.go
  kubernetes/istio.go
  kubernetes/types.go
  models/istio_config.go
  models/istio_validation.go
Labels: enhancement, requires operator PR
