Repository kiali/kiali, pull requests merged in 2023-05, with the labels that each got.

#6077 Multicluster - Cluster badge and cluster name in details pages
  business/apps.go
  frontend/src/pages/AppDetails/AppDescription.tsx
  frontend/src/pages/ServiceDetails/ServiceDescription.tsx
  frontend/src/pages/WorkloadDetails/WorkloadDescription.tsx
  frontend/src/types/App.ts
  frontend/src/types/ServiceInfo.ts
  models/app.go
Labels: enhancement

#6085 Prevent crash scenario in namespace management
  business/namespaces.go
  handlers/istio_config.go
Labels: backport/special

#6090 removing flaky smoke test
  frontend/cypress/integration/common/kiali_homepage.ts
  frontend/cypress/integration/featureFiles/kiali_homepage.feature
Labels: test-cypress :robot:

#6104 Change configmap istio-cni error message for debug
  business/istio_config.go
  frontend/src/components/Ambient/AmbientBadge.tsx
Labels: enhancement

#6108 Check number of clusters to show the cluster badge in details pages
  frontend/src/pages/AppDetails/AppDescription.tsx
  frontend/src/pages/ServiceDetails/ServiceDescription.tsx
  frontend/src/pages/WorkloadDetails/WorkloadDescription.tsx
Labels: enhancement

#6110 [v1.57] [OSSM-1216] cypress container
  deploy/docker/Dockerfile-cypress
Labels: test-cypress :robot:

#6131 Multicluster - Add cluster params for metrics
  business/metrics.go
  frontend/src/actions/JaegerThunkActions.ts
  frontend/src/components/JaegerIntegration/JaegerResults/SpanDetails.tsx
  frontend/src/components/JaegerIntegration/JaegerResults/SpanTable.tsx
  frontend/src/components/JaegerIntegration/JaegerResults/TraceDetails.tsx
  frontend/src/components/JaegerIntegration/JaegerScatter.tsx
  frontend/src/components/JaegerIntegration/TracesComponent.tsx
  frontend/src/components/JaegerIntegration/TracesFetcher.ts
  frontend/src/pages/Graph/GraphPage.tsx
  frontend/src/pages/Graph/SummaryPanelNamespaceBox.tsx
  frontend/src/pages/Graph/SummaryPanelNodeTraces.tsx
  frontend/src/pages/Graph/SummaryPanelTraceDetails.tsx
  frontend/src/pages/Overview/OverviewPage.tsx
  frontend/src/services/Api.ts
  frontend/src/types/JaegerInfo.ts
  frontend/src/types/MetricsOptions.ts
  frontend/src/utils/tracing/TraceStats.ts
  frontend/src/utils/tracing/TraceTransform.ts
  frontend/src/utils/tracing/TracingHelper.ts
  frontend/src/utils/tracing/__tests__/TracingHelper.test.ts
  handlers/metrics.go
  models/metrics.go
Labels: enhancement

#6151 Add contextual menu for read links for remote clusters
  frontend/src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
Labels: enhancement

#6165 ensure healed graph edges go back to green on refresh
  frontend/src/types/ErrorRate/GraphEdgeStatus.ts
Labels: backport/special, backport/v1.65

#6163 Fix header in overview page for large names
  frontend/src/pages/Overview/OverviewPage.tsx
Labels: enhancement

#6147 Adding missing packages to cypress image
  deploy/docker/Dockerfile-cypress
Labels: test-cypress :robot:

#6146 [v1.57] Adding missing packages to cypress image
  deploy/docker/Dockerfile-cypress
Labels: test-cypress :robot:

#6145 [v1.57] Adding readme for int tests in a container
  tests/integration/README.md
  tests/integration/run-tests.sh
Labels: test-cypress :robot:

#6172 Kiali does not handle namespace-level injection enable/disable for Maistra
  frontend/cypress/integration/common/sidecar_injection.ts
Labels: backport/v1.65

#6105 Skipping the Gateway API tests when Gateway API is not enabled using Cypress hooks
  frontend/cypress/integration/common/hooks.ts
  frontend/cypress/integration/featureFiles/istio_config.feature
  frontend/cypress/integration/featureFiles/wizard_istio_config.feature
  frontend/cypress/integration/featureFiles/wizard_k8sgw_api_routing.feature
Labels: test-cypress :robot:

#6187 [v1.65] Flaky homepage test
  frontend/cypress/integration/common/kiali_homepage.ts
  frontend/cypress/integration/featureFiles/kiali_homepage.feature
Labels: test-cypress :robot:

#6119 Fix OCP tests
  make/Makefile.build.mk
  tests/integration/tests/no_istiod_test.go
  tests/integration/tests/remote_istiod_test.go
Labels: test-integration :nut_and_bolt:

#6181 authenticate when kiali is deployed behind openshift route with non-standard port
  util/httputil/http_util.go
Labels: requires operator PR, requires helm chart PR

#6204 get config list by namespace when not all namespaces are accessible
  handlers/istio_config.go
  models/istio_config.go
  tests/integration/tests/config_validations_test.go
  tests/integration/tests/no_istiod_test.go
Labels: enhancement

#6206 Update time out so the pod restart not affects other tests
  tests/integration/assets/remote-istiod/proxy-patch.yaml
  tests/integration/tests/no_istiod_test.go
  tests/integration/tests/remote_istiod_test.go
Labels: bug
