Repository kiali/kiali, pull requests merged in 2023-12, with the labels that each got.

#6902 Fixed showing additional items for Service, fixed the REST logo
  frontend/cypress/integration/common/services.ts
  frontend/cypress/integration/common/table.ts
  frontend/cypress/integration/featureFiles/services.feature
  frontend/src/assets/img/rest-logo.svg
  frontend/src/pages/ServiceDetails/ServiceDescription.tsx
  frontend/src/services/__mockData__/getServiceDetail.ts
  frontend/src/types/ServiceInfo.ts
Labels: test-add-coverage :paperclip:

#6883 Hover trace update - Tempo
  frontend/src/actions/ActionKeys.ts
  frontend/src/actions/TracingActions.ts
  frontend/src/actions/TracingThunkActions.ts
  frontend/src/components/Charts/ChartWithLegend.tsx
  frontend/src/components/TracingIntegration/TraceTooltip.tsx
  frontend/src/components/TracingIntegration/TracesComponent.tsx
  frontend/src/components/TracingIntegration/TracingScatter.tsx
  frontend/src/reducers/TracingState.ts
  hack/istio/tempo/install-tempo-env.sh
  tracing/tempo/grpc_client.go
  tracing/tempo/http_client.go
Labels: bug

#6917 Use the Tracer Name to emit traces
  observability/tracing.go
Labels: bug

#6891 Create an istio registry per primary
  .github/workflows/integration-tests-frontend-multicluster-multi-primary.yml
  .github/workflows/integration-tests-frontend-multicluster-primary-remote.yml
  .github/workflows/kiali-ci.yml
  business/apps_test.go
  business/controlplane_monitor.go
  business/controlplane_monitor_test.go
  business/fake_controlplane_monitor.go
  business/istio_config.go
  business/istio_config_test.go
  business/istio_status.go
  business/istio_status_test.go
  business/istio_validations.go
  business/istio_validations_test.go
  business/layer.go
  business/mesh.go
  business/registry_status.go
  business/services.go
  business/services_test.go
  business/testing.go
  business/workloads.go
  business/workloads_test.go
  config/config.go
  frontend/cypress/integration/common/istio_config.ts
  frontend/cypress/integration/common/overview.ts
  frontend/cypress/integration/common/sidecar_injection.ts
  frontend/cypress/integration/common/table.ts
  frontend/cypress/integration/common/wizard_request_routing.ts
  frontend/cypress/integration/featureFiles/istio_config.feature
  frontend/cypress/integration/featureFiles/overview.feature
  frontend/cypress/integration/featureFiles/wizard_istio_config.feature
  frontend/cypress/support/commands.ts
  frontend/package.json
  frontend/src/components/VirtualList/VirtualItem.tsx
  hack/istio/multicluster/install-multi-primary.sh
  hack/run-integration-tests.sh
  hack/setup-kind-in-ci.sh
  handlers/apps_test.go
  handlers/istio_config.go
  handlers/services.go
  kiali.go
  kubernetes/cache/cache.go
  kubernetes/cache/cache_handlers.go
  kubernetes/cache/cache_handlers_test.go
  kubernetes/cache/cache_test.go
  kubernetes/cache/kube_cache.go
  kubernetes/cache/kube_cache_test.go
  kubernetes/cache/proxy_status.go
  kubernetes/cache/registry_status.go
  kubernetes/cache/testing.go
  kubernetes/istio.go
  kubernetes/istio_internal_test.go
  kubernetes/kubernetes.go
  kubernetes/kubetest/mock.go
  kubernetes/token_test.go
  kubernetes/types.go
  server/server.go
  server/server_test.go
  store/store.go
  store/store_test.go
  store/threadsafe_store.go
Labels: docs, requires operator PR, requires helm chart PR

#6920 Add Tempo tests
  hack/istio/tempo/install-tempo-env.sh
  tracing/client_test.go
  tracing/tempo/grpc_client.go
  tracing/tempo/grpc_client_test.go
  tracing/tempo/http_client.go
  tracing/tempo/http_client_test.go
  tracing/tracingtest/response.json
  tracing/tracingtest/responseTrace.json
Labels: enhancement

#6741 Cypress Details page implementation for multicluster
  frontend/cypress/integration/common/app_details_multicluster.ts
  frontend/cypress/integration/common/service_details_multicluster.ts
  frontend/cypress/integration/common/workloads_details_multicluster.ts
  frontend/cypress/integration/featureFiles/app_details_multicluster.feature
  frontend/cypress/integration/featureFiles/service_details_multicluster.feature
  frontend/cypress/integration/featureFiles/workloads_details_multicluster.feature
  frontend/src/components/Charts/KChart.tsx
  hack/setup-kind-in-ci.sh
Labels: test-cypress :robot:, multicluster-testing

#6949 Include istio-waypoint api class as default
  business/istio_config.go
  config/config.go
  kubernetes/istio.go
Labels: enhancement, ambient

#6954 Include FQDN in error list for K8s HTTPRoute backend ref service name.
  business/checkers/k8shttproutes/no_host_checker.go
  business/checkers/k8shttproutes/no_host_checker_test.go
  models/istio_validation.go
  tests/integration/tests/config_validations_test.go
Labels: docs

#6959 [OSSM-5564][hack] Fix install testing demo script to support OSSM 2.5
  hack/istio/functions.sh
  hack/istio/install-sleep-demo.sh
  hack/istio/install-testing-demos.sh
Labels: backport needed

#6960 Use ignorecluster global for tracing
  tracing/client.go
  tracing/client_test.go
  tracing/jaeger/grpc_client.go
  tracing/jaeger/http_client.go
  tracing/jaeger/model/types.go
Labels: enhancement

#6965 [CI] Tempo tests workflow
  .github/workflows/integration-tests-frontend-tempo.yml
  .github/workflows/kiali-ci.yml
  business/tracing.go
  frontend/cypress/integration/common/graph_side_panel.ts
  frontend/cypress/integration/featureFiles/app_details.feature
  frontend/cypress/integration/featureFiles/graph_side_panel.feature
  frontend/cypress/integration/featureFiles/service_details.feature
  frontend/cypress/integration/featureFiles/workload_logs.feature
  frontend/cypress/integration/featureFiles/workloads_details.feature
  frontend/package.json
  frontend/src/pages/Graph/SummaryPanelNodeTraces.tsx
  hack/istio/tempo/install-tempo-env.sh
  hack/run-integration-tests.sh
  hack/setup-kind-in-ci.sh
Labels: enhancement

#6988 Update trace logic for Tempo lo limit the number of results
  business/tracing.go
  tracing/tempo/http_client.go
Labels: enhancement
