Repository kiali/kiali, pull requests merged in 2023-07, with the labels that each got.

#6316 Auto-enable find/hide filters via Kiali CR
  config/config.go
  frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx
  frontend/src/types/ServerConfig.ts
Labels: enhancement, docs, requires operator PR

#6323 L4 Telemetry is backwards
  business/metrics_definitions.go
  business/metrics_test.go
  graph/api/api_test.go
  graph/api/testdata/test_app_graph.expected
  graph/api/testdata/test_rates_received_graph.expected
  graph/api/testdata/test_rates_sent_graph.expected
  graph/api/testdata/test_service_graph.expected
  graph/api/testdata/test_versioned_app_graph.expected
  graph/api/testdata/test_workload_graph.expected
  graph/telemetry/istio/istio.go
Labels: enhancement

#6348 v1.65 - remote istiod obtain Istio deployment name
  tests/integration/tests/remote_istiod_test.go
Labels: bug, backport/v1.65

#6351 Enhance the cypress testing related to the kiali6331 Show Idle Nodes bug
  frontend/cypress/integration/common/graph_display.ts
  frontend/cypress/integration/common/hooks.ts
  frontend/cypress/integration/featureFiles/graph_display.feature
  hack/istio/install-error-rates-demo.sh
Labels: test-cypress :robot:

#6355 Backport flaky test fix
  frontend/cypress/integration/common/istio_config.ts
  frontend/cypress/integration/common/istio_config_validation_filters.ts
  frontend/cypress/integration/common/label_check.ts
Labels: test-cypress :robot:

#6364 Make cache mandatory and remove some cache config opts
  business/authentication/openid_auth_controller_test.go
  business/authentication/token_auth_controller_test.go
  business/istio_config.go
  business/istio_status_test.go
  business/layer.go
  business/mesh_test.go
  business/namespaces.go
  business/namespaces_test.go
  business/workloads_test.go
  config/config.go
  go.mod
  go.sum
  graph/api/api_test.go
  graph/telemetry/istio/appender/health_test.go
  handlers/apps_test.go
  handlers/proxy_logging_test.go
  handlers/workloads_test.go
  kubernetes/cache/cache.go
  kubernetes/cache/kube_cache.go
  kubernetes/cache/kube_cache_test.go
  kubernetes/cache/registry_test_helper.go
  server/server.go
  server/server_test.go
Labels: docs, requires operator PR

#6334 Use cluster param when it is available
  business/apps.go
  business/health.go
  business/istio_config.go
  business/istio_validations.go
  business/mesh.go
  business/namespaces.go
  business/namespaces_test.go
  business/services.go
  business/tls.go
  business/workloads.go
  handlers/apps.go
  handlers/apps_test.go
  handlers/dashboards.go
  handlers/health.go
  handlers/istio_config.go
  handlers/metrics.go
  handlers/metrics_test.go
  handlers/namespaces.go
  handlers/services.go
  handlers/services_test.go
  handlers/tls.go
  handlers/utils.go
  handlers/utils_test.go
  handlers/workloads.go
  handlers/workloads_test.go
  kubernetes/kubetest/mock_kubernetes.go
Labels: enhancement

#6406 Update the way kiali identifies Ambient
  business/istio_config.go
Labels: enhancement, ambient

#6419 Cypress automation for a Graph page test scenario
  frontend/cypress/integration/common/graph_display.ts
  frontend/cypress/integration/featureFiles/graph_display.feature
Labels: test-cypress :robot:

#6425 Remove extra parenthesis in PF Graph
  frontend/src/pages/GraphPF/GraphPF.tsx
Labels: bug

#6424 Include waypoint creation in bookinfo demo hack script
  hack/istio/install-bookinfo-demo.sh
Labels: enhancement, ambient
