Repository kiali/kiali, pull requests merged in 2023-11, with the labels that each got.

#6799 Tempo - Update Tracing url for Tempo
  frontend/src/components/About/AboutUIModal.tsx
  frontend/src/components/Nav/Menu.tsx
  frontend/src/components/Nav/Navigation.tsx
  frontend/src/components/Nav/__tests__/Navigation.test.tsx
  frontend/src/components/Nav/__tests__/RenderPage.test.tsx
  frontend/src/components/TracingIntegration/TracesComponent.tsx
Labels: enhancement

#6827 Refactor grpc client
  tracing/client.go
  tracing/jaeger/grpc_client.go
  tracing/jaeger/http_client.go
  tracing/tempo/http_client.go
Labels: enhancement

#6833 Cypress implementation of the Request Routing tests for the Multicluster setup
  frontend/cypress/integration/common/hooks.ts
  frontend/cypress/integration/common/wizard_request_routing.ts
  frontend/cypress/integration/featureFiles/wizard_request_routing.feature
Labels: test-cypress :robot:, multicluster

#6839 Update trace data on hover just for Tempo
  frontend/src/actions/ActionKeys.ts
  frontend/src/actions/TracingActions.ts
  frontend/src/actions/TracingThunkActions.ts
  frontend/src/components/Charts/ChartWithLegend.tsx
  frontend/src/components/TracingIntegration/TraceTooltip.tsx
  frontend/src/components/TracingIntegration/TracesComponent.tsx
  frontend/src/components/TracingIntegration/TracingResults/SpanDetails.tsx
  frontend/src/components/TracingIntegration/TracingResults/TraceDetails.tsx
  frontend/src/components/TracingIntegration/TracingScatter.tsx
  frontend/src/reducers/TracingState.ts
  frontend/src/types/TracingInfo.ts
Labels: bug

#6842 Update filtered spans for Tempo
  business/tracing.go
  tracing/tempo/http_client.go
Labels: enhancement

#6832 Use cluster tag for Tempo
  tracing/client.go
  tracing/otel/model/types.go
  tracing/tempo/http_client.go
  util/slice.go
Labels: bug

#6835 Tempo - Use select for queries
  tracing/tempo/http_client.go
  tracing/tempo/traceQLBuilder.go
Labels: enhancement

#6871 Update min duration unit for Jaeger traces filter
  tracing/jaeger/http_client.go
Labels: bug

#6853 gRPC client for Tempo (II)
  config/config.go
  go.mod
  hack/istio/tempo/minio.yaml
  tracing/client.go
  tracing/otel/model/converter/converter.go
  tracing/tempo/grpc_client.go
  tracing/tempo/tempopb/LICENSE_APACHE2
  tracing/tempo/tempopb/README.adoc
  tracing/tempo/tempopb/common/v1/common.pb.go
  tracing/tempo/tempopb/pool/pool.go
  tracing/tempo/tempopb/pool/pool_test.go
  tracing/tempo/tempopb/prealloc.go
  tracing/tempo/tempopb/prealloc_test.go
  tracing/tempo/tempopb/resource/v1/resource.pb.go
  tracing/tempo/tempopb/tempo.pb.go
  tracing/tempo/tempopb/tempo.proto
  tracing/tempo/tempopb/trace/v1/trace.pb.go
Labels: enhancement, docs, requires operator PR

#6882 Test coverage for MC badges on the Overview page
  frontend/cypress/integration/common/overview.ts
  frontend/cypress/integration/featureFiles/overview.feature
Labels: test-cypress :robot:, multicluster

#6823 Added Labels in Istio config creation wizard.
  frontend/cypress/integration/common/wizard_istio_config.ts
  frontend/cypress/integration/featureFiles/wizard_istio_config.feature
  frontend/src/components/IstioWizards/ServiceWizardDropdown.tsx
  frontend/src/components/IstioWizards/WizardActions.ts
  frontend/src/components/IstioWizards/WizardLabels.tsx
  frontend/src/components/IstioWizards/WorkloadWizardDropdown.tsx
  frontend/src/components/Label/Label.tsx
  frontend/src/components/Label/Labels.tsx
  frontend/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
  frontend/src/components/Label/__tests__/__snapshots__/Labels.test.tsx.snap
  frontend/src/config/KialiIcon.tsx
  frontend/src/pages/IstioConfigNew/IstioConfigNewPage.tsx
Labels: test-add-coverage :paperclip:
