Repository kiali/kiali, pull requests merged in 2024-07, with the labels that each got.

#7494 Move to golang 1.22.4
  go.mod
  go.sum
Labels: backport needed

#7498 Stringify the query data only if it is not already stringified
  frontend/src/services/Api.ts
Labels: test: n/a

#7516 Overview: Added missing cluster filter of results.
  frontend/src/pages/Overview/OverviewPage.tsx
Labels: test: n/a

#7505 Fix issue with yaml debug-info generation
  frontend/src/components/DebugInformation/DebugInformation.tsx
Labels: test: n/a

#7489 Improve Ambient appender performance
  business/workloads.go
  graph/telemetry/istio/appender/ambient.go
  graph/telemetry/istio/appender/appender.go
  kubernetes/cache/cache.go
  models/workload.go
Labels: enhancement, ambient

#7523 [v1.86] Fix issue with yaml debug-info generation (#7505)
  frontend/src/components/DebugInformation/DebugInformation.tsx
Labels: test: n/a

#7509 [v1.86] Stringify the query data only if it is not already stringified (#7498)
  frontend/src/services/Api.ts
Labels: test: n/a

#7508 Tracing is disabled by default
  config/config.go
  hack/istio/multicluster/deploy-kiali.sh
  hack/setup-kind-in-ci.sh
  mesh/api/api_test.go
  tests/integration/utils/kiali/instance.go
Labels: bug

#7532 Determine tempo version in Mesh page
  status/versions.go
Labels: enhancement

#7529 Use auth for check urls in Grafana & tracing
  status/versions.go
Labels: bug

#7538 Removed 'external_services.istio.component_status.components' duplicate labels.
  business/istio_status.go
  business/istio_status_test.go
  config/config.go
  handlers/istio_status.go
  istio/discovery.go
  istio/discovery_test.go
  mesh/api/testdata/test_mesh_graph.expected
Labels: requires operator PR, test: back-end/integration

#7535 Mesh page throws error when one of the clusters is inaccessible
  mesh/generator/generator.go
Labels: bug, test: n/a

#7554 Implement notification list with AlertGroup PF component
  frontend/src/components/MessageCenter/AlertToast.tsx
  frontend/src/components/MessageCenter/NotificationList.tsx
Labels: test: n/a

#7558 [1.73] Update the way the Kiali CR is updated for no istiod tests
  tests/integration/tests/no_istiod_test.go
  tests/integration/utils/kiali/instance.go
  tests/integration/utils/kiali/kiali_client.go
  tests/integration/utils/kube/util.go
Labels: test: back-end/integration

#7541 Setup openId for single cluster
  hack/istio/multicluster/deploy-kiali.sh
  hack/istio/multicluster/env.sh
  hack/istio/multicluster/realm-export-template.json
  hack/keycloak.sh
  hack/setup-kind-in-ci.sh
Labels: enhancement, test: n/a

#7560 [ambient graph] Fix HTTP traffic loss when disabling TCP traffic
  graph/telemetry/istio/appender/ambient.go
Labels: test: n/a

#7557 Align notification badge with PF standards
  frontend/public/locales/zh/translation.json
  frontend/src/components/IstioStatus/IstioStatus.tsx
  frontend/src/components/IstioStatus/__tests__/__snapshots__/IstioStatus.test.tsx.snap
  frontend/src/components/MessageCenter/MessageCenter.tsx
  frontend/src/components/MessageCenter/MessageCenterTrigger.tsx
  frontend/src/components/Nav/Masthead/HelpDropdown.tsx
  frontend/src/components/Nav/Masthead/LanguageSwitch.tsx
  frontend/src/components/Nav/Masthead/Masthead.tsx
  frontend/src/components/Nav/Masthead/ThemeSwitch.tsx
  frontend/src/components/Nav/Masthead/UserDropdown.tsx
  frontend/src/components/Nav/Navigation.tsx
  frontend/src/components/Nav/RenderPage.tsx
  frontend/src/components/Nav/__tests__/__snapshots__/ThemeSwitch.test.tsx.snap
Labels: test: front-end/cypress

#7547 Hide mesh page for non istio-system users
  frontend/cypress/integration/common/authorization.ts
  frontend/cypress/integration/common/kiali_cookie.ts
  frontend/cypress/integration/common/navigation.ts
  frontend/cypress/integration/featureFiles/authorization.feature
  frontend/cypress/integration/featureFiles/mesh.feature
  frontend/cypress/support/commands.ts
  frontend/src/components/About/AboutUIModal.tsx
  frontend/src/components/IstioStatus/IstioStatus.tsx
  frontend/src/components/IstioStatus/__tests__/__snapshots__/IstioStatus.test.tsx.snap
  frontend/src/components/Nav/Masthead/Masthead.tsx
  frontend/src/components/Nav/Menu.tsx
  frontend/src/pages/Overview/ControlPlaneBadge.tsx
  frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
  frontend/src/types/__testData__/HealthConfig.ts
  frontend/src/utils/MeshUtils.ts
  hack/istio/multicluster/deploy-kiali.sh
  hack/istio/multicluster/roleBookinfo.yaml
  handlers/graph.go
  handlers/mesh.go
  mesh/api/api.go
  mesh/generator/generator.go
Labels: enhancement

#7570 Add React import to .tsx files
  frontend/src/app/History.tsx
  frontend/src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
  frontend/src/components/HeatMap/HeatMap.tsx
  frontend/src/components/IstioWizards/ConfirmDeleteTrafficRoutingModal.tsx
  frontend/src/components/IstioWizards/Slider/BootstrapSlider.tsx
  frontend/src/components/IstioWizards/Slider/Boundaries.tsx
  frontend/src/components/IstioWizards/Slider/Slider.tsx
  frontend/src/components/Nav/Masthead/ThemeSwitch.tsx
  frontend/src/components/Nav/Page/RenderComponentScroll.tsx
  frontend/src/components/Nav/Page/RenderContent.tsx
  frontend/src/components/Nav/Page/RenderHeader.tsx
  frontend/src/components/Nav/RenderPage.tsx
  frontend/src/components/Nav/SecondaryMasthead.tsx
  frontend/src/components/Pf/PfBadges.tsx
  frontend/src/components/Pf/PfSpinner.tsx
  frontend/src/components/Refresh/RefreshNotifier.tsx
  frontend/src/components/Validations/GlobalValidation.tsx
  frontend/src/components/Validations/Validation.tsx
  frontend/src/components/Validations/ValidationList.tsx
  frontend/src/components/Validations/ValidationStack.tsx
  frontend/src/components/Validations/ValidationSummary.tsx
  frontend/src/components/VirtualList/VirtualItem.tsx
  frontend/src/config/Icons.ts
  frontend/src/hooks/refresh.ts
  frontend/src/hooks/services.ts
  frontend/src/pages/Graph/GraphToolbar/GraphReset.tsx
  frontend/src/pages/Graph/GraphToolbar/GraphSecondaryMasthead.tsx
  frontend/src/pages/Graph/GraphToolbar/GraphShortcuts.tsx
  frontend/src/pages/GraphPF/NodeDecorator.tsx
  frontend/src/pages/GraphPF/styles/styleGroup.tsx
  frontend/src/pages/Login/LoginPage.tsx
  frontend/src/pages/Mesh/styles/MeshGroup.tsx
  frontend/src/pages/Mesh/toolbar/MeshReset.tsx
  frontend/src/pages/Mesh/toolbar/MeshShortcuts.tsx
  frontend/src/pages/WorkloadDetails/PodStatus.tsx
  frontend/src/routes.tsx
  frontend/src/utils/ReactUtils.ts
Labels: backport needed, test: n/a
