Repository kiali/kiali, pull requests merged in 2024-10, with the labels that each got.

#7772 Adapt Cypress tests to the patternfly graph
  frontend/cypress/README.md
  frontend/cypress/integration/common/app_details_multicluster-cy.ts
  frontend/cypress/integration/common/app_details_multicluster-pf.ts
  frontend/cypress/integration/common/app_details_multicluster.ts
  frontend/cypress/integration/common/apps.ts
  frontend/cypress/integration/common/authorization-cy.ts
  frontend/cypress/integration/common/authorization-pf.ts
  frontend/cypress/integration/common/graph-cy.ts
  frontend/cypress/integration/common/graph-pf.ts
  frontend/cypress/integration/common/graph_context_menu-cy.ts
  frontend/cypress/integration/common/graph_context_menu-pf.ts
  frontend/cypress/integration/common/graph_display-cy.ts
  frontend/cypress/integration/common/graph_display-pf.ts
  frontend/cypress/integration/common/graph_find_hide-cy.ts
  frontend/cypress/integration/common/graph_find_hide-pf.ts
  frontend/cypress/integration/common/graph_side_panel-cy.ts
  frontend/cypress/integration/common/graph_side_panel-pf.ts
  frontend/cypress/integration/common/graph_toolbar-cy.ts
  frontend/cypress/integration/common/graph_toolbar-pf.ts
  frontend/cypress/integration/common/kiali_login.ts
  frontend/cypress/integration/common/service_details.ts
  frontend/cypress/integration/common/service_details_multicluster.ts
  frontend/cypress/integration/featureFiles/app_details.feature
  frontend/cypress/integration/featureFiles/app_details_graph-cy.feature
  frontend/cypress/integration/featureFiles/app_details_graph-pf.feature
  frontend/cypress/integration/featureFiles/app_details_multicluster.feature
  frontend/cypress/integration/featureFiles/app_details_multicluster_graph-cy.feature
  frontend/cypress/integration/featureFiles/app_details_multicluster_graph-pf.feature
  frontend/cypress/integration/featureFiles/graph_context_menu-cy.feature
  frontend/cypress/integration/featureFiles/graph_context_menu-pf.feature
  frontend/cypress/integration/featureFiles/graph_display-cy.feature
  frontend/cypress/integration/featureFiles/graph_display-pf.feature
  frontend/cypress/integration/featureFiles/graph_display_user-cy.feature
  frontend/cypress/integration/featureFiles/graph_display_user-pf.feature
  frontend/cypress/integration/featureFiles/graph_find_hide-cy.feature
  frontend/cypress/integration/featureFiles/graph_find_hide-pf.feature
  frontend/cypress/integration/featureFiles/graph_replay-cy.feature
  frontend/cypress/integration/featureFiles/graph_replay-pf.feature
  frontend/cypress/integration/featureFiles/graph_side_panel-cy.feature
  frontend/cypress/integration/featureFiles/graph_side_panel-pf.feature
  frontend/cypress/integration/featureFiles/graph_toolbar-cy.feature
  frontend/cypress/integration/featureFiles/graph_toolbar-pf.feature
  frontend/cypress/integration/featureFiles/graph_toolbar_legend-cy.feature
  frontend/cypress/integration/featureFiles/graph_toolbar_legend-pf.feature
  frontend/cypress/integration/featureFiles/service_details.feature
  frontend/cypress/integration/featureFiles/service_details_graph-cy.feature
  frontend/cypress/integration/featureFiles/service_details_graph-pf.feature
  frontend/cypress/integration/featureFiles/service_details_multicluster.feature
  frontend/cypress/integration/featureFiles/service_details_multicluster_graph-cy.feature
  frontend/cypress/integration/featureFiles/service_details_multicluster_graph-pf.feature
  frontend/cypress/integration/featureFiles/workloads_details _graph-cy.feature
  frontend/cypress/integration/featureFiles/workloads_details _graph-pf.feature
  frontend/cypress/integration/featureFiles/workloads_details.feature
  frontend/cypress/integration/featureFiles/workloads_details_multicluster.feature
  frontend/cypress/integration/featureFiles/workloads_details_multicluster_graph-cy.feature
  frontend/cypress/integration/featureFiles/workloads_details_multicluster_graph-pf.feature
  frontend/package.json
Labels: test: front-end/cypress

#7782 Fix issue with bookmarked find/hide not being evaluated in PFT graph or Mesh page
  frontend/src/actions/GraphThunkActions.ts
  frontend/src/pages/Graph/GraphToolbar/GraphFindPF.tsx
  frontend/src/pages/GraphPF/GraphPF.tsx
  frontend/src/pages/GraphPF/GraphPagePF.tsx
  frontend/src/pages/Mesh/Mesh.tsx
  frontend/src/pages/Mesh/toolbar/MeshFind.tsx
Labels: test: n/a

#7786 Set default graph impl to PFT
  config/config.go
  frontend/cypress/integration/common/authorization-pf.ts
  frontend/cypress/integration/common/graph-pf.ts
  frontend/cypress/integration/common/graph_context_menu-pf.ts
  frontend/cypress/integration/common/graph_display-pf.ts
  frontend/cypress/integration/common/graph_find_hide-pf.ts
  frontend/cypress/integration/common/graph_side_panel-pf.ts
  frontend/cypress/integration/common/graph_toolbar-pf.ts
  frontend/cypress/integration/common/mesh.ts
  frontend/cypress/integration/featureFiles/graph_toolbar-cy.feature
  frontend/src/config/ServerConfig.ts
  frontend/src/pages/GraphPF/GraphPagePF.tsx
  frontend/src/pages/Mesh/MeshPage.tsx
  frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
  frontend/src/types/ServerConfig.ts
  frontend/src/types/__testData__/HealthConfig.ts
  hack/istio/multicluster/deploy-kiali.sh
  hack/setup-kind-in-ci.sh
Labels: test: front-end/cypress

#7788 [pft graph] fix node-graph selection snap-back issue
  frontend/src/pages/GraphPF/GraphPF.tsx
Labels: test: n/a

#7796 be able to put username in secrets
  config/config.go
  config/config_test.go
Labels: requires operator PR

#7784 Fix sparkline issue for waypoint-edge side panel
  frontend/src/pages/Graph/SummaryPanelEdge.tsx
Labels: test: n/a

#7783 Apply our own bendpoint logic to parallel edges
  frontend/src/pages/GraphPF/elements/extendedBaseEdge.ts
  frontend/src/pages/GraphPF/layouts/ExtendedDagreLayout.ts
  frontend/src/pages/GraphPF/layouts/layoutFactory.ts
Labels: test: n/a

#7798 Update the config for the open telemetry collector
  frontend/cypress/integration/featureFiles/app_details_multicluster.feature
  hack/istio/multicluster/deploy-kiali.sh
  hack/istio/multicluster/setup-tracing.sh
  hack/run-integration-tests.sh
Labels: maintenance

#7805 Hide node kebab context menus from pft graph
  frontend/src/pages/GraphPF/GraphPFElems.tsx
  frontend/src/pages/GraphPF/styles/styleGroup.tsx
  frontend/src/pages/GraphPF/styles/styleNode.tsx
  frontend/src/styles/GlobalStyle.ts
Labels: test: n/a

#7808 [pft graph] Add dynamic "wizard" options to service node context menus
  frontend/src/components/IstioWizards/ServiceWizardActionsDropdownGroup.tsx
  frontend/src/pages/Graph/GraphToolbar/GraphShortcutsPF.tsx
  frontend/src/pages/GraphPF/GraphPF.tsx
  frontend/src/pages/GraphPF/GraphPagePF.tsx
  frontend/src/pages/GraphPF/MiniGraphCardPF.tsx
  frontend/src/pages/GraphPF/components/stylesComponentFactory.tsx
Labels: test: n/a

#7810 Fix margin issue in the label graph in Firefox
  frontend/src/pages/GraphPF/GraphPFElems.tsx
  frontend/src/pages/GraphPF/styles/styleNode.tsx
  frontend/src/styles/GlobalStyle.ts
Labels: test: n/a

#7812 Refactor : Gateway Selector - Form Select to Select
  frontend/src/components/IstioWizards/GatewaySelector.tsx
  frontend/src/components/IstioWizards/ServiceWizard.tsx
Labels: test: n/a

#7819 Fixed DaemonSet workload fetching error message
  business/workloads.go
Labels: test: n/a

#7816 Graph toolbar: Replace disabled with active style
  frontend/src/pages/GraphPF/GraphPF.tsx
  frontend/src/pages/GraphPF/MiniGraphCardPF.tsx
  frontend/src/pages/Mesh/Mesh.tsx
  frontend/src/styles/GraphStyle.ts
Labels: test: n/a

#7809 fix issues with control plane metrics
  business/metrics.go
  frontend/public/locales/zh/translation.json
  frontend/src/components/Link/IstioObjectLink.tsx
  frontend/src/components/Overview/TLSInfo.tsx
  frontend/src/components/TracingIntegration/TracesDisplayOptions.tsx
  frontend/src/components/VirtualList/Renderers.tsx
  frontend/src/config/Config.ts
  frontend/src/pages/Graph/GraphToolbar/GraphSettings.tsx
  frontend/src/pages/Graph/GraphToolbar/GraphTraffic.tsx
  frontend/src/pages/Mesh/target/TargetPanelControlPlane.tsx
  frontend/src/pages/Mesh/target/TargetPanelControlPlaneMetrics.tsx
  frontend/src/pages/Mesh/target/TargetPanelControlPlaneStatus.tsx
  frontend/src/pages/Mesh/target/TargetPanelNamespace.tsx
  frontend/src/pages/Overview/ControlPlaneBadge.tsx
  frontend/src/pages/Overview/ControlPlaneNamespaceStatus.tsx
  frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx
  frontend/src/services/Api.ts
  frontend/src/styles/DropdownStyles.ts
  frontend/src/types/NamespaceInfo.ts
  handlers/metrics.go
  handlers/metrics_test.go
  handlers/namespaces_test.go
  prometheus/client.go
  prometheus/metrics.go
  prometheus/prometheustest/mock.go
  routing/routes.go
Labels: test: back-end/integration

#7813 [ambient] e2e test - Initial waypoint tests
  frontend/cypress/integration/common/graph_display-pf.ts
  frontend/cypress/integration/common/istio_config.ts
  frontend/cypress/integration/common/overview.ts
  frontend/cypress/integration/common/table.ts
  frontend/cypress/integration/common/waypoint.ts
  frontend/cypress/integration/featureFiles/overview.feature
  frontend/cypress/integration/featureFiles/waypoint.feature
  frontend/package.json
  hack/istio/install-testing-demos.sh
Labels: ambient, test: front-end/cypress

#7831 Enable rank feature in the patternfly graph
  frontend/src/pages/GraphPF/GraphPF.tsx
  frontend/src/pages/GraphPF/MiniGraphCardPF.tsx
Labels: test: n/a

#7824 [Tempo] View in Tracing url
  config/config.go
  frontend/src/types/StatusState.ts
  frontend/src/types/Tracing.ts
  frontend/src/utils/tracing/UrlProviders/Jaeger.ts
  frontend/src/utils/tracing/UrlProviders/index.ts
  hack/istio/tempo/install-tempo-env.sh
Labels: enhancement

#7833 [mesh page] Protect against the possibility of no time-series for the proxy sync time.
  business/metrics.go
Labels: test: n/a

#7799 Cypress tests for PatternFly Graph
  frontend/cypress/README.md
  frontend/cypress/integration/common/app_details_multicluster-pf.ts
  frontend/cypress/integration/common/authorization-pf.ts
  frontend/cypress/integration/common/graph-pf.ts
  frontend/cypress/integration/common/graph_context_menu-cy.ts
  frontend/cypress/integration/common/graph_context_menu-pf.ts
  frontend/cypress/integration/common/graph_display-pf.ts
  frontend/cypress/integration/common/graph_find_hide-cy.ts
  frontend/cypress/integration/common/graph_find_hide-pf.ts
  frontend/cypress/integration/common/graph_side_panel-cy.ts
  frontend/cypress/integration/common/graph_side_panel-pf.ts
  frontend/cypress/integration/common/graph_toolbar-pf.ts
  frontend/cypress/integration/common/graph_toolbar_legend-cy.ts
  frontend/cypress/integration/common/graph_toolbar_legend-pf.ts
  frontend/cypress/integration/common/mesh.ts
  frontend/cypress/integration/featureFiles/app_details_graph-cy.feature
  frontend/cypress/integration/featureFiles/app_details_graph-pf.feature
  frontend/cypress/integration/featureFiles/app_details_multicluster_graph-cy.feature
  frontend/cypress/integration/featureFiles/app_details_multicluster_graph-pf.feature
  frontend/cypress/integration/featureFiles/graph_context_menu-cy.feature
  frontend/cypress/integration/featureFiles/graph_context_menu-pf.feature
  frontend/cypress/integration/featureFiles/graph_display-cy.feature
  frontend/cypress/integration/featureFiles/graph_display-pf.feature
  frontend/cypress/integration/featureFiles/graph_display_user-cy.feature
  frontend/cypress/integration/featureFiles/graph_display_user-pf.feature
  frontend/cypress/integration/featureFiles/graph_find_hide-cy.feature
  frontend/cypress/integration/featureFiles/graph_find_hide-pf.feature
  frontend/cypress/integration/featureFiles/graph_replay-cy.feature
  frontend/cypress/integration/featureFiles/graph_replay-pf.feature
  frontend/cypress/integration/featureFiles/graph_side_panel-cy.feature
  frontend/cypress/integration/featureFiles/graph_side_panel-pf.feature
  frontend/cypress/integration/featureFiles/graph_toolbar-cy.feature
  frontend/cypress/integration/featureFiles/graph_toolbar-pf.feature
  frontend/cypress/integration/featureFiles/graph_toolbar_legend-cy.feature
  frontend/cypress/integration/featureFiles/graph_toolbar_legend-pf.feature
  frontend/cypress/integration/featureFiles/service_details_graph-cy.feature
  frontend/cypress/integration/featureFiles/service_details_graph-pf.feature
  frontend/cypress/integration/featureFiles/service_details_multicluster_graph-cy.feature
  frontend/cypress/integration/featureFiles/service_details_multicluster_graph-pf.feature
  frontend/cypress/integration/featureFiles/waypoint.feature
  frontend/cypress/integration/featureFiles/workloads_details _graph-cy.feature
  frontend/cypress/integration/featureFiles/workloads_details _graph-pf.feature
  frontend/cypress/integration/featureFiles/workloads_details_multicluster_graph-cy.feature
  frontend/cypress/integration/featureFiles/workloads_details_multicluster_graph-pf.feature
  frontend/cypress/support/commands.ts
  frontend/package.json
  frontend/src/components/CytoscapeGraph/EmptyGraphLayout.tsx
  frontend/src/pages/GraphPF/GraphPagePF.tsx
  frontend/src/pages/GraphPF/MiniGraphCardPF.tsx
  hack/istio/multicluster/deploy-kiali.sh
  hack/setup-kind-in-ci.sh
Labels: test: front-end/cypress

#7836 [mesh page] [graph] Fix issue with laying out on an element change
  frontend/src/pages/Graph/GraphToolbar/GraphFindPF.tsx
  frontend/src/pages/GraphPF/GraphPF.tsx
  frontend/src/pages/GraphPF/GraphPagePF.tsx
  frontend/src/pages/Mesh/Mesh.tsx
  frontend/src/pages/Mesh/MeshElems.tsx
  frontend/src/pages/Mesh/MeshPage.tsx
  frontend/src/pages/Mesh/components/meshComponentFactory.tsx
  frontend/src/pages/Mesh/toolbar/MeshFind.tsx
  frontend/src/pages/Mesh/toolbar/__tests__/MeshFind.test.tsx
Labels: test: n/a

#7848 Upgrade http-proxy-middleware to 2.0.7
  frontend/yarn.lock
Labels: backport needed

#7787 Improve tag support on the mesh page
  business/istio_status.go
  business/istio_status_test.go
  business/istio_validations.go
  business/layer.go
  business/mesh.go
  business/mesh_test.go
  business/namespaces.go
  business/testing.go
  business/tls.go
  business/tls_perf_test.go
  business/tls_test.go
  frontend/public/locales/zh/translation.json
  frontend/src/actions/ActionKeys.ts
  frontend/src/config/Config.ts
  frontend/src/pages/Mesh/MeshElems.tsx
  frontend/src/pages/Mesh/target/TargetPanelCommon.tsx
  frontend/src/pages/Mesh/target/TargetPanelControlPlane.tsx
  frontend/src/pages/Mesh/target/TargetPanelNamespace.tsx
  frontend/src/pages/Overview/CanaryUpgradeProgress.tsx
  frontend/src/pages/Overview/ControlPlaneDonut.tsx
  frontend/src/pages/Overview/OverviewPage.tsx
  frontend/src/pages/Overview/OverviewTrafficPolicies.tsx
  frontend/src/reducers/__tests__/NamespacesReducer.test.ts
  frontend/src/services/Api.ts
  frontend/src/store/Store.ts
  frontend/src/types/IstioObjects.ts
  frontend/src/types/Mesh.ts
  frontend/src/types/Namespace.ts
  frontend/src/types/NamespaceInfo.ts
  hack/setup-kind-in-ci.sh
  handlers/mesh.go
  handlers/mesh_test.go
  handlers/utils.go
  istio/discovery.go
  istio/discovery_test.go
  istio/istiotest/fake.go
  mesh/api/testdata/test_mesh_graph.expected
  mesh/generator/generator.go
  models/mesh.go
  models/namespace.go
  models/namespace_test.go
  routing/routes.go
Labels: test: back-end/integration

#7852 Fine-tune Mesh topology style
  frontend/src/pages/GraphPF/GraphPFElems.tsx
  frontend/src/pages/GraphPF/MiniGraphCardPF.tsx
  frontend/src/pages/GraphPF/styles/styleNode.tsx
  frontend/src/pages/Mesh/MeshElems.tsx
  frontend/src/pages/Mesh/MeshHighlighter.ts
  frontend/src/pages/Mesh/components/meshComponentFactory.tsx
  frontend/src/pages/Mesh/styles/MeshEdge.tsx
  frontend/src/pages/Mesh/styles/MeshNode.tsx
  frontend/src/styles/GlobalStyle.ts
Labels: test: n/a

#7847 Uncomment waypoint tests
  frontend/cypress/integration/common/graph_display-pf.ts
  frontend/cypress/integration/common/waypoint.ts
  frontend/cypress/integration/featureFiles/waypoint.feature
Labels: test: front-end/cypress

#7453 Add APIVersion value to the Istio config object
  kubernetes/cache/kube_cache.go
  kubernetes/cache/kube_cache_test.go
  kubernetes/types.go
Labels: test: back-end/integration

#7864 Change icon color to something more appropriate
  frontend/src/types/Health.ts
Labels: test: n/a

#7865 protect against IP internal_url in mesh service discovery
  mesh/generator/generator.go
Labels: test: n/a

#7857 Fix issue with minigraph node navigation
  frontend/cypress/integration/common/app_details_multicluster-pf.ts
  frontend/cypress/integration/featureFiles/app_details_multicluster_graph-pf.feature
  frontend/cypress/integration/featureFiles/workloads_details_multicluster_graph-pf.feature
  frontend/src/pages/Graph/GraphToolbar/GraphFindPF.tsx
  frontend/src/pages/GraphPF/GraphHighlighterPF.ts
  frontend/src/pages/GraphPF/GraphPF.tsx
  frontend/src/pages/GraphPF/GraphPFElems.tsx
  frontend/src/pages/GraphPF/GraphPagePF.tsx
  frontend/src/pages/GraphPF/MiniGraphCardPF.tsx
  frontend/src/pages/GraphPF/TracePF.ts
  frontend/src/pages/Mesh/Mesh.tsx
  frontend/src/pages/Mesh/MeshElems.tsx
  frontend/src/pages/Mesh/MeshHighlighter.ts
  frontend/src/pages/Mesh/toolbar/MeshFind.tsx
Labels: test: front-end/cypress

#7869 A single Before statement in Cypress is enough
  frontend/cypress/integration/common/graph_display-cy.ts
  frontend/cypress/integration/common/graph_display-pf.ts
  frontend/cypress/integration/common/graph_replay.ts
  frontend/cypress/integration/common/graph_toolbar-cy.ts
  frontend/cypress/integration/common/graph_toolbar-pf.ts
  frontend/cypress/integration/common/hooks.ts
  frontend/cypress/integration/common/mesh.ts
  frontend/cypress/integration/common/overview.ts
  frontend/cypress/integration/common/wizard_request_routing.ts
Labels: test: front-end/cypress

#7871 Upgrade CRC to 2.42.0 - OpenShift 4.17
  hack/crc-openshift.sh
Labels: test: n/a

#7872 Validate istioInitContainer pods
  frontend/src/pages/WorkloadDetails/WorkloadInfo.tsx
  hack/istio/nativesidecars/install-native-sidecars-env.sh
Labels: bug

#7874 Add more types to mesh page components
  frontend/src/actions/MeshThunkActions.ts
  frontend/src/components/Table/ConfigTable.tsx
  frontend/src/helpers/GraphHelpers.tsx
  frontend/src/pages/Graph/GraphToolbar/GraphFindPF.tsx
  frontend/src/pages/Graph/SummaryPanelAppBox.tsx
  frontend/src/pages/Graph/SummaryPanelClusterBox.tsx
  frontend/src/pages/Graph/SummaryPanelGraph.tsx
  frontend/src/pages/Graph/SummaryPanelNamespaceBox.tsx
  frontend/src/pages/Graph/SummaryPanelNodeTraffic.tsx
  frontend/src/pages/Graph/SummaryPanelTraceDetails.tsx
  frontend/src/pages/GraphPF/GraphHighlighterPF.ts
  frontend/src/pages/GraphPF/GraphPF.tsx
  frontend/src/pages/GraphPF/GraphPFElems.tsx
  frontend/src/pages/GraphPF/MiniGraphCardPF.tsx
  frontend/src/pages/GraphPF/TracePF.ts
  frontend/src/pages/GraphPF/layouts/ExtendedDagreLayout.ts
  frontend/src/pages/Mesh/Mesh.tsx
  frontend/src/pages/Mesh/MeshElems.tsx
  frontend/src/pages/Mesh/MeshHighlighter.ts
  frontend/src/pages/Mesh/target/TargetPanel.tsx
  frontend/src/pages/Mesh/target/TargetPanelCluster.tsx
  frontend/src/pages/Mesh/target/TargetPanelConfigTable.tsx
  frontend/src/pages/Mesh/target/TargetPanelControlPlane.tsx
  frontend/src/pages/Mesh/target/TargetPanelDataPlane.tsx
  frontend/src/pages/Mesh/target/TargetPanelDataPlaneNamespace.tsx
  frontend/src/pages/Mesh/target/TargetPanelMesh.tsx
  frontend/src/pages/Mesh/target/TargetPanelNamespace.tsx
  frontend/src/pages/Mesh/target/TargetPanelNode.tsx
  frontend/src/pages/Mesh/toolbar/MeshFind.tsx
  frontend/src/types/Mesh.ts
Labels: test: n/a
