Repository kiali/kiali, pull requests merged in 2024-09, with the labels that each got.

#7686 [v1.89] Tempo query scope fix (#7662)
  business/tracing.go
  hack/istio/multicluster/deploy-kiali.sh
  hack/istio/multicluster/env.sh
  hack/istio/multicluster/install-primary-remote.sh
  hack/run-integration-tests.sh
  hack/setup-kind-in-ci.sh
  tracing/tempo/http_client.go
Labels: bug

#7652 Added support of Mesh config defaultExportTo fields.
  business/istio_validations.go
  business/istio_validations_test.go
  business/mesh.go
  business/mesh_test.go
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/service_entry_test.go
  kubernetes/filters.go
  mesh/api/testdata/test_mesh_graph.expected
  models/mesh.go
  tests/data/validations/exportto/cns/dr_bookinfo1_not_exported.yaml
  tests/data/validations/exportto/cns/dr_bookinfo2_not_exported.yaml
  tests/data/validations/exportto/cns/se_bookinfo1_not_exported.yaml
  tests/data/validations/exportto/cns/se_bookinfo2_not_exported.yaml
  tests/data/validations/exportto/cns/vs_bookinfo1_not_exported.yaml
  tests/data/validations/exportto/cns/vs_bookinfo2_not_exported.yaml
Labels: test: back-end/integration

#7677 [Graph] Update tcp legend for patternfly graph
  frontend/src/assets/img/graph/pf/edge-tcp.svg
Labels: enhancement

#7689 Fix graph appender problem
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/istio_details_test.go
Labels: test: back-end/integration

#7593 [ambient] waypoint arrows and PF fix
  frontend/src/components/CytoscapeGraph/__tests__/GraphScore.test.ts
  frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts
  frontend/src/pages/GraphPF/GraphHighlighterPF.ts
  frontend/src/pages/GraphPF/GraphPFElems.tsx
  frontend/src/types/Graph.ts
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/telemetry/istio/appender/ambient.go
Labels: enhancement, ambient, backport needed

#7698 [1.73] Fix flaky int tests with tempo tracing
  tests/integration/utils/kiali/kiali_client.go
Labels: test: back-end/integration

#7701 [v1.89] Fix graph appender problem
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/istio_details_test.go
Labels: test: back-end/integration

#7694 [v1.89] Upgrade images for IBM
  hack/istio/install-sleep-demo.sh
  hack/istio/kustomization/bookinfo-ppc64le.yaml
  hack/istio/kustomization/bookinfo-s390x.yaml
Labels: test: back-end/integration

#7700 [v1.89] [ambient] waypoint arrows and PF fix
  frontend/src/components/CytoscapeGraph/__tests__/GraphScore.test.ts
  frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts
  frontend/src/pages/GraphPF/GraphHighlighterPF.ts
  frontend/src/pages/GraphPF/GraphPFElems.tsx
  frontend/src/types/Graph.ts
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/telemetry/istio/appender/ambient.go
Labels: enhancement, ambient

#7657 Update comments for waypoint icons
  frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts
  frontend/src/pages/GraphPF/GraphPFElems.tsx
Labels: enhancement, ambient

#7711 [v1.65] Upgrade x/net version
  go.mod
  go.sum
Labels: dependencies

#7715 Fix sidecar injection flaky test
  frontend/cypress/integration/common/sidecar_injection.ts
Labels: test: front-end/cypress

#7695 Add support for tags in mesh page
  business/mesh.go
  business/namespaces.go
  business/tls.go
  config/config.go
  frontend/cypress/integration/common/mesh.ts
  frontend/cypress/integration/featureFiles/mesh.feature
  frontend/public/locales/zh/translation.json
  frontend/src/pages/Mesh/target/TargetPanelDataPlane.tsx
  frontend/src/pages/Mesh/target/TargetPanelMesh.tsx
  frontend/src/pages/Mesh/target/TargetPanelNamespace.tsx
  frontend/src/pages/Overview/ControlPlaneVersionBadge.tsx
  frontend/src/pages/Overview/OverviewPage.tsx
  frontend/src/types/Mesh.ts
  hack/run-integration-tests.sh
  hack/setup-kind-in-ci.sh
  istio/discovery.go
  istio/discovery_selectors.go
  istio/discovery_selectors_test.go
  istio/discovery_test.go
  istio/kubernetes.go
  kubernetes/cache/cache.go
  mesh/api/api_test.go
  mesh/api/testdata/test_mesh_graph.expected
  mesh/config/cytoscape/cytoscape.go
  mesh/generator/generator.go
  mesh/meta.go
  models/mesh.go
  models/namespace.go
Labels: requires operator PR, requires helm chart PR, test: front-end/cypress

#7730 Update express, path-to-regexp and micromatch dependencies
  frontend/package.json
  frontend/yarn.lock
Labels: backport needed, test: n/a

#7732 [v1.89] Update express, path-to-regexp and micromatch dependencies
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7731 Added missing K8sGateway label name check for MissingSidecar icon
  config/config.go
  frontend/src/config/ServerConfig.ts
  frontend/src/helpers/LabelFilterHelper.ts
  frontend/src/helpers/__tests__/LabelFilterHelper.test.ts
  frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
  frontend/src/types/ServerConfig.ts
  frontend/src/types/__testData__/HealthConfig.ts
  graph/telemetry/istio/appender/mesh_check.go
  models/workload.go
  models/workload_test.go
Labels: test: back-end/integration

#7707 Upgrade images for IBM
  hack/istio/install-sleep-demo.sh
  hack/istio/kustomization/bookinfo-ppc64le.yaml
  hack/istio/kustomization/bookinfo-s390x.yaml
Labels: test: front-end/cypress, test: back-end/integration

#7733 [v1.73] Update express, path-to-regexp and micromatch dependencies
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7734 [v1.65] Update express, path-to-regexp and micromatch dependencies
  frontend/yarn.lock
Labels: test: n/a

#7736 Update bookinfo install hack script to have db services opt out of waypoint
  hack/istio/install-bookinfo-demo.sh
Labels: ambient, test: n/a

#7743 Update install istio script to make arg optional
  hack/istio/install-istio-via-istioctl.sh
Labels: enhancement

#7739 [v1.89] Update express dependency (again)
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7738 Update express dependency (again)
  frontend/package.json
  frontend/yarn.lock
Labels: backport needed, test: n/a

#7750 Update serialize-javascript dependency
  frontend/package.json
  frontend/yarn.lock
Labels: backport needed, test: n/a

#7754 [v1.73] Update serialize-javascript dependency
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7742 Prevent service node injection for waypoint edges
  graph/api/api.go
  graph/api/api_test.go
  graph/api/testdata/test_ambient_graph.expected
  graph/appender.go
  graph/config/cytoscape/cytoscape.go
  graph/telemetry.go
  graph/telemetry/istio/appender/aggregate_node.go
  graph/telemetry/istio/appender/ambient.go
  graph/telemetry/istio/appender/ambient_test.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/dead_node.go
  graph/telemetry/istio/appender/dead_node_test.go
  graph/telemetry/istio/appender/health.go
  graph/telemetry/istio/appender/health_test.go
  graph/telemetry/istio/appender/idle_node.go
  graph/telemetry/istio/appender/istio_details.go
  graph/telemetry/istio/appender/istio_details_test.go
  graph/telemetry/istio/appender/labeler.go
  graph/telemetry/istio/appender/labeler_test.go
  graph/telemetry/istio/appender/mesh_check.go
  graph/telemetry/istio/appender/mesh_check_test.go
  graph/telemetry/istio/appender/outsider.go
  graph/telemetry/istio/appender/outsider_test.go
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/appender/security_policy.go
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/service_entry_test.go
  graph/telemetry/istio/appender/throughput.go
  graph/telemetry/istio/appender/traffic_generator.go
  graph/telemetry/istio/appender/workload_entry.go
  graph/telemetry/istio/appender/workload_entry_test.go
  graph/telemetry/istio/istio.go
  mesh/api/api.go
  mesh/api/api_test.go
  mesh/appender.go
  mesh/generator/generator.go
  util/sliceutil/slice.go
Labels: test: back-end/integration

#7755 [v1.65] Update serialize-javascript dependency
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7753 [v1.89] Update serialize-javascript dependency
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7756 Appender work related to waypoint service injection
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/appender/security_policy.go
  graph/telemetry/istio/appender/throughput.go
  graph/telemetry/istio/istio.go
Labels: test: n/a

#7656 Adapt cypress tests to OSSMC
  frontend/cypress/integration/common/app_details.ts
  frontend/cypress/integration/common/app_details_multicluster.ts
  frontend/cypress/integration/common/apps.ts
  frontend/cypress/integration/common/authorization.ts
  frontend/cypress/integration/common/graph_display.ts
  frontend/cypress/integration/common/graph_toolbar.ts
  frontend/cypress/integration/common/istio_config.ts
  frontend/cypress/integration/common/istio_config_editor.ts
  frontend/cypress/integration/common/kiali_cookie.ts
  frontend/cypress/integration/common/kiali_login.ts
  frontend/cypress/integration/common/kiali_logout.ts
  frontend/cypress/integration/common/mesh.ts
  frontend/cypress/integration/common/navigation.ts
  frontend/cypress/integration/common/overview.ts
  frontend/cypress/integration/common/sidecar_injection.ts
  frontend/cypress/integration/common/table.ts
  frontend/cypress/integration/common/wizard_request_routing.ts
  frontend/cypress/integration/common/workload_logs.ts
  frontend/cypress/integration/common/workloads.ts
  frontend/cypress/integration/common/workloads_details.ts
  frontend/cypress/integration/featureFiles/graph_replay.feature
  frontend/cypress/integration/featureFiles/mesh.feature
  frontend/cypress/integration/featureFiles/overview.feature
  frontend/cypress/integration/featureFiles/service_details.feature
  frontend/cypress/integration/featureFiles/sidecar_injection.feature
  frontend/cypress/integration/featureFiles/workload_logs.feature
  frontend/cypress/integration/featureFiles/workloads_details.feature
  frontend/cypress/perf/common.ts
  frontend/cypress/perf/graphload.spec.ts
  frontend/cypress/perf/overviewload.spec.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/tsconfig.json
Labels: test: front-end/cypress

#7719 [Ambient] Add rates in double waypoint edges
  frontend/src/assets/img/graph/pf/edge-danger.svg
  frontend/src/assets/img/graph/pf/edge-idle.svg
  frontend/src/assets/img/graph/pf/edge-success.svg
  frontend/src/assets/img/graph/pf/edge-tcp.svg
  frontend/src/assets/img/graph/pf/edge-warn.svg
  frontend/src/components/CytoscapeGraph/__tests__/GraphScore.test.ts
  frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts
  frontend/src/pages/Graph/SummaryPanelEdge.tsx
  frontend/src/pages/GraphPF/GraphPFElems.tsx
  frontend/src/store/Selectors/GraphData.ts
  frontend/src/types/Graph.ts
  graph/api/testdata/test_ambient_graph.expected
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/telemetry/istio/appender/ambient.go
  graph/telemetry/istio/istio.go
  graph/types.go
Labels: enhancement, ambient

#7763 [cypress] Add coverage for the summary panel when click on an edge in the graph
  frontend/cypress/integration/common/graph_side_panel.ts
  frontend/cypress/integration/featureFiles/graph_side_panel.feature
Labels: enhancement, test: front-end/cypress

#7759 rename in_cluster_url to internal_url; rename url to external_url
  business/istio_status.go
  business/istio_status_test.go
  config/config.go
  grafana/grafana.go
  grafana/grafana_test.go
  hack/istio/multicluster/deploy-kiali.sh
  hack/istio/sail/func-kiali.sh
  hack/istio/tempo/install-tempo-env.sh
  hack/run-kiali-config-template.yaml
  hack/setup-kind-in-ci.sh
  handlers/tracing.go
  mesh/api/testdata/test_mesh_graph.expected
  mesh/generator/generator.go
  status/versions.go
  tracing/client.go
Labels: requires operator PR

#7752 Show workload action list in kiosk mode
  frontend/cypress/integration/common/service_details.ts
  frontend/cypress/integration/common/sidecar_injection.ts
  frontend/cypress/integration/featureFiles/service_details.feature
  frontend/cypress/integration/featureFiles/sidecar_injection.feature
  frontend/package.json
  frontend/public/locales/zh/translation.json
  frontend/src/components/CytoscapeGraph/MiniGraphCard.tsx
  frontend/src/components/IstioWizards/ServiceWizardDropdown.tsx
  frontend/src/components/IstioWizards/WorkloadWizardActionsDropdownGroup.tsx
  frontend/src/components/IstioWizards/WorkloadWizardDropdown.tsx
  frontend/src/pages/Graph/GraphPage.tsx
  frontend/src/pages/GraphPF/GraphPagePF.tsx
  frontend/src/pages/GraphPF/MiniGraphCardPF.tsx
  frontend/src/pages/ServiceDetails/ServiceInfo.tsx
  frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  frontend/src/pages/WorkloadDetails/WorkloadInfo.tsx
Labels: test: front-end/cypress

#7771 Mesh page: do not show namespaces that fail to match any discovery selector
  istio/discovery.go
Labels: test: n/a

#7766 [ambient] Updated styles for waypoint edges summary panel
  frontend/src/config/Icons.ts
  frontend/src/pages/Graph/GraphToolbar/GraphSettings.tsx
  frontend/src/pages/Graph/SummaryLink.tsx
  frontend/src/pages/Graph/SummaryPanelEdge.tsx
  frontend/src/pages/GraphPF/GraphPFElems.tsx
Labels: enhancement, ambient

#7767 [ambient] Add to the Graph Traffic Dropdown
  config/config.go
  frontend/cypress/integration/common/graph_toolbar.ts
  frontend/cypress/integration/featureFiles/graph_toolbar.feature
  frontend/src/app/AuthenticationController.tsx
  frontend/src/config/ServerConfig.ts
  frontend/src/pages/Graph/GraphToolbar/GraphTraffic.tsx
  frontend/src/reducers/GraphDataState.ts
  frontend/src/services/GraphDataSource.ts
  frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
  frontend/src/types/Graph.ts
  frontend/src/types/ServerConfig.ts
  frontend/src/types/__testData__/HealthConfig.ts
  graph/options.go
  graph/telemetry/istio/appender/aggregate_node.go
  graph/telemetry/istio/appender/aggregate_node_test.go
  graph/telemetry/istio/appender/ambient.go
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/appender/response_time_test.go
  graph/telemetry/istio/appender/security_policy.go
  graph/telemetry/istio/appender/security_policy_test.go
  graph/telemetry/istio/appender/throughput.go
  graph/telemetry/istio/appender/throughput_test.go
  graph/telemetry/istio/istio.go
  graph/telemetry/istio/util/util.go
Labels: test: front-end/cypress, test: back-end/integration

#7768 Update tempo resources for Sail hack script
  hack/istio/sail/README-RELEASE.md
  hack/istio/sail/func-tempo.sh
Labels: enhancement

#7486 Kiali extension support
  business/services.go
  business/services_test.go
  config/config.go
  design/KEPS/extensions/proposal.md
  frontend/public/locales/zh/translation.json
  frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts
  frontend/src/components/Pf/PfBadges.tsx
  frontend/src/pages/Graph/SummaryLink.tsx
  frontend/src/pages/GraphPF/GraphPFElems.tsx
  frontend/src/store/Selectors/GraphData.ts
  frontend/src/types/Graph.ts
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/extensions.go
  graph/telemetry/istio/appender/extensions_test.go
  graph/telemetry/istio/istio.go
  graph/types.go
  hack/istio/skupper/demo-emit-metrics-deployment/k8s.yaml
  hack/istio/skupper/install-skupper-demo.sh
Labels: requires operator PR
