Repository kiali/kiali, pull requests merged in 2024-12, with the labels that each got.

#7854 [Tempo] Add Tempo cache
  config/config.go
  mesh/api/testdata/test_mesh_graph.expected
  prometheus/internalmetrics/internal_metrics.go
  store/fifo_store.go
  store/fifo_store_test.go
  tracing/client.go
  tracing/tempo/http_client.go
  tracing/tempo/http_client_test.go
Labels: enhancement, requires docs PR, requires operator PR

#7974 Add ability to specify custom CA to Openshift Auth
  business/openshift_oauth.go
  business/openshift_oauth_internal_test.go
  business/openshift_oauth_test.go
  handlers/authentication/openshift_auth_controller.go
Labels: requires docs PR, requires operator PR

#7972 Convert AuthorizationPolicyForm into React hook
  frontend/public/locales/zh/translation.json
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm.tsx
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/From/SourceBuilder.tsx
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/From/SourceList.tsx
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleBuilder.tsx
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleList.tsx
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/To/OperationBuilder.tsx
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/To/OperationList.tsx
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/When/ConditionBuilder.tsx
  frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/When/ConditionList.tsx
  frontend/src/pages/IstioConfigNew/IstioConfigNewPage.tsx
Labels: test: n/a

#7965 added tag for kiali tests
  frontend/reporter-config.json
Labels: test: front-end/cypress

#7828 Refactor: Change FormSelect to Select from @patternfly/react-core
  frontend/src/components/IstioWizards/K8sGRPCRouteHosts.tsx
  frontend/src/components/IstioWizards/K8sGatewaySelector.tsx
  frontend/src/components/IstioWizards/K8sRouteHosts.tsx
  frontend/src/components/IstioWizards/ServiceWizard.tsx
Labels: test: n/a

#7955 [graph] add traffic-point animation
  config/config.go
  frontend/src/config/ServerConfig.ts
  frontend/src/pages/GraphPF/GraphPF.tsx
  frontend/src/pages/GraphPF/GraphPFElems.tsx
  frontend/src/pages/GraphPF/TrafficAnimation/AnimationEdge.tsx
  frontend/src/pages/GraphPF/TrafficAnimation/AnimationTimerConfig.ts
  frontend/src/pages/GraphPF/TrafficAnimation/TrafficPointRendererPF.tsx
  frontend/src/pages/GraphPF/TrafficAnimation/TrafficRendererPF.tsx
  frontend/src/pages/GraphPF/elements/extendedBaseEdge.ts
  frontend/src/pages/GraphPF/styles/styleEdge.tsx
  frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
  frontend/src/types/ServerConfig.ts
  frontend/src/types/__testData__/HealthConfig.ts
Labels: requires operator PR

#7981 [security] update path-to-regexp
  frontend/yarn.lock
Labels: backport needed, test: n/a

#7983 [security] update nanoid
  frontend/yarn.lock
Labels: backport needed, test: n/a

#7984 [V1.73] update path-to-regexp
  frontend/yarn.lock
Labels: test: n/a

#7985 [V1.73] update nanoid
  frontend/yarn.lock
Labels: test: n/a

#7982 [graph] fix traffic animation with very small error rates
  frontend/src/pages/GraphPF/TrafficAnimation/TrafficRendererPF.tsx
Labels: test: n/a

#7992 [ambient] handle gateway-to-ambient traffic in the graph
  graph/api/api_test.go
  graph/options.go
  graph/telemetry/istio/appender/aggregate_node.go
  graph/telemetry/istio/appender/response_time.go
  graph/telemetry/istio/appender/response_time_test.go
  graph/telemetry/istio/istio.go
  graph/telemetry/istio/util/util.go
  graph/types.go
Labels: test: back-end/integration

#7995 Add a bigger timeout for tracing/spans and istioApi queries in integration tests
  tests/integration/utils/kiali/kiali_client.go
Labels: test: back-end/integration

#8002 Bump istio version for sail hack script
  hack/istio/install-istio-via-sail.sh
Labels: bug

#7991 Handle URL in kiosk for time duration modal
  frontend/src/components/Time/TimeDurationModal.tsx
Labels: bug

#8018 Avoid duplicated tarballs
  frontend/yarn.lock
Labels: test: n/a

#8019 [v2.3] Avoid duplicated tarballs (#8018)
  frontend/yarn.lock
Labels: test: n/a

#8020 Update service with no traces
  frontend/cypress/integration/featureFiles/service_details_multicluster.feature
Labels: test: front-end/cypress

#8028 Keycloak tmp fix
  hack/keycloak.sh
Labels: bug
