Repository kiali/kiali, pull requests merged in 2024-11, with the labels that each got.

#7879 Handle Security appender Ambient corner case
  frontend/src/config/ServerConfig.ts
  graph/telemetry/istio/appender/security_policy.go
  graph/telemetry/istio/appender/security_policy_test.go
Labels: test: back-end/integration

#7885 Fix orphan edge hide issue in graph and mesh page
  frontend/src/pages/Graph/GraphToolbar/GraphFindPF.tsx
  frontend/src/pages/Mesh/toolbar/MeshFind.tsx
Labels: test: n/a

#7890 Convert infraData type from unknown to any
  frontend/src/types/Mesh.ts
Labels: test: n/a

#7888 [mesh page] Always show yaml format config in the Mesh side panels
  frontend/public/locales/zh/translation.json
  frontend/src/pages/Mesh/target/TargetPanelConfigTable.tsx
  frontend/src/pages/Mesh/target/TargetPanelControlPlane.tsx
  frontend/src/pages/Mesh/target/TargetPanelDataPlaneNamespace.tsx
  frontend/src/pages/Mesh/target/TargetPanelEditor.tsx
  frontend/src/pages/Mesh/target/TargetPanelNode.tsx
Labels: test: n/a

#7887 [Ambient] get reporter for tcp telemetry
  graph/api/api_test.go
  graph/telemetry/istio/appender/security_policy.go
  graph/telemetry/istio/appender/security_policy_test.go
  graph/telemetry/istio/istio.go
Labels: bug, ambient

#7908 [CI] Fix cypress test failures with Istio 1.24
  frontend/cypress/integration/common/workload_logs.ts
  frontend/cypress/integration/featureFiles/traffic_policies_multicluster.feature
  frontend/cypress/integration/featureFiles/waypoint.feature
  frontend/cypress/integration/featureFiles/wizard_istio_config_multicluster.feature
  frontend/cypress/integration/featureFiles/wizard_request_routing.feature
  frontend/cypress/integration/featureFiles/workload_logs.feature
Labels: bug, test: front-end/cypress

#7910 Update cross-spawn dependency
  frontend/package.json
  frontend/yarn.lock
Labels: backport needed, test: n/a

#7912 [v1.73] Update cross-spawn dependency
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7913 [v1.65] Update cross-spawn dependency
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7891 [Tempo] Don't split calls to backend
  business/tracing.go
  frontend/src/components/TracingIntegration/TracesComponent.tsx
  frontend/src/components/TracingIntegration/TracesFetcher.ts
  hack/istio/tempo/install-tempo-env.sh
Labels: enhancement

#7916 [1.89] Fix CI failures with Istio 1.24
  frontend/cypress/integration/common/workload_logs.ts
  frontend/cypress/integration/featureFiles/traffic_policies_multicluster.feature
  frontend/cypress/integration/featureFiles/wizard_istio_config_multicluster.feature
  frontend/cypress/integration/featureFiles/wizard_request_routing.feature
  frontend/cypress/integration/featureFiles/workload_logs.feature
Labels: bug, test: front-end/cypress

#7920 [Tempo] Add helm installation method to hack script
  hack/istio/tempo/helm.yaml
  hack/istio/tempo/install-tempo-env.sh
Labels: enhancement

#7923 Allow setting trace limit in graph node-side-panel Trace tab
  frontend/src/components/Metrics/TraceLimit.tsx
  frontend/src/pages/Graph/SummaryPanelNodeTraces.tsx
Labels: test: n/a

#7911 [v1.89] Update cross-spawn dependency
  frontend/yarn.lock
Labels: test: n/a

#7936 When performing a layout, reset the graph by default.
  frontend/src/pages/GraphPF/GraphPF.tsx
  frontend/src/pages/Mesh/Mesh.tsx
Labels: test: n/a

#7931 [pft graph] Selection based zoom
  frontend/cypress/integration/common/table.ts
  frontend/package.json
  frontend/public/locales/zh/translation.json
  frontend/src/pages/Graph/GraphToolbar/GraphShortcutsPF.tsx
  frontend/src/pages/GraphPF/GraphPF.tsx
  frontend/src/pages/GraphPF/GraphPFElems.tsx
  frontend/src/pages/GraphPF/components/stylesComponentFactory.tsx
  frontend/src/pages/GraphPF/styles/styleNode.tsx
  frontend/src/pages/Mesh/Mesh.tsx
  frontend/src/pages/Mesh/MeshElems.tsx
  frontend/src/pages/Mesh/components/meshComponentFactory.tsx
  frontend/src/pages/Mesh/styles/MeshGroup.tsx
  frontend/src/pages/Mesh/styles/MeshNode.tsx
  frontend/src/pages/Mesh/toolbar/MeshShortcuts.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/yarn.lock
Labels: test: n/a

#7947 [v1.73] Update postcss dependency
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7938 Use the same kind node image criteria for all hack scripts
  hack/istio/multicluster/env.sh
  hack/istio/multicluster/install-multi-primary.sh
  hack/istio/multicluster/install-primary-remote.sh
  hack/istio/multicluster/setup-external-controlplane.sh
  hack/setup-kind-in-ci.sh
  hack/start-kind.sh
Labels: test: n/a

#7953 Adapt some cypress tests to OSSMC
  frontend/cypress/integration/common/apps.ts
  frontend/cypress/integration/common/workload_logs.ts
  frontend/src/components/Time/TimeDurationIndicator.tsx
  frontend/src/components/Time/TimeDurationModal.tsx
  frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx
Labels: test: front-end/cypress

#7962 Fixed missing GVK String.
  business/istio_validations.go
Labels: backport needed

#7939 fix: Update hasIstioContainers predicate for correct work with native…
  frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Labels: test: n/a

#7961 [graph] more tweaks to layout/reset
  frontend/package.json
  frontend/src/pages/GraphPF/GraphPF.tsx
  frontend/src/pages/Mesh/Mesh.tsx
  frontend/yarn.lock
Labels: test: n/a
