Repository kiali/kiali, pull requests merged in 2024-01, with the labels that each got.

#6983 Consider ReferenceGrant in HTTPRoute Service validation KIA1402
  business/checkers/k8shttproute_checker.go
  business/checkers/k8shttproutes/no_host_checker.go
  business/checkers/k8shttproutes/no_host_checker_test.go
  business/istio_validations.go
  kubernetes/host.go
  tests/data/k8sgateway_data.go
Labels: docs

#6938 [OSSM-5306][OSSM-5307] Add building tests images workflow into pipeline
  .github/workflows/test-images-creator.yml
  .github/workflows/test-images-release.yml
  .github/workflows/test-images-update-latest.yml
  Makefile
  make/Makefile.container.mk
Labels: github_actions

#7012 Added new check KIA1601 for ReferenceGrant
  business/checkers/k8sreferencegrants/namespace_checker.go
  business/checkers/k8sreferencegrants/namespace_checker_test.go
  business/checkers/k8sreferencegrants_checker.go
  business/checkers/k8sreferencegrants_checker_test.go
  business/istio_validations.go
  models/istio_validation.go
  tests/integration/assets/bookinfo-k8sreferencegrants-from-namespaces.yaml
  tests/integration/tests/config_validations_test.go
Labels: docs

#6991 Remove Jaeger Exporter
  config/config.go
  observability/tracing.go
  observability/tracing_test.go
  server/server_test.go
Labels: enhancement, docs, requires operator PR

#7016 K8sReferenceGrant: new Istio config creation wizard item
  business/istio_config.go
  frontend/cypress/integration/common/wizard_istio_config.ts
  frontend/cypress/integration/featureFiles/wizard_istio_config.feature
  frontend/src/components/IstioConfigPreview/IstioConfigPreview.tsx
  frontend/src/components/IstioWizards/WizardActions.ts
  frontend/src/pages/IstioConfigNew/IstioConfigNewPage.tsx
  frontend/src/pages/IstioConfigNew/K8sReferenceGrantForm.tsx
Labels: test-add-coverage :paperclip:

#7015 Hide waypoint proxies from Graph
  frontend/src/actions/ActionKeys.ts
  frontend/src/actions/GraphToolbarActions.ts
  frontend/src/app/History.ts
  frontend/src/components/CytoscapeGraph/MiniGraphCard.tsx
  frontend/src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  frontend/src/components/Nav/NavUtils.tsx
  frontend/src/pages/Graph/GraphPage.tsx
  frontend/src/pages/Graph/GraphToolbar/GraphSettings.tsx
  frontend/src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  frontend/src/pages/GraphPF/GraphPagePF.tsx
  frontend/src/pages/GraphPF/MiniGraphCardPF.tsx
  frontend/src/pages/GraphPF/components/stylesComponentFactory.tsx
  frontend/src/reducers/GraphDataState.ts
  frontend/src/reducers/__tests__/GraphDataState.test.ts
  frontend/src/services/GraphDataSource.ts
  frontend/src/services/__tests__/GraphDataSource.test.ts
  frontend/src/store/Selectors.ts
  frontend/src/store/Store.ts
  frontend/src/types/Graph.ts
  graph/telemetry/istio/appender/ambient.go
  graph/telemetry/istio/appender/ambient_test.go
  graph/telemetry/istio/appender/appender.go
  graph/telemetry/istio/appender/workload_entry_test.go
Labels: enhancement, ambient

#7038 Fix nil error in OCP
  kubernetes/cache/kube_cache.go
Labels: blocker

#7026 Hide application link for waypoint in graph
  frontend/src/components/DetailDescription/DetailDescription.tsx
  frontend/src/components/Pf/PfBadges.tsx
  frontend/src/pages/Graph/SummaryPanelNode.tsx
  frontend/src/types/Graph.ts
  graph/config/cytoscape/cytoscape.go
  graph/meta.go
  graph/telemetry/istio/appender/ambient.go
  graph/telemetry/istio/appender/ambient_test.go
  graph/telemetry/istio/appender/mesh_check.go
Labels: bug

#7069 Upgrade download and upload github actions to v4
  .github/workflows/build-backend.yml
  .github/workflows/build-frontend.yml
  .github/workflows/integration-tests-backend.yml
  .github/workflows/integration-tests-frontend-multicluster-multi-primary.yml
  .github/workflows/integration-tests-frontend-multicluster-primary-remote.yml
  .github/workflows/integration-tests-frontend-tempo.yml
  .github/workflows/integration-tests-frontend.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: dependencies, github_actions
