Repository kiali/kiali, pull requests merged in 2024-04, with the labels that each got.

#7224 Adapt Kiali code to make OSSMC compatible with OCP 4.15
  frontend/src/components/IstioActions/IstioActionsNamespaceDropdown.tsx
  frontend/src/components/Metrics/CustomMetrics.tsx
  frontend/src/components/Metrics/IstioMetrics.tsx
  frontend/src/components/Nav/Page/RenderComponentScroll.tsx
  frontend/src/pages/Graph/GraphLegend.tsx
  frontend/src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  frontend/src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  frontend/src/pages/GraphPF/GraphHighlighterPF.ts
  frontend/src/pages/GraphPF/GraphLegendPF.tsx
  frontend/src/pages/GraphPF/components/stylesComponentFactory.tsx
  frontend/src/pages/GraphPF/styles/styleEdge.tsx
  frontend/src/pages/GraphPF/styles/styleGroup.tsx
  frontend/src/pages/GraphPF/styles/styleNode.tsx
  frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  frontend/src/pages/IstioConfigNew/IstioConfigNewPage.tsx
  frontend/src/pages/Mesh/MeshHighlighter.ts
  frontend/src/pages/Mesh/MeshLegend.tsx
  frontend/src/pages/Mesh/styles/MeshEdge.tsx
  frontend/src/pages/Mesh/styles/MeshGroup.tsx
  frontend/src/pages/Mesh/styles/MeshNode.tsx
  frontend/src/pages/Mesh/toolbar/__tests__/__snapshots__/MeshLegend.test.tsx.snap
  frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx
  frontend/src/services/Api.ts
Labels: test: n/a

#7245 Script for perf tests run and test data creation
  frontend/cypress/fixtures/perf/baselines.json
  frontend/cypress/fixtures/perf/commonParams.json
  frontend/cypress/perf/overviewload.spec.ts
  hack/run-performance-tests.sh
Labels: test: n/a

#7229 Service list backend request per cluster
  business/services.go
  business/services_test.go
  frontend/cypress/integration/common/graph_side_panel.ts
  frontend/src/config/Config.ts
  frontend/src/pages/ServiceList/ServiceListPage.tsx
  frontend/src/services/Api.ts
  frontend/src/services/__tests__/ApiMethods.test.ts
  frontend/src/types/ServiceList.ts
  graph/telemetry/istio/appender/istio_details.go
  handlers/services.go
  models/service.go
  routing/routes.go
  tests/integration/tests/no_istiod_test.go
  tests/integration/tests/services_test.go
  tests/integration/utils/kiali/kiali_client.go
Labels: test: back-end/integration

#7253 Update Content-Type for login request
  frontend/cypress/integration/common/kiali_login.ts
  frontend/cypress/integration/featureFiles/kiali_login.feature
  frontend/src/services/Api.ts
Labels: bug, backport needed, test-add-coverage :paperclip:

#7257 [v1.73] Update Content-Type for login request
  frontend/cypress/integration/common/kiali_login.ts
  frontend/cypress/integration/featureFiles/kiali_login.feature
  frontend/src/services/Api.ts
Labels: bug

#7250 Adjust flex css value in overview page for OSSMC
  frontend/src/pages/Overview/OverviewPage.tsx
Labels: test: n/a

#7264 Update also content type for OpenShift login request
  frontend/src/services/Api.ts
Labels: bug, backport needed

#7248 Use latest v2 of go-jose
  business/authentication/openid_auth_controller.go
  business/authentication/openid_auth_controller_test.go
  business/authentication/token_auth_controller.go
  go.mod
  go.sum
  kubernetes/kubetest/mock.go
Labels: backport needed, backport completed

#7270 Refactor globals out of auth controllers
  business/authentication/auth_controller.go
  business/authentication/header_auth_controller.go
  business/authentication/openid_auth_controller.go
  business/authentication/openid_auth_controller_test.go
  business/authentication/openshift_auth_controller.go
  business/authentication/session_persistor.go
  business/authentication/session_persistor_test.go
  business/authentication/signing_key.go
  business/authentication/token_auth_controller.go
  business/authentication/token_auth_controller_test.go
  business/layer.go
  business/namespaces.go
  business/namespaces_test.go
  business/openshift_oauth.go
  business/tokenreview.go
  config/config.go
  config/token.go
  handlers/authentication.go
  handlers/authentication_test.go
  kiali.go
  kubernetes/kubetest/fake.go
  routing/router.go
  routing/router_test.go
  routing/routes.go
  util/httputil/http_util.go
  util/httputil/http_util_test.go
Labels: do not merge

#7283 Fix sleep yaml for s390x
  hack/istio/install-sleep-demo.sh
Labels: backport needed

#7280 Implement auth code flow for openshift login
  business/authentication/openshift_auth_controller.go
  business/authentication/openshift_auth_controller_test.go
  business/authentication/token_auth_controller.go
  business/layer.go
  business/namespaces.go
  business/openshift_oauth.go
  business/openshift_oauth_test.go
  business/workloads.go
  config/config.go
  frontend/cypress.config.ts
  frontend/cypress/README.md
  frontend/cypress/integration/common/kiali_cookie.ts
  frontend/cypress/integration/common/kiali_login.ts
  frontend/cypress/integration/featureFiles/kiali_login.feature
  frontend/cypress/plugins/setup.ts
  frontend/cypress/support/commands.ts
  frontend/src/app/AuthenticationController.tsx
  frontend/src/pages/Login/LoginPage.tsx
  frontend/src/pages/Login/__tests__/LoginPage.test.tsx
  go.mod
  go.sum
  hack/istio/multicluster/setup-tracing.sh
  hack/run-molecule-tests.sh
  handlers/authentication.go
  handlers/authentication_test.go
  handlers/testing.go
  kiali.go
  kubernetes/client.go
  kubernetes/client_factory.go
  kubernetes/client_factory_test.go
  kubernetes/kubernetes.go
  kubernetes/kubetest/fake.go
  kubernetes/kubetest/mock.go
  kubernetes/kubetest/mock_openshift.go
  routing/router.go
  routing/router_test.go
  server/server.go
  server/server_test.go
  status/discover.go
Labels: requires operator PR, requires helm chart PR

#7296 Fixed validations for details, load configs for all namespaces
  business/checkers/virtualservices/no_gateway_checker_test.go
  business/istio_validations.go
  frontend/cypress/integration/featureFiles/istio_config.feature
Labels: test: front-end/cypress, test: back-end/integration

#7300 Don't use kiali login headers with api proxy (OSSMC)
  frontend/src/services/Api.ts
Labels: test: n/a

#7258 New KIA0107 for ServiceAccounts on remote cluster
  business/checkers/authorization/principals_checker.go
  business/checkers/authorization/principals_checker_test.go
  business/checkers/authorization_policies_checker.go
  business/istio_validations.go
  models/istio_validation.go
Labels: docs, backport needed, test: back-end/integration

#7308 Show the health status of mesh infra nodes
  business/controlplane_monitor.go
  business/istio_status.go
  business/istio_status_test.go
  frontend/public/locales/zh/translation.json
  frontend/src/components/IstioStatus/IstioComponentStatus.tsx
  frontend/src/components/IstioStatus/IstioStatus.tsx
  frontend/src/components/IstioStatus/IstioStatusList.tsx
  frontend/src/components/IstioStatus/__tests__/IstioStatus.test.tsx
  frontend/src/components/IstioStatus/__tests__/__snapshots__/IstioComponentStatus.test.tsx.snap
  frontend/src/components/IstioStatus/__tests__/__snapshots__/IstioStatus.test.tsx.snap
  frontend/src/pages/Mesh/Mesh.tsx
  frontend/src/pages/Mesh/MeshElems.tsx
  frontend/src/pages/Mesh/target/TargetPanelCommon.tsx
  frontend/src/pages/Mesh/target/TargetPanelControlPlane.tsx
  frontend/src/pages/Mesh/target/TargetPanelNode.tsx
  frontend/src/store/Selectors/MeshData.ts
  frontend/src/types/IstioStatus.ts
  mesh/api/api.go
  mesh/api/api_test.go
  mesh/api/testdata/test_mesh_graph.expected
  mesh/appender.go
  mesh/generator/generator.go
  mesh/util.go
Labels: test: front-end/cypress, test: back-end/integration
