Repository kiali/kiali, pull requests merged in 2024-08, with the labels that each got.

#7579 Update frontend dev dependencies
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7582 [v1.73] Update frontend dev dependencies
  frontend/yarn.lock
Labels: test: n/a

#7585 [v1.65] Update frontend dev dependencies
  frontend/yarn.lock
Labels: test: n/a

#7580 Move to go 1.22.5
  go.mod
Labels: backport needed

#7586 [v1.57] Update frontend dev dependencies
  frontend/yarn.lock
  hack/setup-kind-in-ci.sh
  hack/start-kind.sh
Labels: test: n/a

#7575 Add badge icon to waypoints
  frontend/src/assets/img/graph/node-badge-waypoint.svg
  frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts
  frontend/src/config/Icons.ts
  frontend/src/pages/Graph/GraphLegend.tsx
  frontend/src/pages/Graph/GraphLegendData.ts
  frontend/src/pages/GraphPF/GraphLegendDataPF.ts
  frontend/src/pages/GraphPF/GraphLegendPF.tsx
  frontend/src/pages/GraphPF/GraphPFElems.tsx
Labels: enhancement, ambient

#7597 Update translations
  frontend/public/locales/zh/translation.json
Labels: enhancement

#7602 [v1.86] Update frontend dev dependencies
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7568 Add CSRF token to OSSMC non-GET request header
  frontend/src/services/Api.ts
  frontend/src/types/Auth.ts
Labels: backport needed, test: n/a

#7601 Verify uncommitted new i18n statements
  hack/hooks/pre-commit.sh
Labels: test: n/a

#7606 [v1.86] Implement notification list with AlertGroup PF component (#7554)
  frontend/src/components/MessageCenter/AlertToast.tsx
  frontend/src/components/MessageCenter/NotificationList.tsx
Labels: test: n/a

#7605 [v1.73] Add CSRF token to OSSMC non-GET request header
  frontend/src/services/Api.ts
  frontend/src/types/Auth.ts
Labels: test: n/a

#7607 [v1.73] Implement notification list with AlertGroup PF component (#7554)
  frontend/src/components/MessageCenter/AlertToast.tsx
  frontend/src/components/MessageCenter/NotificationList.tsx
Labels: test: n/a

#7511 [v1.73] Stringify the query data only if it is not already stringified (#7498)
  frontend/src/services/Api.ts
Labels: test: n/a

#7519 Upgrade Node to version 20
  .github/workflows/build-frontend.yml
  .github/workflows/integration-tests-frontend-ambient.yml
  .github/workflows/integration-tests-frontend-multicluster-multi-primary.yml
  .github/workflows/integration-tests-frontend-multicluster-primary-remote.yml
  .github/workflows/integration-tests-frontend-tempo.yml
  .github/workflows/integration-tests-frontend.yml
  README.adoc
  frontend/package.json
  frontend/yarn.lock
Labels: backport needed, test: n/a

#7609 Update cypress/base docker image to Node 20
  deploy/docker/Dockerfile-cypress
Labels: test: n/a

#7610 [v1.86] Upgrade Node to version 20
  .github/workflows/build-frontend.yml
  .github/workflows/integration-tests-frontend-ambient.yml
  .github/workflows/integration-tests-frontend-multicluster-multi-primary.yml
  .github/workflows/integration-tests-frontend-multicluster-primary-remote.yml
  .github/workflows/integration-tests-frontend-tempo.yml
  .github/workflows/integration-tests-frontend.yml
  README.adoc
  deploy/docker/Dockerfile-cypress
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7611 [v1.73] Upgrade Node to version 20
  .github/workflows/build-backend.yml
  .github/workflows/build-frontend.yml
  .github/workflows/integration-tests-backend.yml
  .github/workflows/integration-tests-frontend-multicluster.yml
  .github/workflows/integration-tests-frontend.yml
  .github/workflows/molecules.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/tag-creator.yml
  .github/workflows/test-images-update-latest.yml
  .github/workflows/version-checker.yml
  deploy/docker/Dockerfile-cypress
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7612 [v1.65] Upgrade Node to version 20
  .github/workflows/build-backend.yml
  .github/workflows/build-frontend.yml
  .github/workflows/integration-tests-backend.yml
  .github/workflows/integration-tests-frontend.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/tag-creator.yml
  .github/workflows/test-images-update-latest.yml
  .github/workflows/version-checker.yml
  README.adoc
  deploy/docker/Dockerfile-cypress
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#7567 Display full yaml from istio configmap
  frontend/src/components/Mesh/ConfigButtonsTargetPanel.tsx
  frontend/src/pages/Mesh/target/TargetPanelConfigTable.tsx
  frontend/src/pages/Mesh/target/TargetPanelControlPlane.tsx
  frontend/src/pages/Mesh/target/TargetPanelEditor.tsx
  istio/discovery.go
  mesh/api/testdata/test_mesh_graph.expected
  models/mesh.go
Labels: enhancement

#7616 Upgrade CRC to version 4.16
  hack/crc-openshift.sh
Labels: test: n/a

#7608 Include namespace in service versions yaml from Ambient hack bookinfo script
  hack/istio/install-bookinfo-demo.sh
Labels: enhancement, ambient

#7641 Update axios 1.7.4
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies, backport needed

#7643 [v1.86] Update axios version
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#7644 [v1.73] Update axios version
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#7648 [v1.89] Update axios version
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#7620 Update cypress tests
  frontend/cypress/integration/common/authorization.ts
  frontend/cypress/integration/common/navigation.ts
  frontend/cypress/integration/featureFiles/authorization.feature
Labels: enhancement, test: front-end/cypress

#7647 [v1.65] Update axios version
  frontend/package.json
  frontend/src/actions/JaegerThunkActions.ts
  frontend/src/actions/LoginThunkActions.ts
  frontend/src/app/StartupInitializer.tsx
  frontend/src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
  frontend/src/components/Details/__tests__/DetailObject.test.tsx
  frontend/src/components/Details/__tests__/__snapshots__/DetailObject.test.tsx.snap
  frontend/src/components/FilterList/FilterComponent.tsx
  frontend/src/components/IstioConfigPreview/EditorPreview.tsx
  frontend/src/components/Kiosk/KioskActions.ts
  frontend/src/components/Metrics/IstioMetrics.tsx
  frontend/src/hooks/services.ts
  frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  frontend/src/pages/Mesh/MeshPage.tsx
  frontend/src/pages/Overview/OverviewPage.tsx
  frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx
  frontend/src/services/Api.ts
  frontend/src/services/__tests__/ApiMethods.test.tsx.ts
  frontend/src/store/Selectors/GraphData.ts
  frontend/src/types/AceValidations.ts
  frontend/src/types/Api.ts
  frontend/src/utils/AlertUtils.ts
  frontend/yarn.lock
Labels: dependencies

#7596 Include url parameters on router basename redirect
  frontend/src/index.tsx
Labels: test: front-end/cypress

#7615 Remove unsupported Kiali versions from tag creator workflow
  .github/workflows/tag-creator.yml
Labels: test: n/a

#7633 [Ambient] Update bookinfo script for Istio 1.23 and waypoints
  hack/istio/functions.sh
  hack/istio/install-bookinfo-demo.sh
  hack/istio/install-travel-agency-demo.sh
Labels: enhancement, ambient, test: n/a

#7667 Update deprecate options in github golang workflow
  .github/workflows/config/.golangci.yml
Labels: github_actions, test: n/a

#7662 [Tempo] Query scope fix
  business/tracing.go
  hack/istio/multicluster/deploy-kiali.sh
  hack/istio/multicluster/env.sh
  hack/istio/multicluster/install-primary-remote.sh
  hack/run-integration-tests.sh
  hack/setup-kind-in-ci.sh
  tracing/tempo/http_client.go
Labels: bug

#7673 Fix multicluster service entry scenario
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/service_entry_test.go
Labels: test: back-end/integration

#7670 [Tempo] Modify setup tracing script for Tempo multicluster
  hack/istio/multicluster/setup-tracing.sh
Labels: enhancement, multicluster

#7680 [v1.89] Update webpack to version 5.94.0
  frontend/yarn.lock
Labels: test: n/a

#7681 [v1.73] Update webpack to version 5.94
  frontend/yarn.lock
Labels: test: n/a

#7684 [v1.89] Fix multicluster service entry scenario
  graph/telemetry/istio/appender/service_entry.go
  graph/telemetry/istio/appender/service_entry_test.go
Labels: test: back-end/integration

#7592 accessible namespaces to discovery selectors refactoring
  Makefile
  business/apps_test.go
  business/controlplane_monitor_test.go
  business/discovery_selectors.go
  business/discovery_selectors_test.go
  business/health_test.go
  business/istio_certs_test.go
  business/istio_config_test.go
  business/istio_validations_test.go
  business/mesh_test.go
  business/namespaces.go
  business/namespaces_test.go
  business/services_test.go
  business/tls_test.go
  business/workloads_test.go
  config/config.go
  config/config_test.go
  design/KEPS/namespace-discovery/proposal.md
  frontend/src/components/DebugInformation/DebugInformation.tsx
  frontend/src/config/ServerConfig.ts
  frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
  frontend/src/types/ServerConfig.ts
  frontend/src/types/__testData__/HealthConfig.ts
  graph/api/api_test.go
  graph/telemetry/istio/appender/ambient_test.go
  graph/telemetry/istio/appender/dead_node_test.go
  graph/telemetry/istio/appender/health_test.go
  graph/telemetry/istio/appender/istio_details_test.go
  graph/telemetry/istio/appender/labeler_test.go
  graph/telemetry/istio/appender/mesh_check_test.go
  graph/telemetry/istio/appender/service_entry_test.go
  graph/telemetry/istio/appender/workload_entry_test.go
  hack/istio/multicluster/kiali-prepare-remote-cluster.sh
  hack/run-kiali-config-template.yaml
  handlers/apps_test.go
  handlers/authentication/openid_auth_controller_test.go
  handlers/authentication/token_auth_controller_test.go
  handlers/config.go
  handlers/mesh_test.go
  handlers/namespaces_test.go
  handlers/services_test.go
  handlers/utils_test.go
  handlers/workloads_test.go
  istio/discovery_internal_test.go
  istio/discovery_test.go
  istio/version_test.go
  kubernetes/cache/cache.go
  kubernetes/cache/cache_test.go
  kubernetes/cache/kube_cache.go
  kubernetes/cache/kube_cache_test.go
  kubernetes/cache/once_wrapper.go
  kubernetes/cache/once_wrapper_test.go
  kubernetes/istio_test.go
  kubernetes/kubetest/mock.go
  make/Makefile.operator.mk
  mesh/api/api_test.go
  mesh/api/testdata/test_mesh_graph.expected
  models/mesh.go
  tests/testutils/prepare_config.go
Labels: docs, requires operator PR, requires helm chart PR

#7691 exclude system namespaces if no discovery selectors were defined
  business/discovery_selectors.go
  business/discovery_selectors_test.go
Labels: requires operator PR
