Repository kiali/kiali, pull requests merged in 2025-07, with the labels that each got.

#8542 Unify the format of the configs in the Mesh page
  config/config.go
  frontend/cypress/integration/common/mesh.ts
  frontend/cypress/integration/featureFiles/mesh.feature
  frontend/src/components/IstioStatus/IstioComponentStatus.tsx
  frontend/src/components/IstioStatus/IstioStatus.tsx
  frontend/src/components/IstioStatus/IstioStatusList.tsx
  frontend/src/components/IstioStatus/__tests__/IstioComponentStatus.test.tsx
  frontend/src/components/IstioStatus/__tests__/IstioStatus.test.tsx
  frontend/src/components/IstioStatus/__tests__/IstioStatusList.test.tsx
  frontend/src/components/IstioStatus/__tests__/__snapshots__/IstioStatus.test.tsx.snap
  frontend/src/components/IstioStatus/__tests__/__snapshots__/IstioStatusList.test.tsx.snap
  frontend/src/components/Mesh/TraceConfigurationModal.tsx
  frontend/src/types/IstioStatus.ts
  frontend/src/types/StatusState.ts
  frontend/src/utils/tracing/UrlProviders/Tempo.ts
  frontend/src/utils/tracing/UrlProviders/index.ts
  kubernetes/istio.go
  mesh/api/testdata/test_mesh_graph.expected
Labels: enhancement

#8550 Update Istio metrics
  business/metrics.go
Labels: enhancement

#8589 Upgrade form-data frontend dependency
  frontend/package.json
  frontend/yarn.lock
Labels: backport needed, test: n/a

#8598 [v2.4] Upgrade axios and form-data dependencies (#8589)
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a

#8597 [v2.11] Upgrade axios and form-data dependencies (#8589)
  frontend/package.json
  frontend/yarn.lock
Labels: test: n/a
