Repository kiali/kiali, pull requests merged in 2025-08, with the labels that each got.

#8591 Autodetect the istiod monitoring port
  business/controlplane_monitor.go
  config/config.go
  istio/constants.go
  istio/discovery.go
  istio/discovery_internal_test.go
  istio/version.go
  istio/version_test.go
  mesh/api/testdata/test_mesh_graph.expected
  models/mesh.go
Labels: requires docs PR, requires operator PR

#8592 Remove `external_services.istio` settings that can be autodetected
  business/checkers/services/port_mapping_checker_test.go
  business/istio_validations.go
  business/istio_validations_test.go
  config/config.go
  graph/telemetry/istio/appender/mesh_check_test.go
  hack/run-kiali-config-template.yaml
  handlers/config.go
  istio/discovery.go
  istio/discovery_internal_test.go
  istio/discovery_test.go
  istio/version.go
  kubernetes/istio.go
  kubernetes/istio_test.go
  mesh/api/testdata/test_mesh_graph.expected
  models/pod.go
  models/workload.go
Labels: requires docs PR, requires operator PR

#8636 [CI] Install all the scripts needed in oc for Ambient
  hack/istio/ambient/install-sidecars-ambient.sh
  hack/istio/ambient/install-waypoints.sh
  hack/istio/ambient/resources/curl-pod.yaml
  hack/istio/ambient/resources/echo-service.yaml
  hack/istio/ambient/resources/egress-gateway.yaml
  hack/istio/ambient/resources/waypoint-for-workload.yaml
  hack/istio/ambient/resources/waypoint-forall.yaml
  hack/istio/ambient/resources/waypoint-fornone.yaml
  hack/istio/ambient/resources/waypoint-override.yaml
  hack/istio/ambient/resources/waypoint.yaml
  hack/istio/install-testing-demos.sh
Labels: test: front-end/cypress

#8675 Don't add GH actor if it is empty
  .github/workflows/integration-tests-backend-multicluster-external-controlplane.yml
  .github/workflows/integration-tests-backend.yml
  .github/workflows/integration-tests-frontend-ambient.yml
  .github/workflows/integration-tests-frontend-multicluster-multi-primary.yml
  .github/workflows/integration-tests-frontend-multicluster-primary-remote.yml
  .github/workflows/integration-tests-frontend-tempo.yml
  .github/workflows/integration-tests-frontend.yml
  hack/setup-kind-in-ci.sh
Labels: test: front-end/cypress

#8583 Perses
  business/istio_status.go
  business/istio_status_test.go
  config/config.go
  config/config_test.go
  doc.go
  frontend/src/assets/img/mesh/perses.svg
  frontend/src/components/Ambient/ZtunnelMetrics.tsx
  frontend/src/components/Metrics/IstioMetrics.tsx
  frontend/src/components/Metrics/PersesLinks.tsx
  frontend/src/components/Pf/PfBadges.tsx
  frontend/src/config/Config.ts
  frontend/src/pages/Mesh/MeshElems.tsx
  frontend/src/pages/Mesh/MeshLegendData.ts
  frontend/src/pages/Mesh/styles/MeshNode.tsx
  frontend/src/pages/Mesh/target/TargetPanelCommon.tsx
  frontend/src/pages/Mesh/toolbar/__tests__/__snapshots__/MeshLegend.test.tsx.snap
  frontend/src/pages/Overview/OverviewPage.tsx
  frontend/src/pages/Overview/__tests__/OverviewPage.test.tsx
  frontend/src/services/Api.ts
  frontend/src/types/Mesh.ts
  frontend/src/types/PersesInfo.ts
  grafana/grafana.go
  hack/run-kiali.sh
  handlers/mesh.go
  handlers/mesh_test.go
  handlers/perses.go
  handlers/root.go
  kiali_internal_api.md
  mesh/api/api.go
  mesh/api/api_test.go
  mesh/api/testdata/test_mesh_graph.expected
  mesh/appender.go
  mesh/generator/generator.go
  mesh/types.go
  mesh/util.go
  models/perses_info.go
  perses/perses.go
  perses/perses_test.go
  routing/router.go
  routing/router_test.go
  routing/routes.go
  server/server.go
  status/status.go
  status/versions.go
Labels: enhancement, requires operator PR
