Repository kiali/kiali, pull requests merged in 2025-06, with the labels that each got.

#8443 Add logic to show GW icon
  config/config.go
  frontend/src/pages/Graph/GraphElems.tsx
  graph/telemetry/istio/appender/istio_details.go
Labels: bug

#8466 Add partial selector match for ztunnel
  business/test_util.go
  business/workloads.go
  cache/cache.go
  cache/cache_test.go
  config/config.go
  kubernetes/filters.go
  mesh/api/testdata/test_mesh_graph.expected
Labels: ambient

#8471 Added datasourceUID into Grafana link.
  config/config.go
  config/dashboards/dashboards_config.go
  frontend/src/components/Ambient/ZtunnelMetrics.tsx
  frontend/src/components/Metrics/CustomMetrics.tsx
  frontend/src/components/Metrics/GrafanaLinks.tsx
  frontend/src/components/Metrics/IstioMetrics.tsx
  frontend/src/components/Metrics/__tests__/GrafanaLinks.test.ts
  frontend/src/types/Dashboards.ts
  frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
  frontend/src/types/GrafanaInfo.ts
  frontend/src/types/__testData__/HealthConfig.ts
  grafana/grafana.go
  grafana/grafana_test.go
  mesh/api/testdata/test_mesh_graph.expected
  models/grafana_info.go
Labels: requires docs PR, requires operator PR

#8487 Merge shared config map
  istio/discovery.go
Labels: bug

#8467 [perf] Debug info contains Performance Measurements
  frontend/public/locales/es/translation.json
  frontend/public/locales/zh/translation.json
  frontend/src/components/BreadcrumbView/BreadcrumbView.tsx
  frontend/src/components/DebugInformation/DebugInformation.tsx
  frontend/src/components/TracingIntegration/TracesFetcher.ts
  frontend/src/pages/AppList/AppListPage.tsx
  frontend/src/pages/Graph/SummaryPanelNodeTraces.tsx
  frontend/src/pages/ServiceList/ServiceListPage.tsx
  frontend/src/pages/WorkloadList/WorkloadListPage.tsx
  frontend/src/services/GraphDataSource.ts
  frontend/src/utils/Common.ts
  frontend/src/utils/PerformanceUtils.ts
Labels: enhancement

#8398 K8s GW API to v1.3.0
  business/checkers/common/multi_match_selector_checker.go
  business/checkers/k8sgateways/multi_match_checker.go
  frontend/cypress/integration/common/hooks.ts
  go.mod
  go.sum
  hack/istio/ambient/install-sidecars-ambient.sh
  hack/istio/ambient/install-waypoints.sh
  hack/istio/install-bookinfo-demo.sh
  hack/istio/install-error-rates-demo.sh
  hack/istio/install-travel-agency-demo.sh
  hack/istio/multicluster/setup-external-controlplane.sh
  make/Makefile.build.mk
  models/metrics.go
  tests/data/k8sgateway_data.go
Labels: backport needed

#8532 [v2.11] set up trace limit in config
  config/config.go
  frontend/src/components/Metrics/TraceLimit.tsx
  frontend/src/components/TracingIntegration/TracesDisplayOptions.tsx
  frontend/src/config/ServerConfig.ts
  frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
  frontend/src/types/ServerConfig.ts
  frontend/src/types/__testData__/HealthConfig.ts
Labels: enhancement, requires operator PR

#8497 Improve tracing tool
  business/tracing.go
  business/tracing_test.go
  frontend/public/locales/es/translation.json
  frontend/public/locales/zh/translation.json
  frontend/src/components/Mesh/CheckerTracingConfig.tsx
  frontend/src/components/Mesh/DiscoveryTracingConfig.tsx
  frontend/src/components/Mesh/LogsModal.tsx
  frontend/src/components/Mesh/TraceConfigurationModal.tsx
  frontend/src/components/Mesh/TraceDiagnose.tsx
  frontend/src/components/Mesh/TracingDiagnose.tsx
  frontend/src/components/Pf/PfColors.tsx
  frontend/src/config/Config.ts
  frontend/src/pages/Mesh/target/TargetPanelControlPlane.tsx
  frontend/src/pages/Mesh/target/TargetPanelNode.tsx
  frontend/src/services/Api.ts
  frontend/src/types/TracingInfo.ts
  handlers/tracing.go
  kiali.go
  routing/routes.go
  tracing/client.go
  tracing/client_test.go
  tracing/jaeger/grpc_client.go
  tracing/jaeger/http_client.go
  tracing/jaeger/model/types.go
  tracing/tempo/grpc_client.go
  tracing/tempo/http_client.go
  tracing/tracingtest/mock.go
Labels: enhancement
