Repository kiali/kiali, pull requests merged in 2025-04, with the labels that each got.

#7572 Kiali Spanish translation (initial)
  frontend/i18next-parser.config.ts
  frontend/public/locales/es/translation.json
  frontend/src/components/Nav/Masthead/LanguageSwitch.tsx
  frontend/src/components/Nav/__tests__/LanguageSwitch.test.tsx
  frontend/src/components/Nav/__tests__/__snapshots__/LanguageSwitch.test.tsx.snap
  frontend/src/types/Common.ts
Labels: test: front-end/cypress

#8312 [Mesh page] Don't fetch data if the previous call is still loading
  business/istio_status.go
  business/layer.go
  config/config.go
  frontend/src/pages/Mesh/MeshPage.tsx
  hack/istio/multicluster/deploy-kiali.sh
  hack/istio/multicluster/env.sh
  hack/setup-kind-in-ci.sh
  kubernetes/cache/cache.go
  mesh/generator/generator.go
  status/versions.go
Labels: bug

#8353 Manual refresh interval
  frontend/cypress/integration/common/graph_toolbar.ts
  frontend/cypress/integration/common/manual_refresh.ts
  frontend/cypress/integration/common/navigation.ts
  frontend/cypress/integration/featureFiles/manual_refresh.feature
  frontend/public/locales/es/translation.json
  frontend/public/locales/zh/translation.json
  frontend/src/actions/GraphActions.ts
  frontend/src/app/History.tsx
  frontend/src/components/Dropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
  frontend/src/components/Refresh/Refresh.tsx
  frontend/src/components/Time/TimeControl.tsx
  frontend/src/components/Time/TimeDurationComponent.tsx
  frontend/src/components/Time/TimeDurationModal.tsx
  frontend/src/components/VirtualList/EmptyVirtualList.tsx
  frontend/src/config/Config.ts
  frontend/src/hooks/refresh.ts
  frontend/src/pages/AppList/AppListPage.tsx
  frontend/src/pages/Graph/EmptyGraphLayout.tsx
  frontend/src/pages/Graph/Graph.tsx
  frontend/src/pages/Graph/GraphPage.tsx
  frontend/src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  frontend/src/pages/Graph/MiniGraphCard.tsx
  frontend/src/pages/Graph/SummaryPanel.tsx
  frontend/src/pages/Graph/SummaryPanelAppBox.tsx
  frontend/src/pages/Graph/SummaryPanelClusterBox.tsx
  frontend/src/pages/Graph/SummaryPanelNamespaceBox.tsx
  frontend/src/pages/Graph/SummaryPanelNode.tsx
  frontend/src/pages/Graph/SummaryPanelNodeTraffic.tsx
  frontend/src/pages/Graph/SummaryPanelTraceDetails.tsx
  frontend/src/pages/Graph/__tests__/SummaryPanelNode.test.tsx
  frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  frontend/src/pages/Mesh/EmptyMeshLayout.tsx
  frontend/src/pages/Mesh/MeshPage.tsx
  frontend/src/pages/Overview/EmptyOverview.tsx
  frontend/src/pages/Overview/OverviewPage.tsx
  frontend/src/pages/Overview/OverviewToolbar.tsx
  frontend/src/pages/Overview/__tests__/OverviewPage.test.tsx
  frontend/src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
  frontend/src/pages/ServiceList/ServiceListPage.tsx
  frontend/src/pages/WorkloadList/WorkloadListPage.tsx
  frontend/src/reducers/GraphDataState.ts
  frontend/src/routes.tsx
  frontend/src/types/Graph.ts
Labels: requires operator PR, test: front-end/cypress

#8369 Prevent returning the istiod status if no access to ztunnel config dump
  config/config.go
  istio/discovery.go
  kubernetes/cache/cache.go
  kubernetes/cache/cache_test.go
  kubernetes/cache/ztunnel_dump.go
  kubernetes/istio.go
Labels: enhancement

#8378 Use -latest as patch version
  .github/workflows/test-istio-version.yml
  hack/istio/download-istio.sh
Labels: maintenance
