Repository kiali/kiali, pull requests merged in 2025-05, with the labels that each got.

#8385 Include filter by name/namespace in ztunnel table
  frontend/cypress/integration/common/waypoint.ts
  frontend/cypress/integration/featureFiles/waypoint.feature
  frontend/public/locales/es/translation.json
  frontend/public/locales/zh/translation.json
  frontend/src/components/Ambient/Filters/ZtunnelFilters.tsx
  frontend/src/components/Ambient/Filters/ZtunnelLabels.tsx
  frontend/src/components/Ambient/ZtunnelConfig.tsx
  frontend/src/components/Filters/StatefulFilters.tsx
  frontend/src/types/IstioObjects.ts
Labels: enhancement, ambient

#8382 Update ztunnel field
  kubernetes/cache/cache_test.go
  kubernetes/cache/ztunnel_dump.go
  kubernetes/testdata/ztunnel-config.json
  kubernetes/ztunnel.go
Labels: enhancement, ambient

#8387 Fix failures for Test Istio Version jobs
  hack/setup-kind-in-ci.sh
  make/Makefile.build.mk
  tests/integration/controller/suite_test.go
Labels: maintenance

#8407 Update tracing query for errors
  tracing/tempo/http_client.go
Labels: bug

#8412 Add config option for specifying AdditionalCAs
  .gitleaks.toml
  business/dashboards.go
  business/istio_status.go
  business/openshift_oauth.go
  config/config.go
  config/config_test.go
  config/testdata/test-ca.pem
  grafana/grafana.go
  kubernetes/client.go
  kubernetes/istio.go
  kubernetes/kubernetes.go
  prometheus/client.go
  status/versions.go
  tests/integration/utils/kiali/kiali_client.go
  tests/integration/utils/kiali/retry.go
  tracing/client.go
  util/filetest/testing.go
  util/grpcutil/grpc_util.go
  util/httputil/http_util.go
  util/httputil/http_util_test.go
Labels: requires docs PR

#8395 Gateway API Classes auto-discovery
  business/istio_config.go
  business/istio_validations.go
  cache/cache.go
  config/config.go
  frontend/src/components/IstioWizards/K8sGatewaySelector.tsx
  frontend/src/pages/IstioConfigNew/K8sGatewayForm.tsx
  handlers/config.go
  kubernetes/istio.go
  mesh/api/testdata/test_mesh_graph.expected
Labels: requires docs PR, requires operator PR

#8419 Fix traffic animation rendering in OSSMC
  frontend/cypress/integration/common/graph_display.ts
  frontend/src/pages/Graph/TrafficAnimation/TrafficRenderer.tsx
Labels: test: front-end/cypress

#8330 Load user mesh config if set and display on the mesh page.
  business/istio_validations.go
  business/istio_validations_test.go
  business/mesh.go
  business/mesh_test.go
  business/tls.go
  business/tls_perf_test.go
  business/tls_test.go
  frontend/cypress/integration/common/data/istio-shared-mesh-configmap.yaml
  frontend/cypress/integration/common/hooks.ts
  frontend/cypress/integration/common/mesh.ts
  frontend/cypress/integration/featureFiles/mesh.feature
  frontend/public/locales/es/translation.json
  frontend/public/locales/zh/translation.json
  frontend/src/components/IstioCertsInfo/IstioCertsInfo.tsx
  frontend/src/components/MTls/MeshMTLSStatus.tsx
  frontend/src/components/Mesh/ConfigButtonsTargetPanel.tsx
  frontend/src/components/Overview/TLSInfo.tsx
  frontend/src/components/Tab/SimpleTabs.tsx
  frontend/src/pages/Mesh/target/TargetPanelCommon.tsx
  frontend/src/pages/Mesh/target/TargetPanelControlPlane.tsx
  frontend/src/pages/Mesh/target/TargetPanelControlPlaneMetrics.tsx
  frontend/src/pages/Mesh/target/TargetPanelControlPlaneStatus.tsx
  frontend/src/pages/Mesh/target/TargetPanelEditor.tsx
  frontend/src/types/Mesh.ts
  graph/telemetry/istio/appender/service_entry_test.go
  handlers/mesh.go
  istio/discovery.go
  istio/discovery_internal_test.go
  istio/discovery_test.go
  mesh/api/testdata/test_mesh_graph.expected
  models/mesh.go
  models/mesh_test.go
  tests/integration/controller/validations_test.go
Labels: test: front-end/cypress, test: back-end/integration

#8452 Kiali tracing cluster tag
  business/apps.go
  business/health.go
  business/istio_config.go
  business/istio_validations.go
  business/namespaces.go
  business/services.go
  business/tls.go
  business/tracing.go
  business/workloads.go
  observability/tracing.go
Labels: bug

#8460 script to check if a remote cluster secret is correct
  hack/istio/multicluster/verify-kiali-permissions.sh
Labels: requires docs PR
